// Code generated by mockery. DO NOT EDIT.

package storespb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeStoresServiceServer is an autogenerated mock type for the UnsafeStoresServiceServer type
type MockUnsafeStoresServiceServer struct {
	mock.Mock
}

type MockUnsafeStoresServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeStoresServiceServer) EXPECT() *MockUnsafeStoresServiceServer_Expecter {
	return &MockUnsafeStoresServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedStoresServiceServer provides a mock function with no fields
func (_m *MockUnsafeStoresServiceServer) mustEmbedUnimplementedStoresServiceServer() {
	_m.Called()
}

// MockUnsafeStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedStoresServiceServer'
type MockUnsafeStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedStoresServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeStoresServiceServer_Expecter) mustEmbedUnimplementedStoresServiceServer() *MockUnsafeStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call {
	return &MockUnsafeStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedStoresServiceServer")}
}

func (_c *MockUnsafeStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call) Run(run func()) *MockUnsafeStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call) Return() *MockUnsafeStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call) RunAndReturn(run func()) *MockUnsafeStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockUnsafeStoresServiceServer creates a new instance of MockUnsafeStoresServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeStoresServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeStoresServiceServer {
	mock := &MockUnsafeStoresServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
