// Code generated by mockery. DO NOT EDIT.

package storespb

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStoresServiceServer is an autogenerated mock type for the StoresServiceServer type
type MockStoresServiceServer struct {
	mock.Mock
}

type MockStoresServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoresServiceServer) EXPECT() *MockStoresServiceServer_Expecter {
	return &MockStoresServiceServer_Expecter{mock: &_m.Mock}
}

// AddProduct provides a mock function with given fields: _a0, _a1
func (_m *MockStoresServiceServer) AddProduct(_a0 context.Context, _a1 *AddProductRequest) (*AddProductResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AddProduct")
	}

	var r0 *AddProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *AddProductRequest) (*AddProductResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *AddProductRequest) *AddProductResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AddProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *AddProductRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoresServiceServer_AddProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProduct'
type MockStoresServiceServer_AddProduct_Call struct {
	*mock.Call
}

// AddProduct is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *AddProductRequest
func (_e *MockStoresServiceServer_Expecter) AddProduct(_a0 interface{}, _a1 interface{}) *MockStoresServiceServer_AddProduct_Call {
	return &MockStoresServiceServer_AddProduct_Call{Call: _e.mock.On("AddProduct", _a0, _a1)}
}

func (_c *MockStoresServiceServer_AddProduct_Call) Run(run func(_a0 context.Context, _a1 *AddProductRequest)) *MockStoresServiceServer_AddProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*AddProductRequest))
	})
	return _c
}

func (_c *MockStoresServiceServer_AddProduct_Call) Return(_a0 *AddProductResponse, _a1 error) *MockStoresServiceServer_AddProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoresServiceServer_AddProduct_Call) RunAndReturn(run func(context.Context, *AddProductRequest) (*AddProductResponse, error)) *MockStoresServiceServer_AddProduct_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStore provides a mock function with given fields: _a0, _a1
func (_m *MockStoresServiceServer) CreateStore(_a0 context.Context, _a1 *CreateStoreRequest) (*CreateStoreResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateStore")
	}

	var r0 *CreateStoreResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *CreateStoreRequest) (*CreateStoreResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *CreateStoreRequest) *CreateStoreResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CreateStoreResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *CreateStoreRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoresServiceServer_CreateStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStore'
type MockStoresServiceServer_CreateStore_Call struct {
	*mock.Call
}

// CreateStore is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *CreateStoreRequest
func (_e *MockStoresServiceServer_Expecter) CreateStore(_a0 interface{}, _a1 interface{}) *MockStoresServiceServer_CreateStore_Call {
	return &MockStoresServiceServer_CreateStore_Call{Call: _e.mock.On("CreateStore", _a0, _a1)}
}

func (_c *MockStoresServiceServer_CreateStore_Call) Run(run func(_a0 context.Context, _a1 *CreateStoreRequest)) *MockStoresServiceServer_CreateStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*CreateStoreRequest))
	})
	return _c
}

func (_c *MockStoresServiceServer_CreateStore_Call) Return(_a0 *CreateStoreResponse, _a1 error) *MockStoresServiceServer_CreateStore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoresServiceServer_CreateStore_Call) RunAndReturn(run func(context.Context, *CreateStoreRequest) (*CreateStoreResponse, error)) *MockStoresServiceServer_CreateStore_Call {
	_c.Call.Return(run)
	return _c
}

// DecreaseProductPrice provides a mock function with given fields: _a0, _a1
func (_m *MockStoresServiceServer) DecreaseProductPrice(_a0 context.Context, _a1 *DecreaseProductPriceRequest) (*DecreaseProductPriceResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DecreaseProductPrice")
	}

	var r0 *DecreaseProductPriceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *DecreaseProductPriceRequest) (*DecreaseProductPriceResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *DecreaseProductPriceRequest) *DecreaseProductPriceResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DecreaseProductPriceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *DecreaseProductPriceRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoresServiceServer_DecreaseProductPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecreaseProductPrice'
type MockStoresServiceServer_DecreaseProductPrice_Call struct {
	*mock.Call
}

// DecreaseProductPrice is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *DecreaseProductPriceRequest
func (_e *MockStoresServiceServer_Expecter) DecreaseProductPrice(_a0 interface{}, _a1 interface{}) *MockStoresServiceServer_DecreaseProductPrice_Call {
	return &MockStoresServiceServer_DecreaseProductPrice_Call{Call: _e.mock.On("DecreaseProductPrice", _a0, _a1)}
}

func (_c *MockStoresServiceServer_DecreaseProductPrice_Call) Run(run func(_a0 context.Context, _a1 *DecreaseProductPriceRequest)) *MockStoresServiceServer_DecreaseProductPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*DecreaseProductPriceRequest))
	})
	return _c
}

func (_c *MockStoresServiceServer_DecreaseProductPrice_Call) Return(_a0 *DecreaseProductPriceResponse, _a1 error) *MockStoresServiceServer_DecreaseProductPrice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoresServiceServer_DecreaseProductPrice_Call) RunAndReturn(run func(context.Context, *DecreaseProductPriceRequest) (*DecreaseProductPriceResponse, error)) *MockStoresServiceServer_DecreaseProductPrice_Call {
	_c.Call.Return(run)
	return _c
}

// DisableParticipation provides a mock function with given fields: _a0, _a1
func (_m *MockStoresServiceServer) DisableParticipation(_a0 context.Context, _a1 *DisableParticipationRequest) (*DisableParticipationResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for DisableParticipation")
	}

	var r0 *DisableParticipationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *DisableParticipationRequest) (*DisableParticipationResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *DisableParticipationRequest) *DisableParticipationResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DisableParticipationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *DisableParticipationRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoresServiceServer_DisableParticipation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableParticipation'
type MockStoresServiceServer_DisableParticipation_Call struct {
	*mock.Call
}

// DisableParticipation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *DisableParticipationRequest
func (_e *MockStoresServiceServer_Expecter) DisableParticipation(_a0 interface{}, _a1 interface{}) *MockStoresServiceServer_DisableParticipation_Call {
	return &MockStoresServiceServer_DisableParticipation_Call{Call: _e.mock.On("DisableParticipation", _a0, _a1)}
}

func (_c *MockStoresServiceServer_DisableParticipation_Call) Run(run func(_a0 context.Context, _a1 *DisableParticipationRequest)) *MockStoresServiceServer_DisableParticipation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*DisableParticipationRequest))
	})
	return _c
}

func (_c *MockStoresServiceServer_DisableParticipation_Call) Return(_a0 *DisableParticipationResponse, _a1 error) *MockStoresServiceServer_DisableParticipation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoresServiceServer_DisableParticipation_Call) RunAndReturn(run func(context.Context, *DisableParticipationRequest) (*DisableParticipationResponse, error)) *MockStoresServiceServer_DisableParticipation_Call {
	_c.Call.Return(run)
	return _c
}

// EnableParticipation provides a mock function with given fields: _a0, _a1
func (_m *MockStoresServiceServer) EnableParticipation(_a0 context.Context, _a1 *EnableParticipationRequest) (*EnableParticipationResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for EnableParticipation")
	}

	var r0 *EnableParticipationResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *EnableParticipationRequest) (*EnableParticipationResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *EnableParticipationRequest) *EnableParticipationResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*EnableParticipationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *EnableParticipationRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoresServiceServer_EnableParticipation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableParticipation'
type MockStoresServiceServer_EnableParticipation_Call struct {
	*mock.Call
}

// EnableParticipation is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *EnableParticipationRequest
func (_e *MockStoresServiceServer_Expecter) EnableParticipation(_a0 interface{}, _a1 interface{}) *MockStoresServiceServer_EnableParticipation_Call {
	return &MockStoresServiceServer_EnableParticipation_Call{Call: _e.mock.On("EnableParticipation", _a0, _a1)}
}

func (_c *MockStoresServiceServer_EnableParticipation_Call) Run(run func(_a0 context.Context, _a1 *EnableParticipationRequest)) *MockStoresServiceServer_EnableParticipation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*EnableParticipationRequest))
	})
	return _c
}

func (_c *MockStoresServiceServer_EnableParticipation_Call) Return(_a0 *EnableParticipationResponse, _a1 error) *MockStoresServiceServer_EnableParticipation_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoresServiceServer_EnableParticipation_Call) RunAndReturn(run func(context.Context, *EnableParticipationRequest) (*EnableParticipationResponse, error)) *MockStoresServiceServer_EnableParticipation_Call {
	_c.Call.Return(run)
	return _c
}

// GetCatalog provides a mock function with given fields: _a0, _a1
func (_m *MockStoresServiceServer) GetCatalog(_a0 context.Context, _a1 *GetCatalogRequest) (*GetCatalogResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetCatalog")
	}

	var r0 *GetCatalogResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetCatalogRequest) (*GetCatalogResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetCatalogRequest) *GetCatalogResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetCatalogResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetCatalogRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoresServiceServer_GetCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCatalog'
type MockStoresServiceServer_GetCatalog_Call struct {
	*mock.Call
}

// GetCatalog is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *GetCatalogRequest
func (_e *MockStoresServiceServer_Expecter) GetCatalog(_a0 interface{}, _a1 interface{}) *MockStoresServiceServer_GetCatalog_Call {
	return &MockStoresServiceServer_GetCatalog_Call{Call: _e.mock.On("GetCatalog", _a0, _a1)}
}

func (_c *MockStoresServiceServer_GetCatalog_Call) Run(run func(_a0 context.Context, _a1 *GetCatalogRequest)) *MockStoresServiceServer_GetCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*GetCatalogRequest))
	})
	return _c
}

func (_c *MockStoresServiceServer_GetCatalog_Call) Return(_a0 *GetCatalogResponse, _a1 error) *MockStoresServiceServer_GetCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoresServiceServer_GetCatalog_Call) RunAndReturn(run func(context.Context, *GetCatalogRequest) (*GetCatalogResponse, error)) *MockStoresServiceServer_GetCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipatingStores provides a mock function with given fields: _a0, _a1
func (_m *MockStoresServiceServer) GetParticipatingStores(_a0 context.Context, _a1 *GetParticipatingStoresRequest) (*GetParticipatingStoresResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipatingStores")
	}

	var r0 *GetParticipatingStoresResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetParticipatingStoresRequest) (*GetParticipatingStoresResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetParticipatingStoresRequest) *GetParticipatingStoresResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetParticipatingStoresResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetParticipatingStoresRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoresServiceServer_GetParticipatingStores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipatingStores'
type MockStoresServiceServer_GetParticipatingStores_Call struct {
	*mock.Call
}

// GetParticipatingStores is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *GetParticipatingStoresRequest
func (_e *MockStoresServiceServer_Expecter) GetParticipatingStores(_a0 interface{}, _a1 interface{}) *MockStoresServiceServer_GetParticipatingStores_Call {
	return &MockStoresServiceServer_GetParticipatingStores_Call{Call: _e.mock.On("GetParticipatingStores", _a0, _a1)}
}

func (_c *MockStoresServiceServer_GetParticipatingStores_Call) Run(run func(_a0 context.Context, _a1 *GetParticipatingStoresRequest)) *MockStoresServiceServer_GetParticipatingStores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*GetParticipatingStoresRequest))
	})
	return _c
}

func (_c *MockStoresServiceServer_GetParticipatingStores_Call) Return(_a0 *GetParticipatingStoresResponse, _a1 error) *MockStoresServiceServer_GetParticipatingStores_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoresServiceServer_GetParticipatingStores_Call) RunAndReturn(run func(context.Context, *GetParticipatingStoresRequest) (*GetParticipatingStoresResponse, error)) *MockStoresServiceServer_GetParticipatingStores_Call {
	_c.Call.Return(run)
	return _c
}

// GetProduct provides a mock function with given fields: _a0, _a1
func (_m *MockStoresServiceServer) GetProduct(_a0 context.Context, _a1 *GetProductRequest) (*GetProductResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *GetProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetProductRequest) (*GetProductResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetProductRequest) *GetProductResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetProductRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoresServiceServer_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type MockStoresServiceServer_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *GetProductRequest
func (_e *MockStoresServiceServer_Expecter) GetProduct(_a0 interface{}, _a1 interface{}) *MockStoresServiceServer_GetProduct_Call {
	return &MockStoresServiceServer_GetProduct_Call{Call: _e.mock.On("GetProduct", _a0, _a1)}
}

func (_c *MockStoresServiceServer_GetProduct_Call) Run(run func(_a0 context.Context, _a1 *GetProductRequest)) *MockStoresServiceServer_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*GetProductRequest))
	})
	return _c
}

func (_c *MockStoresServiceServer_GetProduct_Call) Return(_a0 *GetProductResponse, _a1 error) *MockStoresServiceServer_GetProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoresServiceServer_GetProduct_Call) RunAndReturn(run func(context.Context, *GetProductRequest) (*GetProductResponse, error)) *MockStoresServiceServer_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetStore provides a mock function with given fields: _a0, _a1
func (_m *MockStoresServiceServer) GetStore(_a0 context.Context, _a1 *GetStoreRequest) (*GetStoreResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetStore")
	}

	var r0 *GetStoreResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetStoreRequest) (*GetStoreResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetStoreRequest) *GetStoreResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetStoreResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetStoreRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoresServiceServer_GetStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStore'
type MockStoresServiceServer_GetStore_Call struct {
	*mock.Call
}

// GetStore is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *GetStoreRequest
func (_e *MockStoresServiceServer_Expecter) GetStore(_a0 interface{}, _a1 interface{}) *MockStoresServiceServer_GetStore_Call {
	return &MockStoresServiceServer_GetStore_Call{Call: _e.mock.On("GetStore", _a0, _a1)}
}

func (_c *MockStoresServiceServer_GetStore_Call) Run(run func(_a0 context.Context, _a1 *GetStoreRequest)) *MockStoresServiceServer_GetStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*GetStoreRequest))
	})
	return _c
}

func (_c *MockStoresServiceServer_GetStore_Call) Return(_a0 *GetStoreResponse, _a1 error) *MockStoresServiceServer_GetStore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoresServiceServer_GetStore_Call) RunAndReturn(run func(context.Context, *GetStoreRequest) (*GetStoreResponse, error)) *MockStoresServiceServer_GetStore_Call {
	_c.Call.Return(run)
	return _c
}

// GetStores provides a mock function with given fields: _a0, _a1
func (_m *MockStoresServiceServer) GetStores(_a0 context.Context, _a1 *GetStoresRequest) (*GetStoresResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetStores")
	}

	var r0 *GetStoresResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetStoresRequest) (*GetStoresResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetStoresRequest) *GetStoresResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetStoresResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetStoresRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoresServiceServer_GetStores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStores'
type MockStoresServiceServer_GetStores_Call struct {
	*mock.Call
}

// GetStores is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *GetStoresRequest
func (_e *MockStoresServiceServer_Expecter) GetStores(_a0 interface{}, _a1 interface{}) *MockStoresServiceServer_GetStores_Call {
	return &MockStoresServiceServer_GetStores_Call{Call: _e.mock.On("GetStores", _a0, _a1)}
}

func (_c *MockStoresServiceServer_GetStores_Call) Run(run func(_a0 context.Context, _a1 *GetStoresRequest)) *MockStoresServiceServer_GetStores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*GetStoresRequest))
	})
	return _c
}

func (_c *MockStoresServiceServer_GetStores_Call) Return(_a0 *GetStoresResponse, _a1 error) *MockStoresServiceServer_GetStores_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoresServiceServer_GetStores_Call) RunAndReturn(run func(context.Context, *GetStoresRequest) (*GetStoresResponse, error)) *MockStoresServiceServer_GetStores_Call {
	_c.Call.Return(run)
	return _c
}

// IncreaseProductPrice provides a mock function with given fields: _a0, _a1
func (_m *MockStoresServiceServer) IncreaseProductPrice(_a0 context.Context, _a1 *IncreaseProductPriceRequest) (*IncreaseProductPriceResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for IncreaseProductPrice")
	}

	var r0 *IncreaseProductPriceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *IncreaseProductPriceRequest) (*IncreaseProductPriceResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *IncreaseProductPriceRequest) *IncreaseProductPriceResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*IncreaseProductPriceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *IncreaseProductPriceRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoresServiceServer_IncreaseProductPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncreaseProductPrice'
type MockStoresServiceServer_IncreaseProductPrice_Call struct {
	*mock.Call
}

// IncreaseProductPrice is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *IncreaseProductPriceRequest
func (_e *MockStoresServiceServer_Expecter) IncreaseProductPrice(_a0 interface{}, _a1 interface{}) *MockStoresServiceServer_IncreaseProductPrice_Call {
	return &MockStoresServiceServer_IncreaseProductPrice_Call{Call: _e.mock.On("IncreaseProductPrice", _a0, _a1)}
}

func (_c *MockStoresServiceServer_IncreaseProductPrice_Call) Run(run func(_a0 context.Context, _a1 *IncreaseProductPriceRequest)) *MockStoresServiceServer_IncreaseProductPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*IncreaseProductPriceRequest))
	})
	return _c
}

func (_c *MockStoresServiceServer_IncreaseProductPrice_Call) Return(_a0 *IncreaseProductPriceResponse, _a1 error) *MockStoresServiceServer_IncreaseProductPrice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoresServiceServer_IncreaseProductPrice_Call) RunAndReturn(run func(context.Context, *IncreaseProductPriceRequest) (*IncreaseProductPriceResponse, error)) *MockStoresServiceServer_IncreaseProductPrice_Call {
	_c.Call.Return(run)
	return _c
}

// RebrandProduct provides a mock function with given fields: _a0, _a1
func (_m *MockStoresServiceServer) RebrandProduct(_a0 context.Context, _a1 *RebrandProductRequest) (*RebrandProductResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RebrandProduct")
	}

	var r0 *RebrandProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *RebrandProductRequest) (*RebrandProductResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *RebrandProductRequest) *RebrandProductResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RebrandProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *RebrandProductRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoresServiceServer_RebrandProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RebrandProduct'
type MockStoresServiceServer_RebrandProduct_Call struct {
	*mock.Call
}

// RebrandProduct is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *RebrandProductRequest
func (_e *MockStoresServiceServer_Expecter) RebrandProduct(_a0 interface{}, _a1 interface{}) *MockStoresServiceServer_RebrandProduct_Call {
	return &MockStoresServiceServer_RebrandProduct_Call{Call: _e.mock.On("RebrandProduct", _a0, _a1)}
}

func (_c *MockStoresServiceServer_RebrandProduct_Call) Run(run func(_a0 context.Context, _a1 *RebrandProductRequest)) *MockStoresServiceServer_RebrandProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*RebrandProductRequest))
	})
	return _c
}

func (_c *MockStoresServiceServer_RebrandProduct_Call) Return(_a0 *RebrandProductResponse, _a1 error) *MockStoresServiceServer_RebrandProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoresServiceServer_RebrandProduct_Call) RunAndReturn(run func(context.Context, *RebrandProductRequest) (*RebrandProductResponse, error)) *MockStoresServiceServer_RebrandProduct_Call {
	_c.Call.Return(run)
	return _c
}

// RebrandStore provides a mock function with given fields: _a0, _a1
func (_m *MockStoresServiceServer) RebrandStore(_a0 context.Context, _a1 *RebrandStoreRequest) (*RebrandStoreResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RebrandStore")
	}

	var r0 *RebrandStoreResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *RebrandStoreRequest) (*RebrandStoreResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *RebrandStoreRequest) *RebrandStoreResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RebrandStoreResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *RebrandStoreRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoresServiceServer_RebrandStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RebrandStore'
type MockStoresServiceServer_RebrandStore_Call struct {
	*mock.Call
}

// RebrandStore is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *RebrandStoreRequest
func (_e *MockStoresServiceServer_Expecter) RebrandStore(_a0 interface{}, _a1 interface{}) *MockStoresServiceServer_RebrandStore_Call {
	return &MockStoresServiceServer_RebrandStore_Call{Call: _e.mock.On("RebrandStore", _a0, _a1)}
}

func (_c *MockStoresServiceServer_RebrandStore_Call) Run(run func(_a0 context.Context, _a1 *RebrandStoreRequest)) *MockStoresServiceServer_RebrandStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*RebrandStoreRequest))
	})
	return _c
}

func (_c *MockStoresServiceServer_RebrandStore_Call) Return(_a0 *RebrandStoreResponse, _a1 error) *MockStoresServiceServer_RebrandStore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoresServiceServer_RebrandStore_Call) RunAndReturn(run func(context.Context, *RebrandStoreRequest) (*RebrandStoreResponse, error)) *MockStoresServiceServer_RebrandStore_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveProduct provides a mock function with given fields: _a0, _a1
func (_m *MockStoresServiceServer) RemoveProduct(_a0 context.Context, _a1 *RemoveProductRequest) (*RemoveProductResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProduct")
	}

	var r0 *RemoveProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *RemoveProductRequest) (*RemoveProductResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *RemoveProductRequest) *RemoveProductResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RemoveProductResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *RemoveProductRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoresServiceServer_RemoveProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveProduct'
type MockStoresServiceServer_RemoveProduct_Call struct {
	*mock.Call
}

// RemoveProduct is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *RemoveProductRequest
func (_e *MockStoresServiceServer_Expecter) RemoveProduct(_a0 interface{}, _a1 interface{}) *MockStoresServiceServer_RemoveProduct_Call {
	return &MockStoresServiceServer_RemoveProduct_Call{Call: _e.mock.On("RemoveProduct", _a0, _a1)}
}

func (_c *MockStoresServiceServer_RemoveProduct_Call) Run(run func(_a0 context.Context, _a1 *RemoveProductRequest)) *MockStoresServiceServer_RemoveProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*RemoveProductRequest))
	})
	return _c
}

func (_c *MockStoresServiceServer_RemoveProduct_Call) Return(_a0 *RemoveProductResponse, _a1 error) *MockStoresServiceServer_RemoveProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoresServiceServer_RemoveProduct_Call) RunAndReturn(run func(context.Context, *RemoveProductRequest) (*RemoveProductResponse, error)) *MockStoresServiceServer_RemoveProduct_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedStoresServiceServer provides a mock function with no fields
func (_m *MockStoresServiceServer) mustEmbedUnimplementedStoresServiceServer() {
	_m.Called()
}

// MockStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedStoresServiceServer'
type MockStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedStoresServiceServer is a helper method to define mock.On call
func (_e *MockStoresServiceServer_Expecter) mustEmbedUnimplementedStoresServiceServer() *MockStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call {
	return &MockStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedStoresServiceServer")}
}

func (_c *MockStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call) Run(run func()) *MockStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call) Return() *MockStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call) RunAndReturn(run func()) *MockStoresServiceServer_mustEmbedUnimplementedStoresServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockStoresServiceServer creates a new instance of MockStoresServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoresServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoresServiceServer {
	mock := &MockStoresServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
