// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: orderingpb/api.proto

package orderingpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	orderingpb "github.com/owezzy/soko-bora-mngt-system/ordering/orderingpb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// OrderingServiceName is the fully-qualified name of the OrderingService service.
	OrderingServiceName = "orderingpb.OrderingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// OrderingServiceCreateOrderProcedure is the fully-qualified name of the OrderingService's
	// CreateOrder RPC.
	OrderingServiceCreateOrderProcedure = "/orderingpb.OrderingService/CreateOrder"
	// OrderingServiceGetOrderProcedure is the fully-qualified name of the OrderingService's GetOrder
	// RPC.
	OrderingServiceGetOrderProcedure = "/orderingpb.OrderingService/GetOrder"
	// OrderingServiceCancelOrderProcedure is the fully-qualified name of the OrderingService's
	// CancelOrder RPC.
	OrderingServiceCancelOrderProcedure = "/orderingpb.OrderingService/CancelOrder"
	// OrderingServiceReadyOrderProcedure is the fully-qualified name of the OrderingService's
	// ReadyOrder RPC.
	OrderingServiceReadyOrderProcedure = "/orderingpb.OrderingService/ReadyOrder"
	// OrderingServiceCompleteOrderProcedure is the fully-qualified name of the OrderingService's
	// CompleteOrder RPC.
	OrderingServiceCompleteOrderProcedure = "/orderingpb.OrderingService/CompleteOrder"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	orderingServiceServiceDescriptor             = orderingpb.File_orderingpb_api_proto.Services().ByName("OrderingService")
	orderingServiceCreateOrderMethodDescriptor   = orderingServiceServiceDescriptor.Methods().ByName("CreateOrder")
	orderingServiceGetOrderMethodDescriptor      = orderingServiceServiceDescriptor.Methods().ByName("GetOrder")
	orderingServiceCancelOrderMethodDescriptor   = orderingServiceServiceDescriptor.Methods().ByName("CancelOrder")
	orderingServiceReadyOrderMethodDescriptor    = orderingServiceServiceDescriptor.Methods().ByName("ReadyOrder")
	orderingServiceCompleteOrderMethodDescriptor = orderingServiceServiceDescriptor.Methods().ByName("CompleteOrder")
)

// OrderingServiceClient is a client for the orderingpb.OrderingService service.
type OrderingServiceClient interface {
	CreateOrder(context.Context, *connect.Request[orderingpb.CreateOrderRequest]) (*connect.Response[orderingpb.CreateOrderResponse], error)
	GetOrder(context.Context, *connect.Request[orderingpb.GetOrderRequest]) (*connect.Response[orderingpb.GetOrderResponse], error)
	CancelOrder(context.Context, *connect.Request[orderingpb.CancelOrderRequest]) (*connect.Response[orderingpb.CancelOrderResponse], error)
	ReadyOrder(context.Context, *connect.Request[orderingpb.ReadyOrderRequest]) (*connect.Response[orderingpb.ReadyOrderResponse], error)
	CompleteOrder(context.Context, *connect.Request[orderingpb.CompleteOrderRequest]) (*connect.Response[orderingpb.CompleteOrderResponse], error)
}

// NewOrderingServiceClient constructs a client for the orderingpb.OrderingService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewOrderingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) OrderingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &orderingServiceClient{
		createOrder: connect.NewClient[orderingpb.CreateOrderRequest, orderingpb.CreateOrderResponse](
			httpClient,
			baseURL+OrderingServiceCreateOrderProcedure,
			connect.WithSchema(orderingServiceCreateOrderMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getOrder: connect.NewClient[orderingpb.GetOrderRequest, orderingpb.GetOrderResponse](
			httpClient,
			baseURL+OrderingServiceGetOrderProcedure,
			connect.WithSchema(orderingServiceGetOrderMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		cancelOrder: connect.NewClient[orderingpb.CancelOrderRequest, orderingpb.CancelOrderResponse](
			httpClient,
			baseURL+OrderingServiceCancelOrderProcedure,
			connect.WithSchema(orderingServiceCancelOrderMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		readyOrder: connect.NewClient[orderingpb.ReadyOrderRequest, orderingpb.ReadyOrderResponse](
			httpClient,
			baseURL+OrderingServiceReadyOrderProcedure,
			connect.WithSchema(orderingServiceReadyOrderMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		completeOrder: connect.NewClient[orderingpb.CompleteOrderRequest, orderingpb.CompleteOrderResponse](
			httpClient,
			baseURL+OrderingServiceCompleteOrderProcedure,
			connect.WithSchema(orderingServiceCompleteOrderMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// orderingServiceClient implements OrderingServiceClient.
type orderingServiceClient struct {
	createOrder   *connect.Client[orderingpb.CreateOrderRequest, orderingpb.CreateOrderResponse]
	getOrder      *connect.Client[orderingpb.GetOrderRequest, orderingpb.GetOrderResponse]
	cancelOrder   *connect.Client[orderingpb.CancelOrderRequest, orderingpb.CancelOrderResponse]
	readyOrder    *connect.Client[orderingpb.ReadyOrderRequest, orderingpb.ReadyOrderResponse]
	completeOrder *connect.Client[orderingpb.CompleteOrderRequest, orderingpb.CompleteOrderResponse]
}

// CreateOrder calls orderingpb.OrderingService.CreateOrder.
func (c *orderingServiceClient) CreateOrder(ctx context.Context, req *connect.Request[orderingpb.CreateOrderRequest]) (*connect.Response[orderingpb.CreateOrderResponse], error) {
	return c.createOrder.CallUnary(ctx, req)
}

// GetOrder calls orderingpb.OrderingService.GetOrder.
func (c *orderingServiceClient) GetOrder(ctx context.Context, req *connect.Request[orderingpb.GetOrderRequest]) (*connect.Response[orderingpb.GetOrderResponse], error) {
	return c.getOrder.CallUnary(ctx, req)
}

// CancelOrder calls orderingpb.OrderingService.CancelOrder.
func (c *orderingServiceClient) CancelOrder(ctx context.Context, req *connect.Request[orderingpb.CancelOrderRequest]) (*connect.Response[orderingpb.CancelOrderResponse], error) {
	return c.cancelOrder.CallUnary(ctx, req)
}

// ReadyOrder calls orderingpb.OrderingService.ReadyOrder.
func (c *orderingServiceClient) ReadyOrder(ctx context.Context, req *connect.Request[orderingpb.ReadyOrderRequest]) (*connect.Response[orderingpb.ReadyOrderResponse], error) {
	return c.readyOrder.CallUnary(ctx, req)
}

// CompleteOrder calls orderingpb.OrderingService.CompleteOrder.
func (c *orderingServiceClient) CompleteOrder(ctx context.Context, req *connect.Request[orderingpb.CompleteOrderRequest]) (*connect.Response[orderingpb.CompleteOrderResponse], error) {
	return c.completeOrder.CallUnary(ctx, req)
}

// OrderingServiceHandler is an implementation of the orderingpb.OrderingService service.
type OrderingServiceHandler interface {
	CreateOrder(context.Context, *connect.Request[orderingpb.CreateOrderRequest]) (*connect.Response[orderingpb.CreateOrderResponse], error)
	GetOrder(context.Context, *connect.Request[orderingpb.GetOrderRequest]) (*connect.Response[orderingpb.GetOrderResponse], error)
	CancelOrder(context.Context, *connect.Request[orderingpb.CancelOrderRequest]) (*connect.Response[orderingpb.CancelOrderResponse], error)
	ReadyOrder(context.Context, *connect.Request[orderingpb.ReadyOrderRequest]) (*connect.Response[orderingpb.ReadyOrderResponse], error)
	CompleteOrder(context.Context, *connect.Request[orderingpb.CompleteOrderRequest]) (*connect.Response[orderingpb.CompleteOrderResponse], error)
}

// NewOrderingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewOrderingServiceHandler(svc OrderingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	orderingServiceCreateOrderHandler := connect.NewUnaryHandler(
		OrderingServiceCreateOrderProcedure,
		svc.CreateOrder,
		connect.WithSchema(orderingServiceCreateOrderMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	orderingServiceGetOrderHandler := connect.NewUnaryHandler(
		OrderingServiceGetOrderProcedure,
		svc.GetOrder,
		connect.WithSchema(orderingServiceGetOrderMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	orderingServiceCancelOrderHandler := connect.NewUnaryHandler(
		OrderingServiceCancelOrderProcedure,
		svc.CancelOrder,
		connect.WithSchema(orderingServiceCancelOrderMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	orderingServiceReadyOrderHandler := connect.NewUnaryHandler(
		OrderingServiceReadyOrderProcedure,
		svc.ReadyOrder,
		connect.WithSchema(orderingServiceReadyOrderMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	orderingServiceCompleteOrderHandler := connect.NewUnaryHandler(
		OrderingServiceCompleteOrderProcedure,
		svc.CompleteOrder,
		connect.WithSchema(orderingServiceCompleteOrderMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/orderingpb.OrderingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case OrderingServiceCreateOrderProcedure:
			orderingServiceCreateOrderHandler.ServeHTTP(w, r)
		case OrderingServiceGetOrderProcedure:
			orderingServiceGetOrderHandler.ServeHTTP(w, r)
		case OrderingServiceCancelOrderProcedure:
			orderingServiceCancelOrderHandler.ServeHTTP(w, r)
		case OrderingServiceReadyOrderProcedure:
			orderingServiceReadyOrderHandler.ServeHTTP(w, r)
		case OrderingServiceCompleteOrderProcedure:
			orderingServiceCompleteOrderHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedOrderingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedOrderingServiceHandler struct{}

func (UnimplementedOrderingServiceHandler) CreateOrder(context.Context, *connect.Request[orderingpb.CreateOrderRequest]) (*connect.Response[orderingpb.CreateOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orderingpb.OrderingService.CreateOrder is not implemented"))
}

func (UnimplementedOrderingServiceHandler) GetOrder(context.Context, *connect.Request[orderingpb.GetOrderRequest]) (*connect.Response[orderingpb.GetOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orderingpb.OrderingService.GetOrder is not implemented"))
}

func (UnimplementedOrderingServiceHandler) CancelOrder(context.Context, *connect.Request[orderingpb.CancelOrderRequest]) (*connect.Response[orderingpb.CancelOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orderingpb.OrderingService.CancelOrder is not implemented"))
}

func (UnimplementedOrderingServiceHandler) ReadyOrder(context.Context, *connect.Request[orderingpb.ReadyOrderRequest]) (*connect.Response[orderingpb.ReadyOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orderingpb.OrderingService.ReadyOrder is not implemented"))
}

func (UnimplementedOrderingServiceHandler) CompleteOrder(context.Context, *connect.Request[orderingpb.CompleteOrderRequest]) (*connect.Response[orderingpb.CompleteOrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("orderingpb.OrderingService.CompleteOrder is not implemented"))
}
