// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: paymentspb/api.proto

package paymentspbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	paymentspb "github.com/owezzy/soko-bora-mngt-system/payments/paymentspb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PaymentsServiceName is the fully-qualified name of the PaymentsService service.
	PaymentsServiceName = "paymentspb.PaymentsService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PaymentsServiceAuthorizePaymentProcedure is the fully-qualified name of the PaymentsService's
	// AuthorizePayment RPC.
	PaymentsServiceAuthorizePaymentProcedure = "/paymentspb.PaymentsService/AuthorizePayment"
	// PaymentsServiceConfirmPaymentProcedure is the fully-qualified name of the PaymentsService's
	// ConfirmPayment RPC.
	PaymentsServiceConfirmPaymentProcedure = "/paymentspb.PaymentsService/ConfirmPayment"
	// PaymentsServiceCreateInvoiceProcedure is the fully-qualified name of the PaymentsService's
	// CreateInvoice RPC.
	PaymentsServiceCreateInvoiceProcedure = "/paymentspb.PaymentsService/CreateInvoice"
	// PaymentsServiceAdjustInvoiceProcedure is the fully-qualified name of the PaymentsService's
	// AdjustInvoice RPC.
	PaymentsServiceAdjustInvoiceProcedure = "/paymentspb.PaymentsService/AdjustInvoice"
	// PaymentsServicePayInvoiceProcedure is the fully-qualified name of the PaymentsService's
	// PayInvoice RPC.
	PaymentsServicePayInvoiceProcedure = "/paymentspb.PaymentsService/PayInvoice"
	// PaymentsServiceCancelInvoiceProcedure is the fully-qualified name of the PaymentsService's
	// CancelInvoice RPC.
	PaymentsServiceCancelInvoiceProcedure = "/paymentspb.PaymentsService/CancelInvoice"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	paymentsServiceServiceDescriptor                = paymentspb.File_paymentspb_api_proto.Services().ByName("PaymentsService")
	paymentsServiceAuthorizePaymentMethodDescriptor = paymentsServiceServiceDescriptor.Methods().ByName("AuthorizePayment")
	paymentsServiceConfirmPaymentMethodDescriptor   = paymentsServiceServiceDescriptor.Methods().ByName("ConfirmPayment")
	paymentsServiceCreateInvoiceMethodDescriptor    = paymentsServiceServiceDescriptor.Methods().ByName("CreateInvoice")
	paymentsServiceAdjustInvoiceMethodDescriptor    = paymentsServiceServiceDescriptor.Methods().ByName("AdjustInvoice")
	paymentsServicePayInvoiceMethodDescriptor       = paymentsServiceServiceDescriptor.Methods().ByName("PayInvoice")
	paymentsServiceCancelInvoiceMethodDescriptor    = paymentsServiceServiceDescriptor.Methods().ByName("CancelInvoice")
)

// PaymentsServiceClient is a client for the paymentspb.PaymentsService service.
type PaymentsServiceClient interface {
	AuthorizePayment(context.Context, *connect.Request[paymentspb.AuthorizePaymentRequest]) (*connect.Response[paymentspb.AuthorizePaymentResponse], error)
	ConfirmPayment(context.Context, *connect.Request[paymentspb.ConfirmPaymentRequest]) (*connect.Response[paymentspb.ConfirmPaymentResponse], error)
	CreateInvoice(context.Context, *connect.Request[paymentspb.CreateInvoiceRequest]) (*connect.Response[paymentspb.CreateInvoiceResponse], error)
	AdjustInvoice(context.Context, *connect.Request[paymentspb.AdjustInvoiceRequest]) (*connect.Response[paymentspb.AdjustInvoiceResponse], error)
	PayInvoice(context.Context, *connect.Request[paymentspb.PayInvoiceRequest]) (*connect.Response[paymentspb.PayInvoiceResponse], error)
	CancelInvoice(context.Context, *connect.Request[paymentspb.CancelInvoiceRequest]) (*connect.Response[paymentspb.CancelInvoiceResponse], error)
}

// NewPaymentsServiceClient constructs a client for the paymentspb.PaymentsService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPaymentsServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PaymentsServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &paymentsServiceClient{
		authorizePayment: connect.NewClient[paymentspb.AuthorizePaymentRequest, paymentspb.AuthorizePaymentResponse](
			httpClient,
			baseURL+PaymentsServiceAuthorizePaymentProcedure,
			connect.WithSchema(paymentsServiceAuthorizePaymentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		confirmPayment: connect.NewClient[paymentspb.ConfirmPaymentRequest, paymentspb.ConfirmPaymentResponse](
			httpClient,
			baseURL+PaymentsServiceConfirmPaymentProcedure,
			connect.WithSchema(paymentsServiceConfirmPaymentMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		createInvoice: connect.NewClient[paymentspb.CreateInvoiceRequest, paymentspb.CreateInvoiceResponse](
			httpClient,
			baseURL+PaymentsServiceCreateInvoiceProcedure,
			connect.WithSchema(paymentsServiceCreateInvoiceMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		adjustInvoice: connect.NewClient[paymentspb.AdjustInvoiceRequest, paymentspb.AdjustInvoiceResponse](
			httpClient,
			baseURL+PaymentsServiceAdjustInvoiceProcedure,
			connect.WithSchema(paymentsServiceAdjustInvoiceMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		payInvoice: connect.NewClient[paymentspb.PayInvoiceRequest, paymentspb.PayInvoiceResponse](
			httpClient,
			baseURL+PaymentsServicePayInvoiceProcedure,
			connect.WithSchema(paymentsServicePayInvoiceMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		cancelInvoice: connect.NewClient[paymentspb.CancelInvoiceRequest, paymentspb.CancelInvoiceResponse](
			httpClient,
			baseURL+PaymentsServiceCancelInvoiceProcedure,
			connect.WithSchema(paymentsServiceCancelInvoiceMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// paymentsServiceClient implements PaymentsServiceClient.
type paymentsServiceClient struct {
	authorizePayment *connect.Client[paymentspb.AuthorizePaymentRequest, paymentspb.AuthorizePaymentResponse]
	confirmPayment   *connect.Client[paymentspb.ConfirmPaymentRequest, paymentspb.ConfirmPaymentResponse]
	createInvoice    *connect.Client[paymentspb.CreateInvoiceRequest, paymentspb.CreateInvoiceResponse]
	adjustInvoice    *connect.Client[paymentspb.AdjustInvoiceRequest, paymentspb.AdjustInvoiceResponse]
	payInvoice       *connect.Client[paymentspb.PayInvoiceRequest, paymentspb.PayInvoiceResponse]
	cancelInvoice    *connect.Client[paymentspb.CancelInvoiceRequest, paymentspb.CancelInvoiceResponse]
}

// AuthorizePayment calls paymentspb.PaymentsService.AuthorizePayment.
func (c *paymentsServiceClient) AuthorizePayment(ctx context.Context, req *connect.Request[paymentspb.AuthorizePaymentRequest]) (*connect.Response[paymentspb.AuthorizePaymentResponse], error) {
	return c.authorizePayment.CallUnary(ctx, req)
}

// ConfirmPayment calls paymentspb.PaymentsService.ConfirmPayment.
func (c *paymentsServiceClient) ConfirmPayment(ctx context.Context, req *connect.Request[paymentspb.ConfirmPaymentRequest]) (*connect.Response[paymentspb.ConfirmPaymentResponse], error) {
	return c.confirmPayment.CallUnary(ctx, req)
}

// CreateInvoice calls paymentspb.PaymentsService.CreateInvoice.
func (c *paymentsServiceClient) CreateInvoice(ctx context.Context, req *connect.Request[paymentspb.CreateInvoiceRequest]) (*connect.Response[paymentspb.CreateInvoiceResponse], error) {
	return c.createInvoice.CallUnary(ctx, req)
}

// AdjustInvoice calls paymentspb.PaymentsService.AdjustInvoice.
func (c *paymentsServiceClient) AdjustInvoice(ctx context.Context, req *connect.Request[paymentspb.AdjustInvoiceRequest]) (*connect.Response[paymentspb.AdjustInvoiceResponse], error) {
	return c.adjustInvoice.CallUnary(ctx, req)
}

// PayInvoice calls paymentspb.PaymentsService.PayInvoice.
func (c *paymentsServiceClient) PayInvoice(ctx context.Context, req *connect.Request[paymentspb.PayInvoiceRequest]) (*connect.Response[paymentspb.PayInvoiceResponse], error) {
	return c.payInvoice.CallUnary(ctx, req)
}

// CancelInvoice calls paymentspb.PaymentsService.CancelInvoice.
func (c *paymentsServiceClient) CancelInvoice(ctx context.Context, req *connect.Request[paymentspb.CancelInvoiceRequest]) (*connect.Response[paymentspb.CancelInvoiceResponse], error) {
	return c.cancelInvoice.CallUnary(ctx, req)
}

// PaymentsServiceHandler is an implementation of the paymentspb.PaymentsService service.
type PaymentsServiceHandler interface {
	AuthorizePayment(context.Context, *connect.Request[paymentspb.AuthorizePaymentRequest]) (*connect.Response[paymentspb.AuthorizePaymentResponse], error)
	ConfirmPayment(context.Context, *connect.Request[paymentspb.ConfirmPaymentRequest]) (*connect.Response[paymentspb.ConfirmPaymentResponse], error)
	CreateInvoice(context.Context, *connect.Request[paymentspb.CreateInvoiceRequest]) (*connect.Response[paymentspb.CreateInvoiceResponse], error)
	AdjustInvoice(context.Context, *connect.Request[paymentspb.AdjustInvoiceRequest]) (*connect.Response[paymentspb.AdjustInvoiceResponse], error)
	PayInvoice(context.Context, *connect.Request[paymentspb.PayInvoiceRequest]) (*connect.Response[paymentspb.PayInvoiceResponse], error)
	CancelInvoice(context.Context, *connect.Request[paymentspb.CancelInvoiceRequest]) (*connect.Response[paymentspb.CancelInvoiceResponse], error)
}

// NewPaymentsServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPaymentsServiceHandler(svc PaymentsServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	paymentsServiceAuthorizePaymentHandler := connect.NewUnaryHandler(
		PaymentsServiceAuthorizePaymentProcedure,
		svc.AuthorizePayment,
		connect.WithSchema(paymentsServiceAuthorizePaymentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	paymentsServiceConfirmPaymentHandler := connect.NewUnaryHandler(
		PaymentsServiceConfirmPaymentProcedure,
		svc.ConfirmPayment,
		connect.WithSchema(paymentsServiceConfirmPaymentMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	paymentsServiceCreateInvoiceHandler := connect.NewUnaryHandler(
		PaymentsServiceCreateInvoiceProcedure,
		svc.CreateInvoice,
		connect.WithSchema(paymentsServiceCreateInvoiceMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	paymentsServiceAdjustInvoiceHandler := connect.NewUnaryHandler(
		PaymentsServiceAdjustInvoiceProcedure,
		svc.AdjustInvoice,
		connect.WithSchema(paymentsServiceAdjustInvoiceMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	paymentsServicePayInvoiceHandler := connect.NewUnaryHandler(
		PaymentsServicePayInvoiceProcedure,
		svc.PayInvoice,
		connect.WithSchema(paymentsServicePayInvoiceMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	paymentsServiceCancelInvoiceHandler := connect.NewUnaryHandler(
		PaymentsServiceCancelInvoiceProcedure,
		svc.CancelInvoice,
		connect.WithSchema(paymentsServiceCancelInvoiceMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/paymentspb.PaymentsService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PaymentsServiceAuthorizePaymentProcedure:
			paymentsServiceAuthorizePaymentHandler.ServeHTTP(w, r)
		case PaymentsServiceConfirmPaymentProcedure:
			paymentsServiceConfirmPaymentHandler.ServeHTTP(w, r)
		case PaymentsServiceCreateInvoiceProcedure:
			paymentsServiceCreateInvoiceHandler.ServeHTTP(w, r)
		case PaymentsServiceAdjustInvoiceProcedure:
			paymentsServiceAdjustInvoiceHandler.ServeHTTP(w, r)
		case PaymentsServicePayInvoiceProcedure:
			paymentsServicePayInvoiceHandler.ServeHTTP(w, r)
		case PaymentsServiceCancelInvoiceProcedure:
			paymentsServiceCancelInvoiceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPaymentsServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPaymentsServiceHandler struct{}

func (UnimplementedPaymentsServiceHandler) AuthorizePayment(context.Context, *connect.Request[paymentspb.AuthorizePaymentRequest]) (*connect.Response[paymentspb.AuthorizePaymentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paymentspb.PaymentsService.AuthorizePayment is not implemented"))
}

func (UnimplementedPaymentsServiceHandler) ConfirmPayment(context.Context, *connect.Request[paymentspb.ConfirmPaymentRequest]) (*connect.Response[paymentspb.ConfirmPaymentResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paymentspb.PaymentsService.ConfirmPayment is not implemented"))
}

func (UnimplementedPaymentsServiceHandler) CreateInvoice(context.Context, *connect.Request[paymentspb.CreateInvoiceRequest]) (*connect.Response[paymentspb.CreateInvoiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paymentspb.PaymentsService.CreateInvoice is not implemented"))
}

func (UnimplementedPaymentsServiceHandler) AdjustInvoice(context.Context, *connect.Request[paymentspb.AdjustInvoiceRequest]) (*connect.Response[paymentspb.AdjustInvoiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paymentspb.PaymentsService.AdjustInvoice is not implemented"))
}

func (UnimplementedPaymentsServiceHandler) PayInvoice(context.Context, *connect.Request[paymentspb.PayInvoiceRequest]) (*connect.Response[paymentspb.PayInvoiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paymentspb.PaymentsService.PayInvoice is not implemented"))
}

func (UnimplementedPaymentsServiceHandler) CancelInvoice(context.Context, *connect.Request[paymentspb.CancelInvoiceRequest]) (*connect.Response[paymentspb.CancelInvoiceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paymentspb.PaymentsService.CancelInvoice is not implemented"))
}
