// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=.ts"
// @generated from file paymentspb/api.proto (package paymentspb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file paymentspb/api.proto.
 */
export const file_paymentspb_api: GenFile = /*@__PURE__*/
  fileDesc("ChRwYXltZW50c3BiL2FwaS5wcm90bxIKcGF5bWVudHNwYiI+ChdBdXRob3JpemVQYXltZW50UmVxdWVzdBITCgtjdXN0b21lcl9pZBgBIAEoCRIOCgZhbW91bnQYAiABKAEiJgoYQXV0aG9yaXplUGF5bWVudFJlc3BvbnNlEgoKAmlkGAEgASgJIiMKFUNvbmZpcm1QYXltZW50UmVxdWVzdBIKCgJpZBgBIAEoCSIYChZDb25maXJtUGF5bWVudFJlc3BvbnNlIkwKFENyZWF0ZUludm9pY2VSZXF1ZXN0EhAKCG9yZGVyX2lkGAEgASgJEhIKCnBheW1lbnRfaWQYAiABKAkSDgoGYW1vdW50GAMgASgBIiMKFUNyZWF0ZUludm9pY2VSZXNwb25zZRIKCgJpZBgBIAEoCSIyChRBZGp1c3RJbnZvaWNlUmVxdWVzdBIKCgJpZBgBIAEoCRIOCgZhbW91bnQYAiABKAEiFwoVQWRqdXN0SW52b2ljZVJlc3BvbnNlIh8KEVBheUludm9pY2VSZXF1ZXN0EgoKAmlkGAEgASgJIhQKElBheUludm9pY2VSZXNwb25zZSIiChRDYW5jZWxJbnZvaWNlUmVxdWVzdBIKCgJpZBgBIAEoCSIXChVDYW5jZWxJbnZvaWNlUmVzcG9uc2UypAQKD1BheW1lbnRzU2VydmljZRJfChBBdXRob3JpemVQYXltZW50EiMucGF5bWVudHNwYi5BdXRob3JpemVQYXltZW50UmVxdWVzdBokLnBheW1lbnRzcGIuQXV0aG9yaXplUGF5bWVudFJlc3BvbnNlIgASWQoOQ29uZmlybVBheW1lbnQSIS5wYXltZW50c3BiLkNvbmZpcm1QYXltZW50UmVxdWVzdBoiLnBheW1lbnRzcGIuQ29uZmlybVBheW1lbnRSZXNwb25zZSIAElYKDUNyZWF0ZUludm9pY2USIC5wYXltZW50c3BiLkNyZWF0ZUludm9pY2VSZXF1ZXN0GiEucGF5bWVudHNwYi5DcmVhdGVJbnZvaWNlUmVzcG9uc2UiABJWCg1BZGp1c3RJbnZvaWNlEiAucGF5bWVudHNwYi5BZGp1c3RJbnZvaWNlUmVxdWVzdBohLnBheW1lbnRzcGIuQWRqdXN0SW52b2ljZVJlc3BvbnNlIgASTQoKUGF5SW52b2ljZRIdLnBheW1lbnRzcGIuUGF5SW52b2ljZVJlcXVlc3QaHi5wYXltZW50c3BiLlBheUludm9pY2VSZXNwb25zZSIAElYKDUNhbmNlbEludm9pY2USIC5wYXltZW50c3BiLkNhbmNlbEludm9pY2VSZXF1ZXN0GiEucGF5bWVudHNwYi5DYW5jZWxJbnZvaWNlUmVzcG9uc2UiAEKfAQoOY29tLnBheW1lbnRzcGJCCEFwaVByb3RvUAFaO2dpdGh1Yi5jb20vb3dlenp5L3Nva28tYm9yYS1tbmd0LXN5c3RlbS9wYXltZW50cy9wYXltZW50c3BiogIDUFhYqgIKUGF5bWVudHNwYsoCClBheW1lbnRzcGLiAhZQYXltZW50c3BiXEdQQk1ldGFkYXRh6gIKUGF5bWVudHNwYmIGcHJvdG8z");

/**
 * @generated from message paymentspb.AuthorizePaymentRequest
 */
export type AuthorizePaymentRequest = Message<"paymentspb.AuthorizePaymentRequest"> & {
  /**
   * @generated from field: string customer_id = 1;
   */
  customerId: string;

  /**
   * @generated from field: double amount = 2;
   */
  amount: number;
};

/**
 * Describes the message paymentspb.AuthorizePaymentRequest.
 * Use `create(AuthorizePaymentRequestSchema)` to create a new message.
 */
export const AuthorizePaymentRequestSchema: GenMessage<AuthorizePaymentRequest> = /*@__PURE__*/
  messageDesc(file_paymentspb_api, 0);

/**
 * @generated from message paymentspb.AuthorizePaymentResponse
 */
export type AuthorizePaymentResponse = Message<"paymentspb.AuthorizePaymentResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message paymentspb.AuthorizePaymentResponse.
 * Use `create(AuthorizePaymentResponseSchema)` to create a new message.
 */
export const AuthorizePaymentResponseSchema: GenMessage<AuthorizePaymentResponse> = /*@__PURE__*/
  messageDesc(file_paymentspb_api, 1);

/**
 * @generated from message paymentspb.ConfirmPaymentRequest
 */
export type ConfirmPaymentRequest = Message<"paymentspb.ConfirmPaymentRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message paymentspb.ConfirmPaymentRequest.
 * Use `create(ConfirmPaymentRequestSchema)` to create a new message.
 */
export const ConfirmPaymentRequestSchema: GenMessage<ConfirmPaymentRequest> = /*@__PURE__*/
  messageDesc(file_paymentspb_api, 2);

/**
 * @generated from message paymentspb.ConfirmPaymentResponse
 */
export type ConfirmPaymentResponse = Message<"paymentspb.ConfirmPaymentResponse"> & {
};

/**
 * Describes the message paymentspb.ConfirmPaymentResponse.
 * Use `create(ConfirmPaymentResponseSchema)` to create a new message.
 */
export const ConfirmPaymentResponseSchema: GenMessage<ConfirmPaymentResponse> = /*@__PURE__*/
  messageDesc(file_paymentspb_api, 3);

/**
 * @generated from message paymentspb.CreateInvoiceRequest
 */
export type CreateInvoiceRequest = Message<"paymentspb.CreateInvoiceRequest"> & {
  /**
   * @generated from field: string order_id = 1;
   */
  orderId: string;

  /**
   * @generated from field: string payment_id = 2;
   */
  paymentId: string;

  /**
   * @generated from field: double amount = 3;
   */
  amount: number;
};

/**
 * Describes the message paymentspb.CreateInvoiceRequest.
 * Use `create(CreateInvoiceRequestSchema)` to create a new message.
 */
export const CreateInvoiceRequestSchema: GenMessage<CreateInvoiceRequest> = /*@__PURE__*/
  messageDesc(file_paymentspb_api, 4);

/**
 * @generated from message paymentspb.CreateInvoiceResponse
 */
export type CreateInvoiceResponse = Message<"paymentspb.CreateInvoiceResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message paymentspb.CreateInvoiceResponse.
 * Use `create(CreateInvoiceResponseSchema)` to create a new message.
 */
export const CreateInvoiceResponseSchema: GenMessage<CreateInvoiceResponse> = /*@__PURE__*/
  messageDesc(file_paymentspb_api, 5);

/**
 * @generated from message paymentspb.AdjustInvoiceRequest
 */
export type AdjustInvoiceRequest = Message<"paymentspb.AdjustInvoiceRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: double amount = 2;
   */
  amount: number;
};

/**
 * Describes the message paymentspb.AdjustInvoiceRequest.
 * Use `create(AdjustInvoiceRequestSchema)` to create a new message.
 */
export const AdjustInvoiceRequestSchema: GenMessage<AdjustInvoiceRequest> = /*@__PURE__*/
  messageDesc(file_paymentspb_api, 6);

/**
 * @generated from message paymentspb.AdjustInvoiceResponse
 */
export type AdjustInvoiceResponse = Message<"paymentspb.AdjustInvoiceResponse"> & {
};

/**
 * Describes the message paymentspb.AdjustInvoiceResponse.
 * Use `create(AdjustInvoiceResponseSchema)` to create a new message.
 */
export const AdjustInvoiceResponseSchema: GenMessage<AdjustInvoiceResponse> = /*@__PURE__*/
  messageDesc(file_paymentspb_api, 7);

/**
 * @generated from message paymentspb.PayInvoiceRequest
 */
export type PayInvoiceRequest = Message<"paymentspb.PayInvoiceRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message paymentspb.PayInvoiceRequest.
 * Use `create(PayInvoiceRequestSchema)` to create a new message.
 */
export const PayInvoiceRequestSchema: GenMessage<PayInvoiceRequest> = /*@__PURE__*/
  messageDesc(file_paymentspb_api, 8);

/**
 * @generated from message paymentspb.PayInvoiceResponse
 */
export type PayInvoiceResponse = Message<"paymentspb.PayInvoiceResponse"> & {
};

/**
 * Describes the message paymentspb.PayInvoiceResponse.
 * Use `create(PayInvoiceResponseSchema)` to create a new message.
 */
export const PayInvoiceResponseSchema: GenMessage<PayInvoiceResponse> = /*@__PURE__*/
  messageDesc(file_paymentspb_api, 9);

/**
 * @generated from message paymentspb.CancelInvoiceRequest
 */
export type CancelInvoiceRequest = Message<"paymentspb.CancelInvoiceRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message paymentspb.CancelInvoiceRequest.
 * Use `create(CancelInvoiceRequestSchema)` to create a new message.
 */
export const CancelInvoiceRequestSchema: GenMessage<CancelInvoiceRequest> = /*@__PURE__*/
  messageDesc(file_paymentspb_api, 10);

/**
 * @generated from message paymentspb.CancelInvoiceResponse
 */
export type CancelInvoiceResponse = Message<"paymentspb.CancelInvoiceResponse"> & {
};

/**
 * Describes the message paymentspb.CancelInvoiceResponse.
 * Use `create(CancelInvoiceResponseSchema)` to create a new message.
 */
export const CancelInvoiceResponseSchema: GenMessage<CancelInvoiceResponse> = /*@__PURE__*/
  messageDesc(file_paymentspb_api, 11);

/**
 * @generated from service paymentspb.PaymentsService
 */
export const PaymentsService: GenService<{
  /**
   * @generated from rpc paymentspb.PaymentsService.AuthorizePayment
   */
  authorizePayment: {
    methodKind: "unary";
    input: typeof AuthorizePaymentRequestSchema;
    output: typeof AuthorizePaymentResponseSchema;
  },
  /**
   * @generated from rpc paymentspb.PaymentsService.ConfirmPayment
   */
  confirmPayment: {
    methodKind: "unary";
    input: typeof ConfirmPaymentRequestSchema;
    output: typeof ConfirmPaymentResponseSchema;
  },
  /**
   * @generated from rpc paymentspb.PaymentsService.CreateInvoice
   */
  createInvoice: {
    methodKind: "unary";
    input: typeof CreateInvoiceRequestSchema;
    output: typeof CreateInvoiceResponseSchema;
  },
  /**
   * @generated from rpc paymentspb.PaymentsService.AdjustInvoice
   */
  adjustInvoice: {
    methodKind: "unary";
    input: typeof AdjustInvoiceRequestSchema;
    output: typeof AdjustInvoiceResponseSchema;
  },
  /**
   * @generated from rpc paymentspb.PaymentsService.PayInvoice
   */
  payInvoice: {
    methodKind: "unary";
    input: typeof PayInvoiceRequestSchema;
    output: typeof PayInvoiceResponseSchema;
  },
  /**
   * @generated from rpc paymentspb.PaymentsService.CancelInvoice
   */
  cancelInvoice: {
    methodKind: "unary";
    input: typeof CancelInvoiceRequestSchema;
    output: typeof CancelInvoiceResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_paymentspb_api, 0);

