// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=.ts"
// @generated from file paymentspb/messages.proto (package paymentspb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file paymentspb/messages.proto.
 */
export const file_paymentspb_messages: GenFile = /*@__PURE__*/
  fileDesc("ChlwYXltZW50c3BiL21lc3NhZ2VzLnByb3RvEgpwYXltZW50c3BiIisKC0ludm9pY2VQYWlkEgoKAmlkGAEgASgJEhAKCG9yZGVyX2lkGAIgASgJIiwKDkNvbmZpcm1QYXltZW50EgoKAmlkGAEgASgJEg4KBmFtb3VudBgCIAEoAUKkAQoOY29tLnBheW1lbnRzcGJCDU1lc3NhZ2VzUHJvdG9QAVo7Z2l0aHViLmNvbS9vd2V6enkvc29rby1ib3JhLW1uZ3Qtc3lzdGVtL3BheW1lbnRzL3BheW1lbnRzcGKiAgNQWFiqAgpQYXltZW50c3BiygIKUGF5bWVudHNwYuICFlBheW1lbnRzcGJcR1BCTWV0YWRhdGHqAgpQYXltZW50c3BiYgZwcm90bzM");

/**
 * @generated from message paymentspb.InvoicePaid
 */
export type InvoicePaid = Message<"paymentspb.InvoicePaid"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string order_id = 2;
   */
  orderId: string;
};

/**
 * Describes the message paymentspb.InvoicePaid.
 * Use `create(InvoicePaidSchema)` to create a new message.
 */
export const InvoicePaidSchema: GenMessage<InvoicePaid> = /*@__PURE__*/
  messageDesc(file_paymentspb_messages, 0);

/**
 * @generated from message paymentspb.ConfirmPayment
 */
export type ConfirmPayment = Message<"paymentspb.ConfirmPayment"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: double amount = 2;
   */
  amount: number;
};

/**
 * Describes the message paymentspb.ConfirmPayment.
 * Use `create(ConfirmPaymentSchema)` to create a new message.
 */
export const ConfirmPaymentSchema: GenMessage<ConfirmPayment> = /*@__PURE__*/
  messageDesc(file_paymentspb_messages, 1);

