// Code generated by mockery. DO NOT EDIT.

package am

import (
	context "context"

	ddd "github.com/owezzy/soko-bora-mngt-system/internal/ddd"
	mock "github.com/stretchr/testify/mock"
)

// MockReplyPublisher is an autogenerated mock type for the ReplyPublisher type
type MockReplyPublisher struct {
	mock.Mock
}

type MockReplyPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReplyPublisher) EXPECT() *MockReplyPublisher_Expecter {
	return &MockReplyPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, topicName, reply
func (_m *MockReplyPublisher) Publish(ctx context.Context, topicName string, reply ddd.Reply) error {
	ret := _m.Called(ctx, topicName, reply)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ddd.Reply) error); ok {
		r0 = rf(ctx, topicName, reply)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReplyPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockReplyPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topicName string
//   - reply ddd.Reply
func (_e *MockReplyPublisher_Expecter) Publish(ctx interface{}, topicName interface{}, reply interface{}) *MockReplyPublisher_Publish_Call {
	return &MockReplyPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, topicName, reply)}
}

func (_c *MockReplyPublisher_Publish_Call) Run(run func(ctx context.Context, topicName string, reply ddd.Reply)) *MockReplyPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(ddd.Reply))
	})
	return _c
}

func (_c *MockReplyPublisher_Publish_Call) Return(_a0 error) *MockReplyPublisher_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReplyPublisher_Publish_Call) RunAndReturn(run func(context.Context, string, ddd.Reply) error) *MockReplyPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReplyPublisher creates a new instance of MockReplyPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReplyPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReplyPublisher {
	mock := &MockReplyPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
