// Code generated by mockery. DO NOT EDIT.

package am

import mock "github.com/stretchr/testify/mock"

// MockMessageSubscriber is an autogenerated mock type for the MessageSubscriber type
type MockMessageSubscriber struct {
	mock.Mock
}

type MockMessageSubscriber_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageSubscriber) EXPECT() *MockMessageSubscriber_Expecter {
	return &MockMessageSubscriber_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function with given fields: topicName, handler, options
func (_m *MockMessageSubscriber) Subscribe(topicName string, handler MessageHandler, options ...SubscriberOption) (Subscription, error) {
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, topicName, handler)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 Subscription
	var r1 error
	if rf, ok := ret.Get(0).(func(string, MessageHandler, ...SubscriberOption) (Subscription, error)); ok {
		return rf(topicName, handler, options...)
	}
	if rf, ok := ret.Get(0).(func(string, MessageHandler, ...SubscriberOption) Subscription); ok {
		r0 = rf(topicName, handler, options...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Subscription)
		}
	}

	if rf, ok := ret.Get(1).(func(string, MessageHandler, ...SubscriberOption) error); ok {
		r1 = rf(topicName, handler, options...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockMessageSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockMessageSubscriber_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - topicName string
//   - handler MessageHandler
//   - options ...SubscriberOption
func (_e *MockMessageSubscriber_Expecter) Subscribe(topicName interface{}, handler interface{}, options ...interface{}) *MockMessageSubscriber_Subscribe_Call {
	return &MockMessageSubscriber_Subscribe_Call{Call: _e.mock.On("Subscribe",
		append([]interface{}{topicName, handler}, options...)...)}
}

func (_c *MockMessageSubscriber_Subscribe_Call) Run(run func(topicName string, handler MessageHandler, options ...SubscriberOption)) *MockMessageSubscriber_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]SubscriberOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(SubscriberOption)
			}
		}
		run(args[0].(string), args[1].(MessageHandler), variadicArgs...)
	})
	return _c
}

func (_c *MockMessageSubscriber_Subscribe_Call) Return(_a0 Subscription, _a1 error) *MockMessageSubscriber_Subscribe_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockMessageSubscriber_Subscribe_Call) RunAndReturn(run func(string, MessageHandler, ...SubscriberOption) (Subscription, error)) *MockMessageSubscriber_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// Unsubscribe provides a mock function with no fields
func (_m *MockMessageSubscriber) Unsubscribe() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Unsubscribe")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageSubscriber_Unsubscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unsubscribe'
type MockMessageSubscriber_Unsubscribe_Call struct {
	*mock.Call
}

// Unsubscribe is a helper method to define mock.On call
func (_e *MockMessageSubscriber_Expecter) Unsubscribe() *MockMessageSubscriber_Unsubscribe_Call {
	return &MockMessageSubscriber_Unsubscribe_Call{Call: _e.mock.On("Unsubscribe")}
}

func (_c *MockMessageSubscriber_Unsubscribe_Call) Run(run func()) *MockMessageSubscriber_Unsubscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMessageSubscriber_Unsubscribe_Call) Return(_a0 error) *MockMessageSubscriber_Unsubscribe_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageSubscriber_Unsubscribe_Call) RunAndReturn(run func() error) *MockMessageSubscriber_Unsubscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageSubscriber creates a new instance of MockMessageSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageSubscriber(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageSubscriber {
	mock := &MockMessageSubscriber{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
