// Code generated by mockery. DO NOT EDIT.

package am

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockMessageHandler is an autogenerated mock type for the MessageHandler type
type MockMessageHandler struct {
	mock.Mock
}

type MockMessageHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMessageHandler) EXPECT() *MockMessageHandler_Expecter {
	return &MockMessageHandler_Expecter{mock: &_m.Mock}
}

// HandleMessage provides a mock function with given fields: ctx, msg
func (_m *MockMessageHandler) HandleMessage(ctx context.Context, msg IncomingMessage) error {
	ret := _m.Called(ctx, msg)

	if len(ret) == 0 {
		panic("no return value specified for HandleMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, IncomingMessage) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockMessageHandler_HandleMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleMessage'
type MockMessageHandler_HandleMessage_Call struct {
	*mock.Call
}

// HandleMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - msg IncomingMessage
func (_e *MockMessageHandler_Expecter) HandleMessage(ctx interface{}, msg interface{}) *MockMessageHandler_HandleMessage_Call {
	return &MockMessageHandler_HandleMessage_Call{Call: _e.mock.On("HandleMessage", ctx, msg)}
}

func (_c *MockMessageHandler_HandleMessage_Call) Run(run func(ctx context.Context, msg IncomingMessage)) *MockMessageHandler_HandleMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(IncomingMessage))
	})
	return _c
}

func (_c *MockMessageHandler_HandleMessage_Call) Return(_a0 error) *MockMessageHandler_HandleMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockMessageHandler_HandleMessage_Call) RunAndReturn(run func(context.Context, IncomingMessage) error) *MockMessageHandler_HandleMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockMessageHandler creates a new instance of MockMessageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMessageHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMessageHandler {
	mock := &MockMessageHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
