// Code generated by mockery. DO NOT EDIT.

package am

import (
	context "context"

	ddd "github.com/owezzy/soko-bora-mngt-system/internal/ddd"
	mock "github.com/stretchr/testify/mock"
)

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, topicName, event
func (_m *MockEventPublisher) Publish(ctx context.Context, topicName string, event ddd.Event) error {
	ret := _m.Called(ctx, topicName, event)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, ddd.Event) error); ok {
		r0 = rf(ctx, topicName, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topicName string
//   - event ddd.Event
func (_e *MockEventPublisher_Expecter) Publish(ctx interface{}, topicName interface{}, event interface{}) *MockEventPublisher_Publish_Call {
	return &MockEventPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, topicName, event)}
}

func (_c *MockEventPublisher_Publish_Call) Run(run func(ctx context.Context, topicName string, event ddd.Event)) *MockEventPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(ddd.Event))
	})
	return _c
}

func (_c *MockEventPublisher_Publish_Call) Return(_a0 error) *MockEventPublisher_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_Publish_Call) RunAndReturn(run func(context.Context, string, ddd.Event) error) *MockEventPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
