// Code generated by mockery. DO NOT EDIT.

package paymentspb

import mock "github.com/stretchr/testify/mock"

// MockUnsafePaymentsServiceServer is an autogenerated mock type for the UnsafePaymentsServiceServer type
type MockUnsafePaymentsServiceServer struct {
	mock.Mock
}

type MockUnsafePaymentsServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafePaymentsServiceServer) EXPECT() *MockUnsafePaymentsServiceServer_Expecter {
	return &MockUnsafePaymentsServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedPaymentsServiceServer provides a mock function with no fields
func (_m *MockUnsafePaymentsServiceServer) mustEmbedUnimplementedPaymentsServiceServer() {
	_m.Called()
}

// MockUnsafePaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedPaymentsServiceServer'
type MockUnsafePaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedPaymentsServiceServer is a helper method to define mock.On call
func (_e *MockUnsafePaymentsServiceServer_Expecter) mustEmbedUnimplementedPaymentsServiceServer() *MockUnsafePaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call {
	return &MockUnsafePaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedPaymentsServiceServer")}
}

func (_c *MockUnsafePaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call) Run(run func()) *MockUnsafePaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafePaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call) Return() *MockUnsafePaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafePaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call) RunAndReturn(run func()) *MockUnsafePaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockUnsafePaymentsServiceServer creates a new instance of MockUnsafePaymentsServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafePaymentsServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafePaymentsServiceServer {
	mock := &MockUnsafePaymentsServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
