// Code generated by mockery. DO NOT EDIT.

package paymentspb

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentsServiceServer is an autogenerated mock type for the PaymentsServiceServer type
type MockPaymentsServiceServer struct {
	mock.Mock
}

type MockPaymentsServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentsServiceServer) EXPECT() *MockPaymentsServiceServer_Expecter {
	return &MockPaymentsServiceServer_Expecter{mock: &_m.Mock}
}

// AdjustInvoice provides a mock function with given fields: _a0, _a1
func (_m *MockPaymentsServiceServer) AdjustInvoice(_a0 context.Context, _a1 *AdjustInvoiceRequest) (*AdjustInvoiceResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AdjustInvoice")
	}

	var r0 *AdjustInvoiceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *AdjustInvoiceRequest) (*AdjustInvoiceResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *AdjustInvoiceRequest) *AdjustInvoiceResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AdjustInvoiceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *AdjustInvoiceRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentsServiceServer_AdjustInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AdjustInvoice'
type MockPaymentsServiceServer_AdjustInvoice_Call struct {
	*mock.Call
}

// AdjustInvoice is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *AdjustInvoiceRequest
func (_e *MockPaymentsServiceServer_Expecter) AdjustInvoice(_a0 interface{}, _a1 interface{}) *MockPaymentsServiceServer_AdjustInvoice_Call {
	return &MockPaymentsServiceServer_AdjustInvoice_Call{Call: _e.mock.On("AdjustInvoice", _a0, _a1)}
}

func (_c *MockPaymentsServiceServer_AdjustInvoice_Call) Run(run func(_a0 context.Context, _a1 *AdjustInvoiceRequest)) *MockPaymentsServiceServer_AdjustInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*AdjustInvoiceRequest))
	})
	return _c
}

func (_c *MockPaymentsServiceServer_AdjustInvoice_Call) Return(_a0 *AdjustInvoiceResponse, _a1 error) *MockPaymentsServiceServer_AdjustInvoice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentsServiceServer_AdjustInvoice_Call) RunAndReturn(run func(context.Context, *AdjustInvoiceRequest) (*AdjustInvoiceResponse, error)) *MockPaymentsServiceServer_AdjustInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// AuthorizePayment provides a mock function with given fields: _a0, _a1
func (_m *MockPaymentsServiceServer) AuthorizePayment(_a0 context.Context, _a1 *AuthorizePaymentRequest) (*AuthorizePaymentResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for AuthorizePayment")
	}

	var r0 *AuthorizePaymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *AuthorizePaymentRequest) (*AuthorizePaymentResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *AuthorizePaymentRequest) *AuthorizePaymentResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthorizePaymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *AuthorizePaymentRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentsServiceServer_AuthorizePayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizePayment'
type MockPaymentsServiceServer_AuthorizePayment_Call struct {
	*mock.Call
}

// AuthorizePayment is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *AuthorizePaymentRequest
func (_e *MockPaymentsServiceServer_Expecter) AuthorizePayment(_a0 interface{}, _a1 interface{}) *MockPaymentsServiceServer_AuthorizePayment_Call {
	return &MockPaymentsServiceServer_AuthorizePayment_Call{Call: _e.mock.On("AuthorizePayment", _a0, _a1)}
}

func (_c *MockPaymentsServiceServer_AuthorizePayment_Call) Run(run func(_a0 context.Context, _a1 *AuthorizePaymentRequest)) *MockPaymentsServiceServer_AuthorizePayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*AuthorizePaymentRequest))
	})
	return _c
}

func (_c *MockPaymentsServiceServer_AuthorizePayment_Call) Return(_a0 *AuthorizePaymentResponse, _a1 error) *MockPaymentsServiceServer_AuthorizePayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentsServiceServer_AuthorizePayment_Call) RunAndReturn(run func(context.Context, *AuthorizePaymentRequest) (*AuthorizePaymentResponse, error)) *MockPaymentsServiceServer_AuthorizePayment_Call {
	_c.Call.Return(run)
	return _c
}

// CancelInvoice provides a mock function with given fields: _a0, _a1
func (_m *MockPaymentsServiceServer) CancelInvoice(_a0 context.Context, _a1 *CancelInvoiceRequest) (*CancelInvoiceResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CancelInvoice")
	}

	var r0 *CancelInvoiceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *CancelInvoiceRequest) (*CancelInvoiceResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *CancelInvoiceRequest) *CancelInvoiceResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CancelInvoiceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *CancelInvoiceRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentsServiceServer_CancelInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelInvoice'
type MockPaymentsServiceServer_CancelInvoice_Call struct {
	*mock.Call
}

// CancelInvoice is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *CancelInvoiceRequest
func (_e *MockPaymentsServiceServer_Expecter) CancelInvoice(_a0 interface{}, _a1 interface{}) *MockPaymentsServiceServer_CancelInvoice_Call {
	return &MockPaymentsServiceServer_CancelInvoice_Call{Call: _e.mock.On("CancelInvoice", _a0, _a1)}
}

func (_c *MockPaymentsServiceServer_CancelInvoice_Call) Run(run func(_a0 context.Context, _a1 *CancelInvoiceRequest)) *MockPaymentsServiceServer_CancelInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*CancelInvoiceRequest))
	})
	return _c
}

func (_c *MockPaymentsServiceServer_CancelInvoice_Call) Return(_a0 *CancelInvoiceResponse, _a1 error) *MockPaymentsServiceServer_CancelInvoice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentsServiceServer_CancelInvoice_Call) RunAndReturn(run func(context.Context, *CancelInvoiceRequest) (*CancelInvoiceResponse, error)) *MockPaymentsServiceServer_CancelInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// ConfirmPayment provides a mock function with given fields: _a0, _a1
func (_m *MockPaymentsServiceServer) ConfirmPayment(_a0 context.Context, _a1 *ConfirmPaymentRequest) (*ConfirmPaymentResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ConfirmPayment")
	}

	var r0 *ConfirmPaymentResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ConfirmPaymentRequest) (*ConfirmPaymentResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ConfirmPaymentRequest) *ConfirmPaymentResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ConfirmPaymentResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ConfirmPaymentRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentsServiceServer_ConfirmPayment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConfirmPayment'
type MockPaymentsServiceServer_ConfirmPayment_Call struct {
	*mock.Call
}

// ConfirmPayment is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *ConfirmPaymentRequest
func (_e *MockPaymentsServiceServer_Expecter) ConfirmPayment(_a0 interface{}, _a1 interface{}) *MockPaymentsServiceServer_ConfirmPayment_Call {
	return &MockPaymentsServiceServer_ConfirmPayment_Call{Call: _e.mock.On("ConfirmPayment", _a0, _a1)}
}

func (_c *MockPaymentsServiceServer_ConfirmPayment_Call) Run(run func(_a0 context.Context, _a1 *ConfirmPaymentRequest)) *MockPaymentsServiceServer_ConfirmPayment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ConfirmPaymentRequest))
	})
	return _c
}

func (_c *MockPaymentsServiceServer_ConfirmPayment_Call) Return(_a0 *ConfirmPaymentResponse, _a1 error) *MockPaymentsServiceServer_ConfirmPayment_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentsServiceServer_ConfirmPayment_Call) RunAndReturn(run func(context.Context, *ConfirmPaymentRequest) (*ConfirmPaymentResponse, error)) *MockPaymentsServiceServer_ConfirmPayment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInvoice provides a mock function with given fields: _a0, _a1
func (_m *MockPaymentsServiceServer) CreateInvoice(_a0 context.Context, _a1 *CreateInvoiceRequest) (*CreateInvoiceResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvoice")
	}

	var r0 *CreateInvoiceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *CreateInvoiceRequest) (*CreateInvoiceResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *CreateInvoiceRequest) *CreateInvoiceResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CreateInvoiceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *CreateInvoiceRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentsServiceServer_CreateInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvoice'
type MockPaymentsServiceServer_CreateInvoice_Call struct {
	*mock.Call
}

// CreateInvoice is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *CreateInvoiceRequest
func (_e *MockPaymentsServiceServer_Expecter) CreateInvoice(_a0 interface{}, _a1 interface{}) *MockPaymentsServiceServer_CreateInvoice_Call {
	return &MockPaymentsServiceServer_CreateInvoice_Call{Call: _e.mock.On("CreateInvoice", _a0, _a1)}
}

func (_c *MockPaymentsServiceServer_CreateInvoice_Call) Run(run func(_a0 context.Context, _a1 *CreateInvoiceRequest)) *MockPaymentsServiceServer_CreateInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*CreateInvoiceRequest))
	})
	return _c
}

func (_c *MockPaymentsServiceServer_CreateInvoice_Call) Return(_a0 *CreateInvoiceResponse, _a1 error) *MockPaymentsServiceServer_CreateInvoice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentsServiceServer_CreateInvoice_Call) RunAndReturn(run func(context.Context, *CreateInvoiceRequest) (*CreateInvoiceResponse, error)) *MockPaymentsServiceServer_CreateInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// PayInvoice provides a mock function with given fields: _a0, _a1
func (_m *MockPaymentsServiceServer) PayInvoice(_a0 context.Context, _a1 *PayInvoiceRequest) (*PayInvoiceResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for PayInvoice")
	}

	var r0 *PayInvoiceResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *PayInvoiceRequest) (*PayInvoiceResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *PayInvoiceRequest) *PayInvoiceResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*PayInvoiceResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *PayInvoiceRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockPaymentsServiceServer_PayInvoice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PayInvoice'
type MockPaymentsServiceServer_PayInvoice_Call struct {
	*mock.Call
}

// PayInvoice is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *PayInvoiceRequest
func (_e *MockPaymentsServiceServer_Expecter) PayInvoice(_a0 interface{}, _a1 interface{}) *MockPaymentsServiceServer_PayInvoice_Call {
	return &MockPaymentsServiceServer_PayInvoice_Call{Call: _e.mock.On("PayInvoice", _a0, _a1)}
}

func (_c *MockPaymentsServiceServer_PayInvoice_Call) Run(run func(_a0 context.Context, _a1 *PayInvoiceRequest)) *MockPaymentsServiceServer_PayInvoice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*PayInvoiceRequest))
	})
	return _c
}

func (_c *MockPaymentsServiceServer_PayInvoice_Call) Return(_a0 *PayInvoiceResponse, _a1 error) *MockPaymentsServiceServer_PayInvoice_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockPaymentsServiceServer_PayInvoice_Call) RunAndReturn(run func(context.Context, *PayInvoiceRequest) (*PayInvoiceResponse, error)) *MockPaymentsServiceServer_PayInvoice_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedPaymentsServiceServer provides a mock function with no fields
func (_m *MockPaymentsServiceServer) mustEmbedUnimplementedPaymentsServiceServer() {
	_m.Called()
}

// MockPaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedPaymentsServiceServer'
type MockPaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedPaymentsServiceServer is a helper method to define mock.On call
func (_e *MockPaymentsServiceServer_Expecter) mustEmbedUnimplementedPaymentsServiceServer() *MockPaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call {
	return &MockPaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedPaymentsServiceServer")}
}

func (_c *MockPaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call) Run(run func()) *MockPaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call) Return() *MockPaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call) RunAndReturn(run func()) *MockPaymentsServiceServer_mustEmbedUnimplementedPaymentsServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockPaymentsServiceServer creates a new instance of MockPaymentsServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentsServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentsServiceServer {
	mock := &MockPaymentsServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
