// Code generated by mockery. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCustomerRepository is an autogenerated mock type for the CustomerRepository type
type MockCustomerRepository struct {
	mock.Mock
}

type MockCustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerRepository) EXPECT() *MockCustomerRepository_Expecter {
	return &MockCustomerRepository_Expecter{mock: &_m.Mock}
}

// Authorize provides a mock function with given fields: ctx, customerID
func (_m *MockCustomerRepository) Authorize(ctx context.Context, customerID string) error {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for Authorize")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, customerID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCustomerRepository_Authorize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Authorize'
type MockCustomerRepository_Authorize_Call struct {
	*mock.Call
}

// Authorize is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
func (_e *MockCustomerRepository_Expecter) Authorize(ctx interface{}, customerID interface{}) *MockCustomerRepository_Authorize_Call {
	return &MockCustomerRepository_Authorize_Call{Call: _e.mock.On("Authorize", ctx, customerID)}
}

func (_c *MockCustomerRepository_Authorize_Call) Run(run func(ctx context.Context, customerID string)) *MockCustomerRepository_Authorize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCustomerRepository_Authorize_Call) Return(_a0 error) *MockCustomerRepository_Authorize_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCustomerRepository_Authorize_Call) RunAndReturn(run func(context.Context, string) error) *MockCustomerRepository_Authorize_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCustomerRepository creates a new instance of MockCustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerRepository {
	mock := &MockCustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
