// Code generated by mockery. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockShoppingRepository is an autogenerated mock type for the ShoppingRepository type
type MockShoppingRepository struct {
	mock.Mock
}

type MockShoppingRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShoppingRepository) EXPECT() *MockShoppingRepository_Expecter {
	return &MockShoppingRepository_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function with given fields: ctx, shoppingID
func (_m *MockShoppingRepository) Cancel(ctx context.Context, shoppingID string) error {
	ret := _m.Called(ctx, shoppingID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, shoppingID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockShoppingRepository_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockShoppingRepository_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - ctx context.Context
//   - shoppingID string
func (_e *MockShoppingRepository_Expecter) Cancel(ctx interface{}, shoppingID interface{}) *MockShoppingRepository_Cancel_Call {
	return &MockShoppingRepository_Cancel_Call{Call: _e.mock.On("Cancel", ctx, shoppingID)}
}

func (_c *MockShoppingRepository_Cancel_Call) Run(run func(ctx context.Context, shoppingID string)) *MockShoppingRepository_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockShoppingRepository_Cancel_Call) Return(_a0 error) *MockShoppingRepository_Cancel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockShoppingRepository_Cancel_Call) RunAndReturn(run func(context.Context, string) error) *MockShoppingRepository_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function with given fields: ctx, orderID, items
func (_m *MockShoppingRepository) Create(ctx context.Context, orderID string, items []Item) (string, error) {
	ret := _m.Called(ctx, orderID, items)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []Item) (string, error)); ok {
		return rf(ctx, orderID, items)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, []Item) string); ok {
		r0 = rf(ctx, orderID, items)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, []Item) error); ok {
		r1 = rf(ctx, orderID, items)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockShoppingRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockShoppingRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - orderID string
//   - items []Item
func (_e *MockShoppingRepository_Expecter) Create(ctx interface{}, orderID interface{}, items interface{}) *MockShoppingRepository_Create_Call {
	return &MockShoppingRepository_Create_Call{Call: _e.mock.On("Create", ctx, orderID, items)}
}

func (_c *MockShoppingRepository_Create_Call) Run(run func(ctx context.Context, orderID string, items []Item)) *MockShoppingRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]Item))
	})
	return _c
}

func (_c *MockShoppingRepository_Create_Call) Return(_a0 string, _a1 error) *MockShoppingRepository_Create_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockShoppingRepository_Create_Call) RunAndReturn(run func(context.Context, string, []Item) (string, error)) *MockShoppingRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockShoppingRepository creates a new instance of MockShoppingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShoppingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShoppingRepository {
	mock := &MockShoppingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
