// Code generated by mockery. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPaymentRepository is an autogenerated mock type for the PaymentRepository type
type MockPaymentRepository struct {
	mock.Mock
}

type MockPaymentRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPaymentRepository) EXPECT() *MockPaymentRepository_Expecter {
	return &MockPaymentRepository_Expecter{mock: &_m.Mock}
}

// Confirm provides a mock function with given fields: ctx, paymentID
func (_m *MockPaymentRepository) Confirm(ctx context.Context, paymentID string) error {
	ret := _m.Called(ctx, paymentID)

	if len(ret) == 0 {
		panic("no return value specified for Confirm")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, paymentID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPaymentRepository_Confirm_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Confirm'
type MockPaymentRepository_Confirm_Call struct {
	*mock.Call
}

// Confirm is a helper method to define mock.On call
//   - ctx context.Context
//   - paymentID string
func (_e *MockPaymentRepository_Expecter) Confirm(ctx interface{}, paymentID interface{}) *MockPaymentRepository_Confirm_Call {
	return &MockPaymentRepository_Confirm_Call{Call: _e.mock.On("Confirm", ctx, paymentID)}
}

func (_c *MockPaymentRepository_Confirm_Call) Run(run func(ctx context.Context, paymentID string)) *MockPaymentRepository_Confirm_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockPaymentRepository_Confirm_Call) Return(_a0 error) *MockPaymentRepository_Confirm_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPaymentRepository_Confirm_Call) RunAndReturn(run func(context.Context, string) error) *MockPaymentRepository_Confirm_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPaymentRepository creates a new instance of MockPaymentRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPaymentRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPaymentRepository {
	mock := &MockPaymentRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
