// Code generated by mockery. DO NOT EDIT.

package customerspb

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockCustomersServiceClient is an autogenerated mock type for the CustomersServiceClient type
type MockCustomersServiceClient struct {
	mock.Mock
}

type MockCustomersServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomersServiceClient) EXPECT() *MockCustomersServiceClient_Expecter {
	return &MockCustomersServiceClient_Expecter{mock: &_m.Mock}
}

// AuthorizeCustomer provides a mock function with given fields: ctx, in, opts
func (_m *MockCustomersServiceClient) AuthorizeCustomer(ctx context.Context, in *AuthorizeCustomerRequest, opts ...grpc.CallOption) (*AuthorizeCustomerResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for AuthorizeCustomer")
	}

	var r0 *AuthorizeCustomerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *AuthorizeCustomerRequest, ...grpc.CallOption) (*AuthorizeCustomerResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *AuthorizeCustomerRequest, ...grpc.CallOption) *AuthorizeCustomerResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*AuthorizeCustomerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *AuthorizeCustomerRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCustomersServiceClient_AuthorizeCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AuthorizeCustomer'
type MockCustomersServiceClient_AuthorizeCustomer_Call struct {
	*mock.Call
}

// AuthorizeCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - in *AuthorizeCustomerRequest
//   - opts ...grpc.CallOption
func (_e *MockCustomersServiceClient_Expecter) AuthorizeCustomer(ctx interface{}, in interface{}, opts ...interface{}) *MockCustomersServiceClient_AuthorizeCustomer_Call {
	return &MockCustomersServiceClient_AuthorizeCustomer_Call{Call: _e.mock.On("AuthorizeCustomer",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCustomersServiceClient_AuthorizeCustomer_Call) Run(run func(ctx context.Context, in *AuthorizeCustomerRequest, opts ...grpc.CallOption)) *MockCustomersServiceClient_AuthorizeCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*AuthorizeCustomerRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockCustomersServiceClient_AuthorizeCustomer_Call) Return(_a0 *AuthorizeCustomerResponse, _a1 error) *MockCustomersServiceClient_AuthorizeCustomer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCustomersServiceClient_AuthorizeCustomer_Call) RunAndReturn(run func(context.Context, *AuthorizeCustomerRequest, ...grpc.CallOption) (*AuthorizeCustomerResponse, error)) *MockCustomersServiceClient_AuthorizeCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// ChangeSmsNumber provides a mock function with given fields: ctx, in, opts
func (_m *MockCustomersServiceClient) ChangeSmsNumber(ctx context.Context, in *ChangeSmsNumberRequest, opts ...grpc.CallOption) (*ChangeSmsNumberResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ChangeSmsNumber")
	}

	var r0 *ChangeSmsNumberResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ChangeSmsNumberRequest, ...grpc.CallOption) (*ChangeSmsNumberResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ChangeSmsNumberRequest, ...grpc.CallOption) *ChangeSmsNumberResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ChangeSmsNumberResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ChangeSmsNumberRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCustomersServiceClient_ChangeSmsNumber_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ChangeSmsNumber'
type MockCustomersServiceClient_ChangeSmsNumber_Call struct {
	*mock.Call
}

// ChangeSmsNumber is a helper method to define mock.On call
//   - ctx context.Context
//   - in *ChangeSmsNumberRequest
//   - opts ...grpc.CallOption
func (_e *MockCustomersServiceClient_Expecter) ChangeSmsNumber(ctx interface{}, in interface{}, opts ...interface{}) *MockCustomersServiceClient_ChangeSmsNumber_Call {
	return &MockCustomersServiceClient_ChangeSmsNumber_Call{Call: _e.mock.On("ChangeSmsNumber",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCustomersServiceClient_ChangeSmsNumber_Call) Run(run func(ctx context.Context, in *ChangeSmsNumberRequest, opts ...grpc.CallOption)) *MockCustomersServiceClient_ChangeSmsNumber_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*ChangeSmsNumberRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockCustomersServiceClient_ChangeSmsNumber_Call) Return(_a0 *ChangeSmsNumberResponse, _a1 error) *MockCustomersServiceClient_ChangeSmsNumber_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCustomersServiceClient_ChangeSmsNumber_Call) RunAndReturn(run func(context.Context, *ChangeSmsNumberRequest, ...grpc.CallOption) (*ChangeSmsNumberResponse, error)) *MockCustomersServiceClient_ChangeSmsNumber_Call {
	_c.Call.Return(run)
	return _c
}

// DisableCustomer provides a mock function with given fields: ctx, in, opts
func (_m *MockCustomersServiceClient) DisableCustomer(ctx context.Context, in *DisableCustomerRequest, opts ...grpc.CallOption) (*DisableCustomerResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for DisableCustomer")
	}

	var r0 *DisableCustomerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *DisableCustomerRequest, ...grpc.CallOption) (*DisableCustomerResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *DisableCustomerRequest, ...grpc.CallOption) *DisableCustomerResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*DisableCustomerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *DisableCustomerRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCustomersServiceClient_DisableCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableCustomer'
type MockCustomersServiceClient_DisableCustomer_Call struct {
	*mock.Call
}

// DisableCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - in *DisableCustomerRequest
//   - opts ...grpc.CallOption
func (_e *MockCustomersServiceClient_Expecter) DisableCustomer(ctx interface{}, in interface{}, opts ...interface{}) *MockCustomersServiceClient_DisableCustomer_Call {
	return &MockCustomersServiceClient_DisableCustomer_Call{Call: _e.mock.On("DisableCustomer",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCustomersServiceClient_DisableCustomer_Call) Run(run func(ctx context.Context, in *DisableCustomerRequest, opts ...grpc.CallOption)) *MockCustomersServiceClient_DisableCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*DisableCustomerRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockCustomersServiceClient_DisableCustomer_Call) Return(_a0 *DisableCustomerResponse, _a1 error) *MockCustomersServiceClient_DisableCustomer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCustomersServiceClient_DisableCustomer_Call) RunAndReturn(run func(context.Context, *DisableCustomerRequest, ...grpc.CallOption) (*DisableCustomerResponse, error)) *MockCustomersServiceClient_DisableCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// EnableCustomer provides a mock function with given fields: ctx, in, opts
func (_m *MockCustomersServiceClient) EnableCustomer(ctx context.Context, in *EnableCustomerRequest, opts ...grpc.CallOption) (*EnableCustomerResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for EnableCustomer")
	}

	var r0 *EnableCustomerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *EnableCustomerRequest, ...grpc.CallOption) (*EnableCustomerResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *EnableCustomerRequest, ...grpc.CallOption) *EnableCustomerResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*EnableCustomerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *EnableCustomerRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCustomersServiceClient_EnableCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableCustomer'
type MockCustomersServiceClient_EnableCustomer_Call struct {
	*mock.Call
}

// EnableCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - in *EnableCustomerRequest
//   - opts ...grpc.CallOption
func (_e *MockCustomersServiceClient_Expecter) EnableCustomer(ctx interface{}, in interface{}, opts ...interface{}) *MockCustomersServiceClient_EnableCustomer_Call {
	return &MockCustomersServiceClient_EnableCustomer_Call{Call: _e.mock.On("EnableCustomer",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCustomersServiceClient_EnableCustomer_Call) Run(run func(ctx context.Context, in *EnableCustomerRequest, opts ...grpc.CallOption)) *MockCustomersServiceClient_EnableCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*EnableCustomerRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockCustomersServiceClient_EnableCustomer_Call) Return(_a0 *EnableCustomerResponse, _a1 error) *MockCustomersServiceClient_EnableCustomer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCustomersServiceClient_EnableCustomer_Call) RunAndReturn(run func(context.Context, *EnableCustomerRequest, ...grpc.CallOption) (*EnableCustomerResponse, error)) *MockCustomersServiceClient_EnableCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomer provides a mock function with given fields: ctx, in, opts
func (_m *MockCustomersServiceClient) GetCustomer(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption) (*GetCustomerResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomer")
	}

	var r0 *GetCustomerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetCustomerRequest, ...grpc.CallOption) (*GetCustomerResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetCustomerRequest, ...grpc.CallOption) *GetCustomerResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetCustomerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetCustomerRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCustomersServiceClient_GetCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomer'
type MockCustomersServiceClient_GetCustomer_Call struct {
	*mock.Call
}

// GetCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - in *GetCustomerRequest
//   - opts ...grpc.CallOption
func (_e *MockCustomersServiceClient_Expecter) GetCustomer(ctx interface{}, in interface{}, opts ...interface{}) *MockCustomersServiceClient_GetCustomer_Call {
	return &MockCustomersServiceClient_GetCustomer_Call{Call: _e.mock.On("GetCustomer",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCustomersServiceClient_GetCustomer_Call) Run(run func(ctx context.Context, in *GetCustomerRequest, opts ...grpc.CallOption)) *MockCustomersServiceClient_GetCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*GetCustomerRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockCustomersServiceClient_GetCustomer_Call) Return(_a0 *GetCustomerResponse, _a1 error) *MockCustomersServiceClient_GetCustomer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCustomersServiceClient_GetCustomer_Call) RunAndReturn(run func(context.Context, *GetCustomerRequest, ...grpc.CallOption) (*GetCustomerResponse, error)) *MockCustomersServiceClient_GetCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// RegisterCustomer provides a mock function with given fields: ctx, in, opts
func (_m *MockCustomersServiceClient) RegisterCustomer(ctx context.Context, in *RegisterCustomerRequest, opts ...grpc.CallOption) (*RegisterCustomerResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for RegisterCustomer")
	}

	var r0 *RegisterCustomerResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *RegisterCustomerRequest, ...grpc.CallOption) (*RegisterCustomerResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *RegisterCustomerRequest, ...grpc.CallOption) *RegisterCustomerResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*RegisterCustomerResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *RegisterCustomerRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCustomersServiceClient_RegisterCustomer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RegisterCustomer'
type MockCustomersServiceClient_RegisterCustomer_Call struct {
	*mock.Call
}

// RegisterCustomer is a helper method to define mock.On call
//   - ctx context.Context
//   - in *RegisterCustomerRequest
//   - opts ...grpc.CallOption
func (_e *MockCustomersServiceClient_Expecter) RegisterCustomer(ctx interface{}, in interface{}, opts ...interface{}) *MockCustomersServiceClient_RegisterCustomer_Call {
	return &MockCustomersServiceClient_RegisterCustomer_Call{Call: _e.mock.On("RegisterCustomer",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockCustomersServiceClient_RegisterCustomer_Call) Run(run func(ctx context.Context, in *RegisterCustomerRequest, opts ...grpc.CallOption)) *MockCustomersServiceClient_RegisterCustomer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*RegisterCustomerRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockCustomersServiceClient_RegisterCustomer_Call) Return(_a0 *RegisterCustomerResponse, _a1 error) *MockCustomersServiceClient_RegisterCustomer_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCustomersServiceClient_RegisterCustomer_Call) RunAndReturn(run func(context.Context, *RegisterCustomerRequest, ...grpc.CallOption) (*RegisterCustomerResponse, error)) *MockCustomersServiceClient_RegisterCustomer_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCustomersServiceClient creates a new instance of MockCustomersServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomersServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomersServiceClient {
	mock := &MockCustomersServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
