// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=.ts"
// @generated from file depotpb/api.proto (package depotpb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file depotpb/api.proto.
 */
export const file_depotpb_api: GenFile = /*@__PURE__*/
  fileDesc("ChFkZXBvdHBiL2FwaS5wcm90bxIHZGVwb3RwYiJDCglPcmRlckl0ZW0SEgoKcHJvZHVjdF9pZBgBIAEoCRIQCghzdG9yZV9pZBgCIAEoCRIQCghxdWFudGl0eRgDIAEoBSLDAQoMU2hvcHBpbmdMaXN0EgoKAmlkGAEgASgJEhAKCG9yZGVyX2lkGAIgASgJEi8KBXN0b3BzGAMgAygLMiAuZGVwb3RwYi5TaG9wcGluZ0xpc3QuU3RvcHNFbnRyeRIXCg9hc3NpZ25lZF9ib3RfaWQYBCABKAkSDgoGc3RhdHVzGAUgASgJGjsKClN0b3BzRW50cnkSCwoDa2V5GAEgASgJEhwKBXZhbHVlGAIgASgLMg0uZGVwb3RwYi5TdG9wOgI4ASKYAQoEU3RvcBISCgpzdG9yZV9uYW1lGAEgASgJEhYKDnN0b3JlX2xvY2F0aW9uGAIgASgJEicKBWl0ZW1zGAMgAygLMhguZGVwb3RwYi5TdG9wLkl0ZW1zRW50cnkaOwoKSXRlbXNFbnRyeRILCgNrZXkYASABKAkSHAoFdmFsdWUYAiABKAsyDS5kZXBvdHBiLkl0ZW06AjgBIiYKBEl0ZW0SDAoEbmFtZRgBIAEoCRIQCghxdWFudGl0eRgCIAEoBSJQChlDcmVhdGVTaG9wcGluZ0xpc3RSZXF1ZXN0EhAKCG9yZGVyX2lkGAEgASgJEiEKBWl0ZW1zGAIgAygLMhIuZGVwb3RwYi5PcmRlckl0ZW0iKAoaQ3JlYXRlU2hvcHBpbmdMaXN0UmVzcG9uc2USCgoCaWQYASABKAkiJwoZQ2FuY2VsU2hvcHBpbmdMaXN0UmVxdWVzdBIKCgJpZBgBIAEoCSIcChpDYW5jZWxTaG9wcGluZ0xpc3RSZXNwb25zZSI3ChlBc3NpZ25TaG9wcGluZ0xpc3RSZXF1ZXN0EgoKAmlkGAEgASgJEg4KBmJvdF9pZBgCIAEoCSIcChpBc3NpZ25TaG9wcGluZ0xpc3RSZXNwb25zZSIpChtDb21wbGV0ZVNob3BwaW5nTGlzdFJlcXVlc3QSCgoCaWQYASABKAkiHgocQ29tcGxldGVTaG9wcGluZ0xpc3RSZXNwb25zZTKYAwoMRGVwb3RTZXJ2aWNlEl8KEkNyZWF0ZVNob3BwaW5nTGlzdBIiLmRlcG90cGIuQ3JlYXRlU2hvcHBpbmdMaXN0UmVxdWVzdBojLmRlcG90cGIuQ3JlYXRlU2hvcHBpbmdMaXN0UmVzcG9uc2UiABJfChJDYW5jZWxTaG9wcGluZ0xpc3QSIi5kZXBvdHBiLkNhbmNlbFNob3BwaW5nTGlzdFJlcXVlc3QaIy5kZXBvdHBiLkNhbmNlbFNob3BwaW5nTGlzdFJlc3BvbnNlIgASXwoSQXNzaWduU2hvcHBpbmdMaXN0EiIuZGVwb3RwYi5Bc3NpZ25TaG9wcGluZ0xpc3RSZXF1ZXN0GiMuZGVwb3RwYi5Bc3NpZ25TaG9wcGluZ0xpc3RSZXNwb25zZSIAEmUKFENvbXBsZXRlU2hvcHBpbmdMaXN0EiQuZGVwb3RwYi5Db21wbGV0ZVNob3BwaW5nTGlzdFJlcXVlc3QaJS5kZXBvdHBiLkNvbXBsZXRlU2hvcHBpbmdMaXN0UmVzcG9uc2UiAEKKAQoLY29tLmRlcG90cGJCCEFwaVByb3RvUAFaNWdpdGh1Yi5jb20vb3dlenp5L3Nva28tYm9yYS1tbmd0LXN5c3RlbS9kZXBvdC9kZXBvdHBiogIDRFhYqgIHRGVwb3RwYsoCB0RlcG90cGLiAhNEZXBvdHBiXEdQQk1ldGFkYXRh6gIHRGVwb3RwYmIGcHJvdG8z");

/**
 * @generated from message depotpb.OrderItem
 */
export type OrderItem = Message<"depotpb.OrderItem"> & {
  /**
   * @generated from field: string product_id = 1;
   */
  productId: string;

  /**
   * @generated from field: string store_id = 2;
   */
  storeId: string;

  /**
   * @generated from field: int32 quantity = 3;
   */
  quantity: number;
};

/**
 * Describes the message depotpb.OrderItem.
 * Use `create(OrderItemSchema)` to create a new message.
 */
export const OrderItemSchema: GenMessage<OrderItem> = /*@__PURE__*/
  messageDesc(file_depotpb_api, 0);

/**
 * @generated from message depotpb.ShoppingList
 */
export type ShoppingList = Message<"depotpb.ShoppingList"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string order_id = 2;
   */
  orderId: string;

  /**
   * @generated from field: map<string, depotpb.Stop> stops = 3;
   */
  stops: { [key: string]: Stop };

  /**
   * @generated from field: string assigned_bot_id = 4;
   */
  assignedBotId: string;

  /**
   * @generated from field: string status = 5;
   */
  status: string;
};

/**
 * Describes the message depotpb.ShoppingList.
 * Use `create(ShoppingListSchema)` to create a new message.
 */
export const ShoppingListSchema: GenMessage<ShoppingList> = /*@__PURE__*/
  messageDesc(file_depotpb_api, 1);

/**
 * @generated from message depotpb.Stop
 */
export type Stop = Message<"depotpb.Stop"> & {
  /**
   * @generated from field: string store_name = 1;
   */
  storeName: string;

  /**
   * @generated from field: string store_location = 2;
   */
  storeLocation: string;

  /**
   * @generated from field: map<string, depotpb.Item> items = 3;
   */
  items: { [key: string]: Item };
};

/**
 * Describes the message depotpb.Stop.
 * Use `create(StopSchema)` to create a new message.
 */
export const StopSchema: GenMessage<Stop> = /*@__PURE__*/
  messageDesc(file_depotpb_api, 2);

/**
 * @generated from message depotpb.Item
 */
export type Item = Message<"depotpb.Item"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: int32 quantity = 2;
   */
  quantity: number;
};

/**
 * Describes the message depotpb.Item.
 * Use `create(ItemSchema)` to create a new message.
 */
export const ItemSchema: GenMessage<Item> = /*@__PURE__*/
  messageDesc(file_depotpb_api, 3);

/**
 * @generated from message depotpb.CreateShoppingListRequest
 */
export type CreateShoppingListRequest = Message<"depotpb.CreateShoppingListRequest"> & {
  /**
   * @generated from field: string order_id = 1;
   */
  orderId: string;

  /**
   * @generated from field: repeated depotpb.OrderItem items = 2;
   */
  items: OrderItem[];
};

/**
 * Describes the message depotpb.CreateShoppingListRequest.
 * Use `create(CreateShoppingListRequestSchema)` to create a new message.
 */
export const CreateShoppingListRequestSchema: GenMessage<CreateShoppingListRequest> = /*@__PURE__*/
  messageDesc(file_depotpb_api, 4);

/**
 * @generated from message depotpb.CreateShoppingListResponse
 */
export type CreateShoppingListResponse = Message<"depotpb.CreateShoppingListResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message depotpb.CreateShoppingListResponse.
 * Use `create(CreateShoppingListResponseSchema)` to create a new message.
 */
export const CreateShoppingListResponseSchema: GenMessage<CreateShoppingListResponse> = /*@__PURE__*/
  messageDesc(file_depotpb_api, 5);

/**
 * @generated from message depotpb.CancelShoppingListRequest
 */
export type CancelShoppingListRequest = Message<"depotpb.CancelShoppingListRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message depotpb.CancelShoppingListRequest.
 * Use `create(CancelShoppingListRequestSchema)` to create a new message.
 */
export const CancelShoppingListRequestSchema: GenMessage<CancelShoppingListRequest> = /*@__PURE__*/
  messageDesc(file_depotpb_api, 6);

/**
 * @generated from message depotpb.CancelShoppingListResponse
 */
export type CancelShoppingListResponse = Message<"depotpb.CancelShoppingListResponse"> & {
};

/**
 * Describes the message depotpb.CancelShoppingListResponse.
 * Use `create(CancelShoppingListResponseSchema)` to create a new message.
 */
export const CancelShoppingListResponseSchema: GenMessage<CancelShoppingListResponse> = /*@__PURE__*/
  messageDesc(file_depotpb_api, 7);

/**
 * @generated from message depotpb.AssignShoppingListRequest
 */
export type AssignShoppingListRequest = Message<"depotpb.AssignShoppingListRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string bot_id = 2;
   */
  botId: string;
};

/**
 * Describes the message depotpb.AssignShoppingListRequest.
 * Use `create(AssignShoppingListRequestSchema)` to create a new message.
 */
export const AssignShoppingListRequestSchema: GenMessage<AssignShoppingListRequest> = /*@__PURE__*/
  messageDesc(file_depotpb_api, 8);

/**
 * @generated from message depotpb.AssignShoppingListResponse
 */
export type AssignShoppingListResponse = Message<"depotpb.AssignShoppingListResponse"> & {
};

/**
 * Describes the message depotpb.AssignShoppingListResponse.
 * Use `create(AssignShoppingListResponseSchema)` to create a new message.
 */
export const AssignShoppingListResponseSchema: GenMessage<AssignShoppingListResponse> = /*@__PURE__*/
  messageDesc(file_depotpb_api, 9);

/**
 * @generated from message depotpb.CompleteShoppingListRequest
 */
export type CompleteShoppingListRequest = Message<"depotpb.CompleteShoppingListRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message depotpb.CompleteShoppingListRequest.
 * Use `create(CompleteShoppingListRequestSchema)` to create a new message.
 */
export const CompleteShoppingListRequestSchema: GenMessage<CompleteShoppingListRequest> = /*@__PURE__*/
  messageDesc(file_depotpb_api, 10);

/**
 * @generated from message depotpb.CompleteShoppingListResponse
 */
export type CompleteShoppingListResponse = Message<"depotpb.CompleteShoppingListResponse"> & {
};

/**
 * Describes the message depotpb.CompleteShoppingListResponse.
 * Use `create(CompleteShoppingListResponseSchema)` to create a new message.
 */
export const CompleteShoppingListResponseSchema: GenMessage<CompleteShoppingListResponse> = /*@__PURE__*/
  messageDesc(file_depotpb_api, 11);

/**
 * @generated from service depotpb.DepotService
 */
export const DepotService: GenService<{
  /**
   * @generated from rpc depotpb.DepotService.CreateShoppingList
   */
  createShoppingList: {
    methodKind: "unary";
    input: typeof CreateShoppingListRequestSchema;
    output: typeof CreateShoppingListResponseSchema;
  },
  /**
   * @generated from rpc depotpb.DepotService.CancelShoppingList
   */
  cancelShoppingList: {
    methodKind: "unary";
    input: typeof CancelShoppingListRequestSchema;
    output: typeof CancelShoppingListResponseSchema;
  },
  /**
   * @generated from rpc depotpb.DepotService.AssignShoppingList
   */
  assignShoppingList: {
    methodKind: "unary";
    input: typeof AssignShoppingListRequestSchema;
    output: typeof AssignShoppingListResponseSchema;
  },
  /**
   * @generated from rpc depotpb.DepotService.CompleteShoppingList
   */
  completeShoppingList: {
    methodKind: "unary";
    input: typeof CompleteShoppingListRequestSchema;
    output: typeof CompleteShoppingListResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_depotpb_api, 0);

