// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=.ts"
// @generated from file depotpb/messages.proto (package depotpb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file depotpb/messages.proto.
 */
export const file_depotpb_messages: GenFile = /*@__PURE__*/
  fileDesc("ChZkZXBvdHBiL21lc3NhZ2VzLnByb3RvEgdkZXBvdHBiIjUKFVNob3BwaW5nTGlzdENvbXBsZXRlZBIKCgJpZBgBIAEoCRIQCghvcmRlcl9pZBgCIAEoCSKXAQoSQ3JlYXRlU2hvcHBpbmdMaXN0EhAKCG9yZGVyX2lkGAEgASgJEi8KBWl0ZW1zGAIgAygLMiAuZGVwb3RwYi5DcmVhdGVTaG9wcGluZ0xpc3QuSXRlbRo+CgRJdGVtEhIKCnByb2R1Y3RfaWQYASABKAkSEAoIc3RvcmVfaWQYAiABKAkSEAoIcXVhbnRpdHkYAyABKAUiIAoSQ2FuY2VsU2hvcHBpbmdMaXN0EgoKAmlkGAEgASgJIh4KEEluaXRpYXRlU2hvcHBpbmcSCgoCaWQYASABKAkiIQoTQ3JlYXRlZFNob3BwaW5nTGlzdBIKCgJpZBgBIAEoCUKPAQoLY29tLmRlcG90cGJCDU1lc3NhZ2VzUHJvdG9QAVo1Z2l0aHViLmNvbS9vd2V6enkvc29rby1ib3JhLW1uZ3Qtc3lzdGVtL2RlcG90L2RlcG90cGKiAgNEWFiqAgdEZXBvdHBiygIHRGVwb3RwYuICE0RlcG90cGJcR1BCTWV0YWRhdGHqAgdEZXBvdHBiYgZwcm90bzM");

/**
 * @generated from message depotpb.ShoppingListCompleted
 */
export type ShoppingListCompleted = Message<"depotpb.ShoppingListCompleted"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string order_id = 2;
   */
  orderId: string;
};

/**
 * Describes the message depotpb.ShoppingListCompleted.
 * Use `create(ShoppingListCompletedSchema)` to create a new message.
 */
export const ShoppingListCompletedSchema: GenMessage<ShoppingListCompleted> = /*@__PURE__*/
  messageDesc(file_depotpb_messages, 0);

/**
 * @generated from message depotpb.CreateShoppingList
 */
export type CreateShoppingList = Message<"depotpb.CreateShoppingList"> & {
  /**
   * @generated from field: string order_id = 1;
   */
  orderId: string;

  /**
   * @generated from field: repeated depotpb.CreateShoppingList.Item items = 2;
   */
  items: CreateShoppingList_Item[];
};

/**
 * Describes the message depotpb.CreateShoppingList.
 * Use `create(CreateShoppingListSchema)` to create a new message.
 */
export const CreateShoppingListSchema: GenMessage<CreateShoppingList> = /*@__PURE__*/
  messageDesc(file_depotpb_messages, 1);

/**
 * @generated from message depotpb.CreateShoppingList.Item
 */
export type CreateShoppingList_Item = Message<"depotpb.CreateShoppingList.Item"> & {
  /**
   * @generated from field: string product_id = 1;
   */
  productId: string;

  /**
   * @generated from field: string store_id = 2;
   */
  storeId: string;

  /**
   * @generated from field: int32 quantity = 3;
   */
  quantity: number;
};

/**
 * Describes the message depotpb.CreateShoppingList.Item.
 * Use `create(CreateShoppingList_ItemSchema)` to create a new message.
 */
export const CreateShoppingList_ItemSchema: GenMessage<CreateShoppingList_Item> = /*@__PURE__*/
  messageDesc(file_depotpb_messages, 1, 0);

/**
 * @generated from message depotpb.CancelShoppingList
 */
export type CancelShoppingList = Message<"depotpb.CancelShoppingList"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message depotpb.CancelShoppingList.
 * Use `create(CancelShoppingListSchema)` to create a new message.
 */
export const CancelShoppingListSchema: GenMessage<CancelShoppingList> = /*@__PURE__*/
  messageDesc(file_depotpb_messages, 2);

/**
 * @generated from message depotpb.InitiateShopping
 */
export type InitiateShopping = Message<"depotpb.InitiateShopping"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message depotpb.InitiateShopping.
 * Use `create(InitiateShoppingSchema)` to create a new message.
 */
export const InitiateShoppingSchema: GenMessage<InitiateShopping> = /*@__PURE__*/
  messageDesc(file_depotpb_messages, 3);

/**
 * @generated from message depotpb.CreatedShoppingList
 */
export type CreatedShoppingList = Message<"depotpb.CreatedShoppingList"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message depotpb.CreatedShoppingList.
 * Use `create(CreatedShoppingListSchema)` to create a new message.
 */
export const CreatedShoppingListSchema: GenMessage<CreatedShoppingList> = /*@__PURE__*/
  messageDesc(file_depotpb_messages, 4);

