// @generated by protoc-gen-es v2.12.0 with parameter "target=ts,import_extension=.ts"
// @generated from file storespb/events.proto (package storespb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file storespb/events.proto.
 */
export const file_storespb_events: GenFile = /*@__PURE__*/
  fileDesc("ChVzdG9yZXNwYi9ldmVudHMucHJvdG8SCHN0b3Jlc3BiIjoKDFN0b3JlQ3JlYXRlZBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEhAKCGxvY2F0aW9uGAMgASgJIj4KGVN0b3JlUGFydGljaXBhdGlvblRvZ2dsZWQSCgoCaWQYASABKAkSFQoNcGFydGljaXBhdGluZxgCIAEoCCIqCg5TdG9yZVJlYnJhbmRlZBIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJImsKDFByb2R1Y3RBZGRlZBIKCgJpZBgBIAEoCRIQCghzdG9yZV9pZBgCIAEoCRIMCgRuYW1lGAMgASgJEhMKC2Rlc2NyaXB0aW9uGAQgASgJEgsKA3NrdRgFIAEoCRINCgVwcmljZRgGIAEoASJBChBQcm9kdWN0UmVicmFuZGVkEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkiMAoTUHJvZHVjdFByaWNlQ2hhbmdlZBIKCgJpZBgBIAEoCRINCgVkZWx0YRgCIAEoASIcCg5Qcm9kdWN0UmVtb3ZlZBIKCgJpZBgBIAEoCUKUAQoMY29tLnN0b3Jlc3BiQgtFdmVudHNQcm90b1ABWjdnaXRodWIuY29tL293ZXp6eS9zb2tvLWJvcmEtbW5ndC1zeXN0ZW0vc3RvcmVzL3N0b3Jlc3BiogIDU1hYqgIIU3RvcmVzcGLKAghTdG9yZXNwYuICFFN0b3Jlc3BiXEdQQk1ldGFkYXRh6gIIU3RvcmVzcGJiBnByb3RvMw");

/**
 * @generated from message storespb.StoreCreated
 */
export type StoreCreated = Message<"storespb.StoreCreated"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string location = 3;
   */
  location: string;
};

/**
 * Describes the message storespb.StoreCreated.
 * Use `create(StoreCreatedSchema)` to create a new message.
 */
export const StoreCreatedSchema: GenMessage<StoreCreated> = /*@__PURE__*/
  messageDesc(file_storespb_events, 0);

/**
 * @generated from message storespb.StoreParticipationToggled
 */
export type StoreParticipationToggled = Message<"storespb.StoreParticipationToggled"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: bool participating = 2;
   */
  participating: boolean;
};

/**
 * Describes the message storespb.StoreParticipationToggled.
 * Use `create(StoreParticipationToggledSchema)` to create a new message.
 */
export const StoreParticipationToggledSchema: GenMessage<StoreParticipationToggled> = /*@__PURE__*/
  messageDesc(file_storespb_events, 1);

/**
 * @generated from message storespb.StoreRebranded
 */
export type StoreRebranded = Message<"storespb.StoreRebranded"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message storespb.StoreRebranded.
 * Use `create(StoreRebrandedSchema)` to create a new message.
 */
export const StoreRebrandedSchema: GenMessage<StoreRebranded> = /*@__PURE__*/
  messageDesc(file_storespb_events, 2);

/**
 * @generated from message storespb.ProductAdded
 */
export type ProductAdded = Message<"storespb.ProductAdded"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string store_id = 2;
   */
  storeId: string;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: string sku = 5;
   */
  sku: string;

  /**
   * @generated from field: double price = 6;
   */
  price: number;
};

/**
 * Describes the message storespb.ProductAdded.
 * Use `create(ProductAddedSchema)` to create a new message.
 */
export const ProductAddedSchema: GenMessage<ProductAdded> = /*@__PURE__*/
  messageDesc(file_storespb_events, 3);

/**
 * @generated from message storespb.ProductRebranded
 */
export type ProductRebranded = Message<"storespb.ProductRebranded"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;
};

/**
 * Describes the message storespb.ProductRebranded.
 * Use `create(ProductRebrandedSchema)` to create a new message.
 */
export const ProductRebrandedSchema: GenMessage<ProductRebranded> = /*@__PURE__*/
  messageDesc(file_storespb_events, 4);

/**
 * @generated from message storespb.ProductPriceChanged
 */
export type ProductPriceChanged = Message<"storespb.ProductPriceChanged"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: double delta = 2;
   */
  delta: number;
};

/**
 * Describes the message storespb.ProductPriceChanged.
 * Use `create(ProductPriceChangedSchema)` to create a new message.
 */
export const ProductPriceChangedSchema: GenMessage<ProductPriceChanged> = /*@__PURE__*/
  messageDesc(file_storespb_events, 5);

/**
 * @generated from message storespb.ProductRemoved
 */
export type ProductRemoved = Message<"storespb.ProductRemoved"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message storespb.ProductRemoved.
 * Use `create(ProductRemovedSchema)` to create a new message.
 */
export const ProductRemovedSchema: GenMessage<ProductRemoved> = /*@__PURE__*/
  messageDesc(file_storespb_events, 6);

