// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: basketspb/api.proto

package basketspbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	basketspb "github.com/owezzy/soko-bora-mngt-system/baskets/basketspb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BasketServiceName is the fully-qualified name of the BasketService service.
	BasketServiceName = "basketspb.BasketService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BasketServiceStartBasketProcedure is the fully-qualified name of the BasketService's StartBasket
	// RPC.
	BasketServiceStartBasketProcedure = "/basketspb.BasketService/StartBasket"
	// BasketServiceCancelBasketProcedure is the fully-qualified name of the BasketService's
	// CancelBasket RPC.
	BasketServiceCancelBasketProcedure = "/basketspb.BasketService/CancelBasket"
	// BasketServiceCheckoutBasketProcedure is the fully-qualified name of the BasketService's
	// CheckoutBasket RPC.
	BasketServiceCheckoutBasketProcedure = "/basketspb.BasketService/CheckoutBasket"
	// BasketServiceAddItemProcedure is the fully-qualified name of the BasketService's AddItem RPC.
	BasketServiceAddItemProcedure = "/basketspb.BasketService/AddItem"
	// BasketServiceRemoveItemProcedure is the fully-qualified name of the BasketService's RemoveItem
	// RPC.
	BasketServiceRemoveItemProcedure = "/basketspb.BasketService/RemoveItem"
	// BasketServiceGetBasketProcedure is the fully-qualified name of the BasketService's GetBasket RPC.
	BasketServiceGetBasketProcedure = "/basketspb.BasketService/GetBasket"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	basketServiceServiceDescriptor              = basketspb.File_basketspb_api_proto.Services().ByName("BasketService")
	basketServiceStartBasketMethodDescriptor    = basketServiceServiceDescriptor.Methods().ByName("StartBasket")
	basketServiceCancelBasketMethodDescriptor   = basketServiceServiceDescriptor.Methods().ByName("CancelBasket")
	basketServiceCheckoutBasketMethodDescriptor = basketServiceServiceDescriptor.Methods().ByName("CheckoutBasket")
	basketServiceAddItemMethodDescriptor        = basketServiceServiceDescriptor.Methods().ByName("AddItem")
	basketServiceRemoveItemMethodDescriptor     = basketServiceServiceDescriptor.Methods().ByName("RemoveItem")
	basketServiceGetBasketMethodDescriptor      = basketServiceServiceDescriptor.Methods().ByName("GetBasket")
)

// BasketServiceClient is a client for the basketspb.BasketService service.
type BasketServiceClient interface {
	StartBasket(context.Context, *connect.Request[basketspb.StartBasketRequest]) (*connect.Response[basketspb.StartBasketResponse], error)
	CancelBasket(context.Context, *connect.Request[basketspb.CancelBasketRequest]) (*connect.Response[basketspb.CancelBasketResponse], error)
	CheckoutBasket(context.Context, *connect.Request[basketspb.CheckoutBasketRequest]) (*connect.Response[basketspb.CheckoutBasketResponse], error)
	AddItem(context.Context, *connect.Request[basketspb.AddItemRequest]) (*connect.Response[basketspb.AddItemResponse], error)
	RemoveItem(context.Context, *connect.Request[basketspb.RemoveItemRequest]) (*connect.Response[basketspb.RemoveItemResponse], error)
	GetBasket(context.Context, *connect.Request[basketspb.GetBasketRequest]) (*connect.Response[basketspb.GetBasketResponse], error)
}

// NewBasketServiceClient constructs a client for the basketspb.BasketService service. By default,
// it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and
// sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC()
// or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBasketServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BasketServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &basketServiceClient{
		startBasket: connect.NewClient[basketspb.StartBasketRequest, basketspb.StartBasketResponse](
			httpClient,
			baseURL+BasketServiceStartBasketProcedure,
			connect.WithSchema(basketServiceStartBasketMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		cancelBasket: connect.NewClient[basketspb.CancelBasketRequest, basketspb.CancelBasketResponse](
			httpClient,
			baseURL+BasketServiceCancelBasketProcedure,
			connect.WithSchema(basketServiceCancelBasketMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		checkoutBasket: connect.NewClient[basketspb.CheckoutBasketRequest, basketspb.CheckoutBasketResponse](
			httpClient,
			baseURL+BasketServiceCheckoutBasketProcedure,
			connect.WithSchema(basketServiceCheckoutBasketMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		addItem: connect.NewClient[basketspb.AddItemRequest, basketspb.AddItemResponse](
			httpClient,
			baseURL+BasketServiceAddItemProcedure,
			connect.WithSchema(basketServiceAddItemMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		removeItem: connect.NewClient[basketspb.RemoveItemRequest, basketspb.RemoveItemResponse](
			httpClient,
			baseURL+BasketServiceRemoveItemProcedure,
			connect.WithSchema(basketServiceRemoveItemMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		getBasket: connect.NewClient[basketspb.GetBasketRequest, basketspb.GetBasketResponse](
			httpClient,
			baseURL+BasketServiceGetBasketProcedure,
			connect.WithSchema(basketServiceGetBasketMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// basketServiceClient implements BasketServiceClient.
type basketServiceClient struct {
	startBasket    *connect.Client[basketspb.StartBasketRequest, basketspb.StartBasketResponse]
	cancelBasket   *connect.Client[basketspb.CancelBasketRequest, basketspb.CancelBasketResponse]
	checkoutBasket *connect.Client[basketspb.CheckoutBasketRequest, basketspb.CheckoutBasketResponse]
	addItem        *connect.Client[basketspb.AddItemRequest, basketspb.AddItemResponse]
	removeItem     *connect.Client[basketspb.RemoveItemRequest, basketspb.RemoveItemResponse]
	getBasket      *connect.Client[basketspb.GetBasketRequest, basketspb.GetBasketResponse]
}

// StartBasket calls basketspb.BasketService.StartBasket.
func (c *basketServiceClient) StartBasket(ctx context.Context, req *connect.Request[basketspb.StartBasketRequest]) (*connect.Response[basketspb.StartBasketResponse], error) {
	return c.startBasket.CallUnary(ctx, req)
}

// CancelBasket calls basketspb.BasketService.CancelBasket.
func (c *basketServiceClient) CancelBasket(ctx context.Context, req *connect.Request[basketspb.CancelBasketRequest]) (*connect.Response[basketspb.CancelBasketResponse], error) {
	return c.cancelBasket.CallUnary(ctx, req)
}

// CheckoutBasket calls basketspb.BasketService.CheckoutBasket.
func (c *basketServiceClient) CheckoutBasket(ctx context.Context, req *connect.Request[basketspb.CheckoutBasketRequest]) (*connect.Response[basketspb.CheckoutBasketResponse], error) {
	return c.checkoutBasket.CallUnary(ctx, req)
}

// AddItem calls basketspb.BasketService.AddItem.
func (c *basketServiceClient) AddItem(ctx context.Context, req *connect.Request[basketspb.AddItemRequest]) (*connect.Response[basketspb.AddItemResponse], error) {
	return c.addItem.CallUnary(ctx, req)
}

// RemoveItem calls basketspb.BasketService.RemoveItem.
func (c *basketServiceClient) RemoveItem(ctx context.Context, req *connect.Request[basketspb.RemoveItemRequest]) (*connect.Response[basketspb.RemoveItemResponse], error) {
	return c.removeItem.CallUnary(ctx, req)
}

// GetBasket calls basketspb.BasketService.GetBasket.
func (c *basketServiceClient) GetBasket(ctx context.Context, req *connect.Request[basketspb.GetBasketRequest]) (*connect.Response[basketspb.GetBasketResponse], error) {
	return c.getBasket.CallUnary(ctx, req)
}

// BasketServiceHandler is an implementation of the basketspb.BasketService service.
type BasketServiceHandler interface {
	StartBasket(context.Context, *connect.Request[basketspb.StartBasketRequest]) (*connect.Response[basketspb.StartBasketResponse], error)
	CancelBasket(context.Context, *connect.Request[basketspb.CancelBasketRequest]) (*connect.Response[basketspb.CancelBasketResponse], error)
	CheckoutBasket(context.Context, *connect.Request[basketspb.CheckoutBasketRequest]) (*connect.Response[basketspb.CheckoutBasketResponse], error)
	AddItem(context.Context, *connect.Request[basketspb.AddItemRequest]) (*connect.Response[basketspb.AddItemResponse], error)
	RemoveItem(context.Context, *connect.Request[basketspb.RemoveItemRequest]) (*connect.Response[basketspb.RemoveItemResponse], error)
	GetBasket(context.Context, *connect.Request[basketspb.GetBasketRequest]) (*connect.Response[basketspb.GetBasketResponse], error)
}

// NewBasketServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBasketServiceHandler(svc BasketServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	basketServiceStartBasketHandler := connect.NewUnaryHandler(
		BasketServiceStartBasketProcedure,
		svc.StartBasket,
		connect.WithSchema(basketServiceStartBasketMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	basketServiceCancelBasketHandler := connect.NewUnaryHandler(
		BasketServiceCancelBasketProcedure,
		svc.CancelBasket,
		connect.WithSchema(basketServiceCancelBasketMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	basketServiceCheckoutBasketHandler := connect.NewUnaryHandler(
		BasketServiceCheckoutBasketProcedure,
		svc.CheckoutBasket,
		connect.WithSchema(basketServiceCheckoutBasketMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	basketServiceAddItemHandler := connect.NewUnaryHandler(
		BasketServiceAddItemProcedure,
		svc.AddItem,
		connect.WithSchema(basketServiceAddItemMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	basketServiceRemoveItemHandler := connect.NewUnaryHandler(
		BasketServiceRemoveItemProcedure,
		svc.RemoveItem,
		connect.WithSchema(basketServiceRemoveItemMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	basketServiceGetBasketHandler := connect.NewUnaryHandler(
		BasketServiceGetBasketProcedure,
		svc.GetBasket,
		connect.WithSchema(basketServiceGetBasketMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/basketspb.BasketService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BasketServiceStartBasketProcedure:
			basketServiceStartBasketHandler.ServeHTTP(w, r)
		case BasketServiceCancelBasketProcedure:
			basketServiceCancelBasketHandler.ServeHTTP(w, r)
		case BasketServiceCheckoutBasketProcedure:
			basketServiceCheckoutBasketHandler.ServeHTTP(w, r)
		case BasketServiceAddItemProcedure:
			basketServiceAddItemHandler.ServeHTTP(w, r)
		case BasketServiceRemoveItemProcedure:
			basketServiceRemoveItemHandler.ServeHTTP(w, r)
		case BasketServiceGetBasketProcedure:
			basketServiceGetBasketHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBasketServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBasketServiceHandler struct{}

func (UnimplementedBasketServiceHandler) StartBasket(context.Context, *connect.Request[basketspb.StartBasketRequest]) (*connect.Response[basketspb.StartBasketResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("basketspb.BasketService.StartBasket is not implemented"))
}

func (UnimplementedBasketServiceHandler) CancelBasket(context.Context, *connect.Request[basketspb.CancelBasketRequest]) (*connect.Response[basketspb.CancelBasketResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("basketspb.BasketService.CancelBasket is not implemented"))
}

func (UnimplementedBasketServiceHandler) CheckoutBasket(context.Context, *connect.Request[basketspb.CheckoutBasketRequest]) (*connect.Response[basketspb.CheckoutBasketResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("basketspb.BasketService.CheckoutBasket is not implemented"))
}

func (UnimplementedBasketServiceHandler) AddItem(context.Context, *connect.Request[basketspb.AddItemRequest]) (*connect.Response[basketspb.AddItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("basketspb.BasketService.AddItem is not implemented"))
}

func (UnimplementedBasketServiceHandler) RemoveItem(context.Context, *connect.Request[basketspb.RemoveItemRequest]) (*connect.Response[basketspb.RemoveItemResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("basketspb.BasketService.RemoveItem is not implemented"))
}

func (UnimplementedBasketServiceHandler) GetBasket(context.Context, *connect.Request[basketspb.GetBasketRequest]) (*connect.Response[basketspb.GetBasketResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("basketspb.BasketService.GetBasket is not implemented"))
}
