// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: searchpb/api.proto

package searchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDemoBootstrapRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDemoBootstrapRequest) Reset() {
	*x = GetDemoBootstrapRequest{}
	mi := &file_searchpb_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDemoBootstrapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDemoBootstrapRequest) ProtoMessage() {}

func (x *GetDemoBootstrapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_searchpb_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDemoBootstrapRequest.ProtoReflect.Descriptor instead.
func (*GetDemoBootstrapRequest) Descriptor() ([]byte, []int) {
	return file_searchpb_api_proto_rawDescGZIP(), []int{0}
}

type DemoCustomer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoCustomer) Reset() {
	*x = DemoCustomer{}
	mi := &file_searchpb_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoCustomer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoCustomer) ProtoMessage() {}

func (x *DemoCustomer) ProtoReflect() protoreflect.Message {
	mi := &file_searchpb_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoCustomer.ProtoReflect.Descriptor instead.
func (*DemoCustomer) Descriptor() ([]byte, []int) {
	return file_searchpb_api_proto_rawDescGZIP(), []int{1}
}

func (x *DemoCustomer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DemoCustomer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DemoStore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoStore) Reset() {
	*x = DemoStore{}
	mi := &file_searchpb_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoStore) ProtoMessage() {}

func (x *DemoStore) ProtoReflect() protoreflect.Message {
	mi := &file_searchpb_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoStore.ProtoReflect.Descriptor instead.
func (*DemoStore) Descriptor() ([]byte, []int) {
	return file_searchpb_api_proto_rawDescGZIP(), []int{2}
}

func (x *DemoStore) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DemoStore) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DemoProduct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StoreId       string                 `protobuf:"bytes,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	StoreName     string                 `protobuf:"bytes,3,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DemoProduct) Reset() {
	*x = DemoProduct{}
	mi := &file_searchpb_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DemoProduct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoProduct) ProtoMessage() {}

func (x *DemoProduct) ProtoReflect() protoreflect.Message {
	mi := &file_searchpb_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoProduct.ProtoReflect.Descriptor instead.
func (*DemoProduct) Descriptor() ([]byte, []int) {
	return file_searchpb_api_proto_rawDescGZIP(), []int{3}
}

func (x *DemoProduct) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DemoProduct) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *DemoProduct) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *DemoProduct) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDemoBootstrapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Customer      *DemoCustomer          `protobuf:"bytes,1,opt,name=customer,proto3" json:"customer,omitempty"`
	Stores        []*DemoStore           `protobuf:"bytes,2,rep,name=stores,proto3" json:"stores,omitempty"`
	Products      []*DemoProduct         `protobuf:"bytes,3,rep,name=products,proto3" json:"products,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDemoBootstrapResponse) Reset() {
	*x = GetDemoBootstrapResponse{}
	mi := &file_searchpb_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDemoBootstrapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDemoBootstrapResponse) ProtoMessage() {}

func (x *GetDemoBootstrapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_searchpb_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDemoBootstrapResponse.ProtoReflect.Descriptor instead.
func (*GetDemoBootstrapResponse) Descriptor() ([]byte, []int) {
	return file_searchpb_api_proto_rawDescGZIP(), []int{4}
}

func (x *GetDemoBootstrapResponse) GetCustomer() *DemoCustomer {
	if x != nil {
		return x.Customer
	}
	return nil
}

func (x *GetDemoBootstrapResponse) GetStores() []*DemoStore {
	if x != nil {
		return x.Stores
	}
	return nil
}

func (x *GetDemoBootstrapResponse) GetProducts() []*DemoProduct {
	if x != nil {
		return x.Products
	}
	return nil
}

type Order struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	CustomerId    string                 `protobuf:"bytes,2,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	CustomerName  string                 `protobuf:"bytes,3,opt,name=customer_name,json=customerName,proto3" json:"customer_name,omitempty"`
	Items         []*Order_Item          `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	Total         float64                `protobuf:"fixed64,5,opt,name=total,proto3" json:"total,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order) Reset() {
	*x = Order{}
	mi := &file_searchpb_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order) ProtoMessage() {}

func (x *Order) ProtoReflect() protoreflect.Message {
	mi := &file_searchpb_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order.ProtoReflect.Descriptor instead.
func (*Order) Descriptor() ([]byte, []int) {
	return file_searchpb_api_proto_rawDescGZIP(), []int{5}
}

func (x *Order) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *Order) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *Order) GetCustomerName() string {
	if x != nil {
		return x.CustomerName
	}
	return ""
}

func (x *Order) GetItems() []*Order_Item {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Order) GetTotal() float64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Order) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SearchOrdersRequest struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Filters       *SearchOrdersRequest_Filters `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	Next          string                       `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	Limit         int32                        `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOrdersRequest) Reset() {
	*x = SearchOrdersRequest{}
	mi := &file_searchpb_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOrdersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrdersRequest) ProtoMessage() {}

func (x *SearchOrdersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_searchpb_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrdersRequest.ProtoReflect.Descriptor instead.
func (*SearchOrdersRequest) Descriptor() ([]byte, []int) {
	return file_searchpb_api_proto_rawDescGZIP(), []int{6}
}

func (x *SearchOrdersRequest) GetFilters() *SearchOrdersRequest_Filters {
	if x != nil {
		return x.Filters
	}
	return nil
}

func (x *SearchOrdersRequest) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

func (x *SearchOrdersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchOrdersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Orders        []*Order               `protobuf:"bytes,1,rep,name=orders,proto3" json:"orders,omitempty"`
	Next          string                 `protobuf:"bytes,2,opt,name=next,proto3" json:"next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOrdersResponse) Reset() {
	*x = SearchOrdersResponse{}
	mi := &file_searchpb_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOrdersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrdersResponse) ProtoMessage() {}

func (x *SearchOrdersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_searchpb_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrdersResponse.ProtoReflect.Descriptor instead.
func (*SearchOrdersResponse) Descriptor() ([]byte, []int) {
	return file_searchpb_api_proto_rawDescGZIP(), []int{7}
}

func (x *SearchOrdersResponse) GetOrders() []*Order {
	if x != nil {
		return x.Orders
	}
	return nil
}

func (x *SearchOrdersResponse) GetNext() string {
	if x != nil {
		return x.Next
	}
	return ""
}

type GetOrderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderRequest) Reset() {
	*x = GetOrderRequest{}
	mi := &file_searchpb_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderRequest) ProtoMessage() {}

func (x *GetOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_searchpb_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderRequest.ProtoReflect.Descriptor instead.
func (*GetOrderRequest) Descriptor() ([]byte, []int) {
	return file_searchpb_api_proto_rawDescGZIP(), []int{8}
}

func (x *GetOrderRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Order         *Order                 `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrderResponse) Reset() {
	*x = GetOrderResponse{}
	mi := &file_searchpb_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrderResponse) ProtoMessage() {}

func (x *GetOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_searchpb_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrderResponse.ProtoReflect.Descriptor instead.
func (*GetOrderResponse) Descriptor() ([]byte, []int) {
	return file_searchpb_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetOrderResponse) GetOrder() *Order {
	if x != nil {
		return x.Order
	}
	return nil
}

type Order_Item struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     string                 `protobuf:"bytes,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	StoreId       string                 `protobuf:"bytes,2,opt,name=store_id,json=storeId,proto3" json:"store_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	StoreName     string                 `protobuf:"bytes,4,opt,name=store_name,json=storeName,proto3" json:"store_name,omitempty"`
	Price         float64                `protobuf:"fixed64,5,opt,name=price,proto3" json:"price,omitempty"`
	Quantity      int64                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Order_Item) Reset() {
	*x = Order_Item{}
	mi := &file_searchpb_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Order_Item) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Order_Item) ProtoMessage() {}

func (x *Order_Item) ProtoReflect() protoreflect.Message {
	mi := &file_searchpb_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Order_Item.ProtoReflect.Descriptor instead.
func (*Order_Item) Descriptor() ([]byte, []int) {
	return file_searchpb_api_proto_rawDescGZIP(), []int{5, 0}
}

func (x *Order_Item) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *Order_Item) GetStoreId() string {
	if x != nil {
		return x.StoreId
	}
	return ""
}

func (x *Order_Item) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *Order_Item) GetStoreName() string {
	if x != nil {
		return x.StoreName
	}
	return ""
}

func (x *Order_Item) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *Order_Item) GetQuantity() int64 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

type SearchOrdersRequest_Filters struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CustomerId    string                 `protobuf:"bytes,1,opt,name=customer_id,json=customerId,proto3" json:"customer_id,omitempty"`
	After         *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=after,proto3" json:"after,omitempty"`
	Before        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=before,proto3" json:"before,omitempty"`
	StoreIds      []string               `protobuf:"bytes,4,rep,name=store_ids,json=storeIds,proto3" json:"store_ids,omitempty"`
	ProductIds    []string               `protobuf:"bytes,5,rep,name=product_ids,json=productIds,proto3" json:"product_ids,omitempty"`
	MinTotal      float64                `protobuf:"fixed64,6,opt,name=min_total,json=minTotal,proto3" json:"min_total,omitempty"`
	MaxTotal      float64                `protobuf:"fixed64,7,opt,name=max_total,json=maxTotal,proto3" json:"max_total,omitempty"`
	Status        string                 `protobuf:"bytes,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchOrdersRequest_Filters) Reset() {
	*x = SearchOrdersRequest_Filters{}
	mi := &file_searchpb_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchOrdersRequest_Filters) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchOrdersRequest_Filters) ProtoMessage() {}

func (x *SearchOrdersRequest_Filters) ProtoReflect() protoreflect.Message {
	mi := &file_searchpb_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchOrdersRequest_Filters.ProtoReflect.Descriptor instead.
func (*SearchOrdersRequest_Filters) Descriptor() ([]byte, []int) {
	return file_searchpb_api_proto_rawDescGZIP(), []int{6, 0}
}

func (x *SearchOrdersRequest_Filters) GetCustomerId() string {
	if x != nil {
		return x.CustomerId
	}
	return ""
}

func (x *SearchOrdersRequest_Filters) GetAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.After
	}
	return nil
}

func (x *SearchOrdersRequest_Filters) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.Before
	}
	return nil
}

func (x *SearchOrdersRequest_Filters) GetStoreIds() []string {
	if x != nil {
		return x.StoreIds
	}
	return nil
}

func (x *SearchOrdersRequest_Filters) GetProductIds() []string {
	if x != nil {
		return x.ProductIds
	}
	return nil
}

func (x *SearchOrdersRequest_Filters) GetMinTotal() float64 {
	if x != nil {
		return x.MinTotal
	}
	return 0
}

func (x *SearchOrdersRequest_Filters) GetMaxTotal() float64 {
	if x != nil {
		return x.MaxTotal
	}
	return 0
}

func (x *SearchOrdersRequest_Filters) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_searchpb_api_proto protoreflect.FileDescriptor

const file_searchpb_api_proto_rawDesc = "" +
	"\n" +
	"\x12searchpb/api.proto\x12\bsearchpb\x1a\x1fgoogle/protobuf/timestamp.proto\"\x19\n" +
	"\x17GetDemoBootstrapRequest\"2\n" +
	"\fDemoCustomer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"/\n" +
	"\tDemoStore\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"k\n" +
	"\vDemoProduct\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\tR\astoreId\x12\x1d\n" +
	"\n" +
	"store_name\x18\x03 \x01(\tR\tstoreName\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\xae\x01\n" +
	"\x18GetDemoBootstrapResponse\x122\n" +
	"\bcustomer\x18\x01 \x01(\v2\x16.searchpb.DemoCustomerR\bcustomer\x12+\n" +
	"\x06stores\x18\x02 \x03(\v2\x13.searchpb.DemoStoreR\x06stores\x121\n" +
	"\bproducts\x18\x03 \x03(\v2\x15.searchpb.DemoProductR\bproducts\"\xf9\x02\n" +
	"\x05Order\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x1f\n" +
	"\vcustomer_id\x18\x02 \x01(\tR\n" +
	"customerId\x12#\n" +
	"\rcustomer_name\x18\x03 \x01(\tR\fcustomerName\x12*\n" +
	"\x05items\x18\x04 \x03(\v2\x14.searchpb.Order.ItemR\x05items\x12\x14\n" +
	"\x05total\x18\x05 \x01(\x01R\x05total\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x1a\xb4\x01\n" +
	"\x04Item\x12\x1d\n" +
	"\n" +
	"product_id\x18\x01 \x01(\tR\tproductId\x12\x19\n" +
	"\bstore_id\x18\x02 \x01(\tR\astoreId\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12\x1d\n" +
	"\n" +
	"store_name\x18\x04 \x01(\tR\tstoreName\x12\x14\n" +
	"\x05price\x18\x05 \x01(\x01R\x05price\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x03R\bquantity\"\xa3\x03\n" +
	"\x13SearchOrdersRequest\x12?\n" +
	"\afilters\x18\x01 \x01(\v2%.searchpb.SearchOrdersRequest.FiltersR\afilters\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x1a\xa0\x02\n" +
	"\aFilters\x12\x1f\n" +
	"\vcustomer_id\x18\x01 \x01(\tR\n" +
	"customerId\x120\n" +
	"\x05after\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\x05after\x122\n" +
	"\x06before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06before\x12\x1b\n" +
	"\tstore_ids\x18\x04 \x03(\tR\bstoreIds\x12\x1f\n" +
	"\vproduct_ids\x18\x05 \x03(\tR\n" +
	"productIds\x12\x1b\n" +
	"\tmin_total\x18\x06 \x01(\x01R\bminTotal\x12\x1b\n" +
	"\tmax_total\x18\a \x01(\x01R\bmaxTotal\x12\x16\n" +
	"\x06status\x18\b \x01(\tR\x06status\"S\n" +
	"\x14SearchOrdersResponse\x12'\n" +
	"\x06orders\x18\x01 \x03(\v2\x0f.searchpb.OrderR\x06orders\x12\x12\n" +
	"\x04next\x18\x02 \x01(\tR\x04next\"!\n" +
	"\x0fGetOrderRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"9\n" +
	"\x10GetOrderResponse\x12%\n" +
	"\x05order\x18\x01 \x01(\v2\x0f.searchpb.OrderR\x05order2\x82\x02\n" +
	"\rSearchService\x12O\n" +
	"\fSearchOrders\x12\x1d.searchpb.SearchOrdersRequest\x1a\x1e.searchpb.SearchOrdersResponse\"\x00\x12C\n" +
	"\bGetOrder\x12\x19.searchpb.GetOrderRequest\x1a\x1a.searchpb.GetOrderResponse\"\x00\x12[\n" +
	"\x10GetDemoBootstrap\x12!.searchpb.GetDemoBootstrapRequest\x1a\".searchpb.GetDemoBootstrapResponse\"\x00B\x91\x01\n" +
	"\fcom.searchpbB\bApiProtoP\x01Z7github.com/owezzy/soko-bora-mngt-system/search/searchpb\xa2\x02\x03SXX\xaa\x02\bSearchpb\xca\x02\bSearchpb\xe2\x02\x14Searchpb\\GPBMetadata\xea\x02\bSearchpbb\x06proto3"

var (
	file_searchpb_api_proto_rawDescOnce sync.Once
	file_searchpb_api_proto_rawDescData []byte
)

func file_searchpb_api_proto_rawDescGZIP() []byte {
	file_searchpb_api_proto_rawDescOnce.Do(func() {
		file_searchpb_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_searchpb_api_proto_rawDesc), len(file_searchpb_api_proto_rawDesc)))
	})
	return file_searchpb_api_proto_rawDescData
}

var file_searchpb_api_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_searchpb_api_proto_goTypes = []any{
	(*GetDemoBootstrapRequest)(nil),     // 0: searchpb.GetDemoBootstrapRequest
	(*DemoCustomer)(nil),                // 1: searchpb.DemoCustomer
	(*DemoStore)(nil),                   // 2: searchpb.DemoStore
	(*DemoProduct)(nil),                 // 3: searchpb.DemoProduct
	(*GetDemoBootstrapResponse)(nil),    // 4: searchpb.GetDemoBootstrapResponse
	(*Order)(nil),                       // 5: searchpb.Order
	(*SearchOrdersRequest)(nil),         // 6: searchpb.SearchOrdersRequest
	(*SearchOrdersResponse)(nil),        // 7: searchpb.SearchOrdersResponse
	(*GetOrderRequest)(nil),             // 8: searchpb.GetOrderRequest
	(*GetOrderResponse)(nil),            // 9: searchpb.GetOrderResponse
	(*Order_Item)(nil),                  // 10: searchpb.Order.Item
	(*SearchOrdersRequest_Filters)(nil), // 11: searchpb.SearchOrdersRequest.Filters
	(*timestamppb.Timestamp)(nil),       // 12: google.protobuf.Timestamp
}
var file_searchpb_api_proto_depIdxs = []int32{
	1,  // 0: searchpb.GetDemoBootstrapResponse.customer:type_name -> searchpb.DemoCustomer
	2,  // 1: searchpb.GetDemoBootstrapResponse.stores:type_name -> searchpb.DemoStore
	3,  // 2: searchpb.GetDemoBootstrapResponse.products:type_name -> searchpb.DemoProduct
	10, // 3: searchpb.Order.items:type_name -> searchpb.Order.Item
	11, // 4: searchpb.SearchOrdersRequest.filters:type_name -> searchpb.SearchOrdersRequest.Filters
	5,  // 5: searchpb.SearchOrdersResponse.orders:type_name -> searchpb.Order
	5,  // 6: searchpb.GetOrderResponse.order:type_name -> searchpb.Order
	12, // 7: searchpb.SearchOrdersRequest.Filters.after:type_name -> google.protobuf.Timestamp
	12, // 8: searchpb.SearchOrdersRequest.Filters.before:type_name -> google.protobuf.Timestamp
	6,  // 9: searchpb.SearchService.SearchOrders:input_type -> searchpb.SearchOrdersRequest
	8,  // 10: searchpb.SearchService.GetOrder:input_type -> searchpb.GetOrderRequest
	0,  // 11: searchpb.SearchService.GetDemoBootstrap:input_type -> searchpb.GetDemoBootstrapRequest
	7,  // 12: searchpb.SearchService.SearchOrders:output_type -> searchpb.SearchOrdersResponse
	9,  // 13: searchpb.SearchService.GetOrder:output_type -> searchpb.GetOrderResponse
	4,  // 14: searchpb.SearchService.GetDemoBootstrap:output_type -> searchpb.GetDemoBootstrapResponse
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_searchpb_api_proto_init() }
func file_searchpb_api_proto_init() {
	if File_searchpb_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_searchpb_api_proto_rawDesc), len(file_searchpb_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_searchpb_api_proto_goTypes,
		DependencyIndexes: file_searchpb_api_proto_depIdxs,
		MessageInfos:      file_searchpb_api_proto_msgTypes,
	}.Build()
	File_searchpb_api_proto = out.File
	file_searchpb_api_proto_goTypes = nil
	file_searchpb_api_proto_depIdxs = nil
}
