// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.ts"
// @generated from file basketspb/api.proto (package basketspb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AddItemRequest, AddItemResponse, CancelBasketRequest, CancelBasketResponse, CheckoutBasketRequest, CheckoutBasketResponse, GetBasketRequest, GetBasketResponse, RemoveItemRequest, RemoveItemResponse, StartBasketRequest, StartBasketResponse } from "./api_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service basketspb.BasketService
 */
export const BasketService = {
  typeName: "basketspb.BasketService",
  methods: {
    /**
     * @generated from rpc basketspb.BasketService.StartBasket
     */
    startBasket: {
      name: "StartBasket",
      I: StartBasketRequest,
      O: StartBasketResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc basketspb.BasketService.CancelBasket
     */
    cancelBasket: {
      name: "CancelBasket",
      I: CancelBasketRequest,
      O: CancelBasketResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc basketspb.BasketService.CheckoutBasket
     */
    checkoutBasket: {
      name: "CheckoutBasket",
      I: CheckoutBasketRequest,
      O: CheckoutBasketResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc basketspb.BasketService.AddItem
     */
    addItem: {
      name: "AddItem",
      I: AddItemRequest,
      O: AddItemResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc basketspb.BasketService.RemoveItem
     */
    removeItem: {
      name: "RemoveItem",
      I: RemoveItemRequest,
      O: RemoveItemResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc basketspb.BasketService.GetBasket
     */
    getBasket: {
      name: "GetBasket",
      I: GetBasketRequest,
      O: GetBasketResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

