// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=.ts"
// @generated from file basketspb/events.proto (package basketspb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file basketspb/events.proto.
 */
export const file_basketspb_events: GenFile = /*@__PURE__*/
  fileDesc("ChZiYXNrZXRzcGIvZXZlbnRzLnByb3RvEgliYXNrZXRzcGIiMAoNQmFza2V0U3RhcnRlZBIKCgJpZBgBIAEoCRITCgtjdXN0b21lcl9pZBgCIAEoCSIcCg5CYXNrZXRDYW5jZWxlZBIKCgJpZBgBIAEoCSLxAQoQQmFza2V0Q2hlY2tlZE91dBIKCgJpZBgBIAEoCRITCgtjdXN0b21lcl9pZBgCIAEoCRISCgpwYXltZW50X2lkGAMgASgJEi8KBWl0ZW1zGAQgAygLMiAuYmFza2V0c3BiLkJhc2tldENoZWNrZWRPdXQuSXRlbRp3CgRJdGVtEhAKCHN0b3JlX2lkGAEgASgJEhIKCnByb2R1Y3RfaWQYAiABKAkSEgoKc3RvcmVfbmFtZRgDIAEoCRIUCgxwcm9kdWN0X25hbWUYBCABKAkSDQoFcHJpY2UYBSABKAESEAoIcXVhbnRpdHkYBiABKAVCmwEKDWNvbS5iYXNrZXRzcGJCC0V2ZW50c1Byb3RvUAFaOWdpdGh1Yi5jb20vb3dlenp5L3Nva28tYm9yYS1tbmd0LXN5c3RlbS9iYXNrZXRzL2Jhc2tldHNwYqICA0JYWKoCCUJhc2tldHNwYsoCCUJhc2tldHNwYuICFUJhc2tldHNwYlxHUEJNZXRhZGF0YeoCCUJhc2tldHNwYmIGcHJvdG8z");

/**
 * @generated from message basketspb.BasketStarted
 */
export type BasketStarted = Message<"basketspb.BasketStarted"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string customer_id = 2;
   */
  customerId: string;
};

/**
 * Describes the message basketspb.BasketStarted.
 * Use `create(BasketStartedSchema)` to create a new message.
 */
export const BasketStartedSchema: GenMessage<BasketStarted> = /*@__PURE__*/
  messageDesc(file_basketspb_events, 0);

/**
 * @generated from message basketspb.BasketCanceled
 */
export type BasketCanceled = Message<"basketspb.BasketCanceled"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message basketspb.BasketCanceled.
 * Use `create(BasketCanceledSchema)` to create a new message.
 */
export const BasketCanceledSchema: GenMessage<BasketCanceled> = /*@__PURE__*/
  messageDesc(file_basketspb_events, 1);

/**
 * @generated from message basketspb.BasketCheckedOut
 */
export type BasketCheckedOut = Message<"basketspb.BasketCheckedOut"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string customer_id = 2;
   */
  customerId: string;

  /**
   * @generated from field: string payment_id = 3;
   */
  paymentId: string;

  /**
   * @generated from field: repeated basketspb.BasketCheckedOut.Item items = 4;
   */
  items: BasketCheckedOut_Item[];
};

/**
 * Describes the message basketspb.BasketCheckedOut.
 * Use `create(BasketCheckedOutSchema)` to create a new message.
 */
export const BasketCheckedOutSchema: GenMessage<BasketCheckedOut> = /*@__PURE__*/
  messageDesc(file_basketspb_events, 2);

/**
 * @generated from message basketspb.BasketCheckedOut.Item
 */
export type BasketCheckedOut_Item = Message<"basketspb.BasketCheckedOut.Item"> & {
  /**
   * @generated from field: string store_id = 1;
   */
  storeId: string;

  /**
   * @generated from field: string product_id = 2;
   */
  productId: string;

  /**
   * @generated from field: string store_name = 3;
   */
  storeName: string;

  /**
   * @generated from field: string product_name = 4;
   */
  productName: string;

  /**
   * @generated from field: double price = 5;
   */
  price: number;

  /**
   * @generated from field: int32 quantity = 6;
   */
  quantity: number;
};

/**
 * Describes the message basketspb.BasketCheckedOut.Item.
 * Use `create(BasketCheckedOut_ItemSchema)` to create a new message.
 */
export const BasketCheckedOut_ItemSchema: GenMessage<BasketCheckedOut_Item> = /*@__PURE__*/
  messageDesc(file_basketspb_events, 2, 0);

