// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: depotpb/api.proto

package depotpbconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	depotpb "github.com/owezzy/soko-bora-mngt-system/depot/depotpb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DepotServiceName is the fully-qualified name of the DepotService service.
	DepotServiceName = "depotpb.DepotService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DepotServiceCreateShoppingListProcedure is the fully-qualified name of the DepotService's
	// CreateShoppingList RPC.
	DepotServiceCreateShoppingListProcedure = "/depotpb.DepotService/CreateShoppingList"
	// DepotServiceCancelShoppingListProcedure is the fully-qualified name of the DepotService's
	// CancelShoppingList RPC.
	DepotServiceCancelShoppingListProcedure = "/depotpb.DepotService/CancelShoppingList"
	// DepotServiceAssignShoppingListProcedure is the fully-qualified name of the DepotService's
	// AssignShoppingList RPC.
	DepotServiceAssignShoppingListProcedure = "/depotpb.DepotService/AssignShoppingList"
	// DepotServiceCompleteShoppingListProcedure is the fully-qualified name of the DepotService's
	// CompleteShoppingList RPC.
	DepotServiceCompleteShoppingListProcedure = "/depotpb.DepotService/CompleteShoppingList"
)

// These variables are the protoreflect.Descriptor objects for the RPCs defined in this package.
var (
	depotServiceServiceDescriptor                    = depotpb.File_depotpb_api_proto.Services().ByName("DepotService")
	depotServiceCreateShoppingListMethodDescriptor   = depotServiceServiceDescriptor.Methods().ByName("CreateShoppingList")
	depotServiceCancelShoppingListMethodDescriptor   = depotServiceServiceDescriptor.Methods().ByName("CancelShoppingList")
	depotServiceAssignShoppingListMethodDescriptor   = depotServiceServiceDescriptor.Methods().ByName("AssignShoppingList")
	depotServiceCompleteShoppingListMethodDescriptor = depotServiceServiceDescriptor.Methods().ByName("CompleteShoppingList")
)

// DepotServiceClient is a client for the depotpb.DepotService service.
type DepotServiceClient interface {
	CreateShoppingList(context.Context, *connect.Request[depotpb.CreateShoppingListRequest]) (*connect.Response[depotpb.CreateShoppingListResponse], error)
	CancelShoppingList(context.Context, *connect.Request[depotpb.CancelShoppingListRequest]) (*connect.Response[depotpb.CancelShoppingListResponse], error)
	AssignShoppingList(context.Context, *connect.Request[depotpb.AssignShoppingListRequest]) (*connect.Response[depotpb.AssignShoppingListResponse], error)
	CompleteShoppingList(context.Context, *connect.Request[depotpb.CompleteShoppingListRequest]) (*connect.Response[depotpb.CompleteShoppingListResponse], error)
}

// NewDepotServiceClient constructs a client for the depotpb.DepotService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDepotServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DepotServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	return &depotServiceClient{
		createShoppingList: connect.NewClient[depotpb.CreateShoppingListRequest, depotpb.CreateShoppingListResponse](
			httpClient,
			baseURL+DepotServiceCreateShoppingListProcedure,
			connect.WithSchema(depotServiceCreateShoppingListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		cancelShoppingList: connect.NewClient[depotpb.CancelShoppingListRequest, depotpb.CancelShoppingListResponse](
			httpClient,
			baseURL+DepotServiceCancelShoppingListProcedure,
			connect.WithSchema(depotServiceCancelShoppingListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		assignShoppingList: connect.NewClient[depotpb.AssignShoppingListRequest, depotpb.AssignShoppingListResponse](
			httpClient,
			baseURL+DepotServiceAssignShoppingListProcedure,
			connect.WithSchema(depotServiceAssignShoppingListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
		completeShoppingList: connect.NewClient[depotpb.CompleteShoppingListRequest, depotpb.CompleteShoppingListResponse](
			httpClient,
			baseURL+DepotServiceCompleteShoppingListProcedure,
			connect.WithSchema(depotServiceCompleteShoppingListMethodDescriptor),
			connect.WithClientOptions(opts...),
		),
	}
}

// depotServiceClient implements DepotServiceClient.
type depotServiceClient struct {
	createShoppingList   *connect.Client[depotpb.CreateShoppingListRequest, depotpb.CreateShoppingListResponse]
	cancelShoppingList   *connect.Client[depotpb.CancelShoppingListRequest, depotpb.CancelShoppingListResponse]
	assignShoppingList   *connect.Client[depotpb.AssignShoppingListRequest, depotpb.AssignShoppingListResponse]
	completeShoppingList *connect.Client[depotpb.CompleteShoppingListRequest, depotpb.CompleteShoppingListResponse]
}

// CreateShoppingList calls depotpb.DepotService.CreateShoppingList.
func (c *depotServiceClient) CreateShoppingList(ctx context.Context, req *connect.Request[depotpb.CreateShoppingListRequest]) (*connect.Response[depotpb.CreateShoppingListResponse], error) {
	return c.createShoppingList.CallUnary(ctx, req)
}

// CancelShoppingList calls depotpb.DepotService.CancelShoppingList.
func (c *depotServiceClient) CancelShoppingList(ctx context.Context, req *connect.Request[depotpb.CancelShoppingListRequest]) (*connect.Response[depotpb.CancelShoppingListResponse], error) {
	return c.cancelShoppingList.CallUnary(ctx, req)
}

// AssignShoppingList calls depotpb.DepotService.AssignShoppingList.
func (c *depotServiceClient) AssignShoppingList(ctx context.Context, req *connect.Request[depotpb.AssignShoppingListRequest]) (*connect.Response[depotpb.AssignShoppingListResponse], error) {
	return c.assignShoppingList.CallUnary(ctx, req)
}

// CompleteShoppingList calls depotpb.DepotService.CompleteShoppingList.
func (c *depotServiceClient) CompleteShoppingList(ctx context.Context, req *connect.Request[depotpb.CompleteShoppingListRequest]) (*connect.Response[depotpb.CompleteShoppingListResponse], error) {
	return c.completeShoppingList.CallUnary(ctx, req)
}

// DepotServiceHandler is an implementation of the depotpb.DepotService service.
type DepotServiceHandler interface {
	CreateShoppingList(context.Context, *connect.Request[depotpb.CreateShoppingListRequest]) (*connect.Response[depotpb.CreateShoppingListResponse], error)
	CancelShoppingList(context.Context, *connect.Request[depotpb.CancelShoppingListRequest]) (*connect.Response[depotpb.CancelShoppingListResponse], error)
	AssignShoppingList(context.Context, *connect.Request[depotpb.AssignShoppingListRequest]) (*connect.Response[depotpb.AssignShoppingListResponse], error)
	CompleteShoppingList(context.Context, *connect.Request[depotpb.CompleteShoppingListRequest]) (*connect.Response[depotpb.CompleteShoppingListResponse], error)
}

// NewDepotServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDepotServiceHandler(svc DepotServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	depotServiceCreateShoppingListHandler := connect.NewUnaryHandler(
		DepotServiceCreateShoppingListProcedure,
		svc.CreateShoppingList,
		connect.WithSchema(depotServiceCreateShoppingListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	depotServiceCancelShoppingListHandler := connect.NewUnaryHandler(
		DepotServiceCancelShoppingListProcedure,
		svc.CancelShoppingList,
		connect.WithSchema(depotServiceCancelShoppingListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	depotServiceAssignShoppingListHandler := connect.NewUnaryHandler(
		DepotServiceAssignShoppingListProcedure,
		svc.AssignShoppingList,
		connect.WithSchema(depotServiceAssignShoppingListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	depotServiceCompleteShoppingListHandler := connect.NewUnaryHandler(
		DepotServiceCompleteShoppingListProcedure,
		svc.CompleteShoppingList,
		connect.WithSchema(depotServiceCompleteShoppingListMethodDescriptor),
		connect.WithHandlerOptions(opts...),
	)
	return "/depotpb.DepotService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DepotServiceCreateShoppingListProcedure:
			depotServiceCreateShoppingListHandler.ServeHTTP(w, r)
		case DepotServiceCancelShoppingListProcedure:
			depotServiceCancelShoppingListHandler.ServeHTTP(w, r)
		case DepotServiceAssignShoppingListProcedure:
			depotServiceAssignShoppingListHandler.ServeHTTP(w, r)
		case DepotServiceCompleteShoppingListProcedure:
			depotServiceCompleteShoppingListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDepotServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDepotServiceHandler struct{}

func (UnimplementedDepotServiceHandler) CreateShoppingList(context.Context, *connect.Request[depotpb.CreateShoppingListRequest]) (*connect.Response[depotpb.CreateShoppingListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depotpb.DepotService.CreateShoppingList is not implemented"))
}

func (UnimplementedDepotServiceHandler) CancelShoppingList(context.Context, *connect.Request[depotpb.CancelShoppingListRequest]) (*connect.Response[depotpb.CancelShoppingListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depotpb.DepotService.CancelShoppingList is not implemented"))
}

func (UnimplementedDepotServiceHandler) AssignShoppingList(context.Context, *connect.Request[depotpb.AssignShoppingListRequest]) (*connect.Response[depotpb.AssignShoppingListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depotpb.DepotService.AssignShoppingList is not implemented"))
}

func (UnimplementedDepotServiceHandler) CompleteShoppingList(context.Context, *connect.Request[depotpb.CompleteShoppingListRequest]) (*connect.Response[depotpb.CompleteShoppingListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("depotpb.DepotService.CompleteShoppingList is not implemented"))
}
