// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.ts"
// @generated from file orderingpb/api.proto (package orderingpb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { CancelOrderRequest, CancelOrderResponse, CompleteOrderRequest, CompleteOrderResponse, CreateOrderRequest, CreateOrderResponse, GetOrderRequest, GetOrderResponse, ReadyOrderRequest, ReadyOrderResponse } from "./api_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service orderingpb.OrderingService
 */
export const OrderingService = {
  typeName: "orderingpb.OrderingService",
  methods: {
    /**
     * @generated from rpc orderingpb.OrderingService.CreateOrder
     */
    createOrder: {
      name: "CreateOrder",
      I: CreateOrderRequest,
      O: CreateOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc orderingpb.OrderingService.GetOrder
     */
    getOrder: {
      name: "GetOrder",
      I: GetOrderRequest,
      O: GetOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc orderingpb.OrderingService.CancelOrder
     */
    cancelOrder: {
      name: "CancelOrder",
      I: CancelOrderRequest,
      O: CancelOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc orderingpb.OrderingService.ReadyOrder
     */
    readyOrder: {
      name: "ReadyOrder",
      I: ReadyOrderRequest,
      O: ReadyOrderResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc orderingpb.OrderingService.CompleteOrder
     */
    completeOrder: {
      name: "CompleteOrder",
      I: CompleteOrderRequest,
      O: CompleteOrderResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

