// Code generated by mockery. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockProductRepository is an autogenerated mock type for the ProductRepository type
type MockProductRepository struct {
	mock.Mock
}

type MockProductRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProductRepository) EXPECT() *MockProductRepository_Expecter {
	return &MockProductRepository_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with given fields: ctx, id
func (_m *MockProductRepository) Load(ctx context.Context, id string) (*Product, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Product, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Product); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProductRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockProductRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProductRepository_Expecter) Load(ctx interface{}, id interface{}) *MockProductRepository_Load_Call {
	return &MockProductRepository_Load_Call{Call: _e.mock.On("Load", ctx, id)}
}

func (_c *MockProductRepository_Load_Call) Run(run func(ctx context.Context, id string)) *MockProductRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProductRepository_Load_Call) Return(_a0 *Product, _a1 error) *MockProductRepository_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProductRepository_Load_Call) RunAndReturn(run func(context.Context, string) (*Product, error)) *MockProductRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, product
func (_m *MockProductRepository) Save(ctx context.Context, product *Product) error {
	ret := _m.Called(ctx, product)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Product) error); ok {
		r0 = rf(ctx, product)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProductRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockProductRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - product *Product
func (_e *MockProductRepository_Expecter) Save(ctx interface{}, product interface{}) *MockProductRepository_Save_Call {
	return &MockProductRepository_Save_Call{Call: _e.mock.On("Save", ctx, product)}
}

func (_c *MockProductRepository_Save_Call) Run(run func(ctx context.Context, product *Product)) *MockProductRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Product))
	})
	return _c
}

func (_c *MockProductRepository_Save_Call) Return(_a0 error) *MockProductRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProductRepository_Save_Call) RunAndReturn(run func(context.Context, *Product) error) *MockProductRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProductRepository creates a new instance of MockProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProductRepository {
	mock := &MockProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
