// Code generated by mockery. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockStoreRepository is an autogenerated mock type for the StoreRepository type
type MockStoreRepository struct {
	mock.Mock
}

type MockStoreRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStoreRepository) EXPECT() *MockStoreRepository_Expecter {
	return &MockStoreRepository_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with given fields: ctx, storeID
func (_m *MockStoreRepository) Load(ctx context.Context, storeID string) (*Store, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *Store
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Store, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Store); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Store)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStoreRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockStoreRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - storeID string
func (_e *MockStoreRepository_Expecter) Load(ctx interface{}, storeID interface{}) *MockStoreRepository_Load_Call {
	return &MockStoreRepository_Load_Call{Call: _e.mock.On("Load", ctx, storeID)}
}

func (_c *MockStoreRepository_Load_Call) Run(run func(ctx context.Context, storeID string)) *MockStoreRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockStoreRepository_Load_Call) Return(_a0 *Store, _a1 error) *MockStoreRepository_Load_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStoreRepository_Load_Call) RunAndReturn(run func(context.Context, string) (*Store, error)) *MockStoreRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, store
func (_m *MockStoreRepository) Save(ctx context.Context, store *Store) error {
	ret := _m.Called(ctx, store)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Store) error); ok {
		r0 = rf(ctx, store)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStoreRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockStoreRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - store *Store
func (_e *MockStoreRepository_Expecter) Save(ctx interface{}, store interface{}) *MockStoreRepository_Save_Call {
	return &MockStoreRepository_Save_Call{Call: _e.mock.On("Save", ctx, store)}
}

func (_c *MockStoreRepository_Save_Call) Run(run func(ctx context.Context, store *Store)) *MockStoreRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Store))
	})
	return _c
}

func (_c *MockStoreRepository_Save_Call) Return(_a0 error) *MockStoreRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStoreRepository_Save_Call) RunAndReturn(run func(context.Context, *Store) error) *MockStoreRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStoreRepository creates a new instance of MockStoreRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStoreRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStoreRepository {
	mock := &MockStoreRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
