// Code generated by mockery. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCatalogRepository is an autogenerated mock type for the CatalogRepository type
type MockCatalogRepository struct {
	mock.Mock
}

type MockCatalogRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCatalogRepository) EXPECT() *MockCatalogRepository_Expecter {
	return &MockCatalogRepository_Expecter{mock: &_m.Mock}
}

// AddProduct provides a mock function with given fields: ctx, productID, storeID, name, description, sku, price
func (_m *MockCatalogRepository) AddProduct(ctx context.Context, productID string, storeID string, name string, description string, sku string, price float64) error {
	ret := _m.Called(ctx, productID, storeID, name, description, sku, price)

	if len(ret) == 0 {
		panic("no return value specified for AddProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, float64) error); ok {
		r0 = rf(ctx, productID, storeID, name, description, sku, price)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCatalogRepository_AddProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProduct'
type MockCatalogRepository_AddProduct_Call struct {
	*mock.Call
}

// AddProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
//   - storeID string
//   - name string
//   - description string
//   - sku string
//   - price float64
func (_e *MockCatalogRepository_Expecter) AddProduct(ctx interface{}, productID interface{}, storeID interface{}, name interface{}, description interface{}, sku interface{}, price interface{}) *MockCatalogRepository_AddProduct_Call {
	return &MockCatalogRepository_AddProduct_Call{Call: _e.mock.On("AddProduct", ctx, productID, storeID, name, description, sku, price)}
}

func (_c *MockCatalogRepository_AddProduct_Call) Run(run func(ctx context.Context, productID string, storeID string, name string, description string, sku string, price float64)) *MockCatalogRepository_AddProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].(string), args[5].(string), args[6].(float64))
	})
	return _c
}

func (_c *MockCatalogRepository_AddProduct_Call) Return(_a0 error) *MockCatalogRepository_AddProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCatalogRepository_AddProduct_Call) RunAndReturn(run func(context.Context, string, string, string, string, string, float64) error) *MockCatalogRepository_AddProduct_Call {
	_c.Call.Return(run)
	return _c
}

// Find provides a mock function with given fields: ctx, productID
func (_m *MockCatalogRepository) Find(ctx context.Context, productID string) (*CatalogProduct, error) {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *CatalogProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*CatalogProduct, error)); ok {
		return rf(ctx, productID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *CatalogProduct); ok {
		r0 = rf(ctx, productID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CatalogProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, productID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockCatalogRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
func (_e *MockCatalogRepository_Expecter) Find(ctx interface{}, productID interface{}) *MockCatalogRepository_Find_Call {
	return &MockCatalogRepository_Find_Call{Call: _e.mock.On("Find", ctx, productID)}
}

func (_c *MockCatalogRepository_Find_Call) Run(run func(ctx context.Context, productID string)) *MockCatalogRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCatalogRepository_Find_Call) Return(_a0 *CatalogProduct, _a1 error) *MockCatalogRepository_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_Find_Call) RunAndReturn(run func(context.Context, string) (*CatalogProduct, error)) *MockCatalogRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// GetCatalog provides a mock function with given fields: ctx, storeID
func (_m *MockCatalogRepository) GetCatalog(ctx context.Context, storeID string) ([]*CatalogProduct, error) {
	ret := _m.Called(ctx, storeID)

	if len(ret) == 0 {
		panic("no return value specified for GetCatalog")
	}

	var r0 []*CatalogProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*CatalogProduct, error)); ok {
		return rf(ctx, storeID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*CatalogProduct); ok {
		r0 = rf(ctx, storeID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*CatalogProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, storeID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCatalogRepository_GetCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCatalog'
type MockCatalogRepository_GetCatalog_Call struct {
	*mock.Call
}

// GetCatalog is a helper method to define mock.On call
//   - ctx context.Context
//   - storeID string
func (_e *MockCatalogRepository_Expecter) GetCatalog(ctx interface{}, storeID interface{}) *MockCatalogRepository_GetCatalog_Call {
	return &MockCatalogRepository_GetCatalog_Call{Call: _e.mock.On("GetCatalog", ctx, storeID)}
}

func (_c *MockCatalogRepository_GetCatalog_Call) Run(run func(ctx context.Context, storeID string)) *MockCatalogRepository_GetCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCatalogRepository_GetCatalog_Call) Return(_a0 []*CatalogProduct, _a1 error) *MockCatalogRepository_GetCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCatalogRepository_GetCatalog_Call) RunAndReturn(run func(context.Context, string) ([]*CatalogProduct, error)) *MockCatalogRepository_GetCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// Rebrand provides a mock function with given fields: ctx, productID, name, description
func (_m *MockCatalogRepository) Rebrand(ctx context.Context, productID string, name string, description string) error {
	ret := _m.Called(ctx, productID, name, description)

	if len(ret) == 0 {
		panic("no return value specified for Rebrand")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) error); ok {
		r0 = rf(ctx, productID, name, description)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCatalogRepository_Rebrand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rebrand'
type MockCatalogRepository_Rebrand_Call struct {
	*mock.Call
}

// Rebrand is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
//   - name string
//   - description string
func (_e *MockCatalogRepository_Expecter) Rebrand(ctx interface{}, productID interface{}, name interface{}, description interface{}) *MockCatalogRepository_Rebrand_Call {
	return &MockCatalogRepository_Rebrand_Call{Call: _e.mock.On("Rebrand", ctx, productID, name, description)}
}

func (_c *MockCatalogRepository_Rebrand_Call) Run(run func(ctx context.Context, productID string, name string, description string)) *MockCatalogRepository_Rebrand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string))
	})
	return _c
}

func (_c *MockCatalogRepository_Rebrand_Call) Return(_a0 error) *MockCatalogRepository_Rebrand_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCatalogRepository_Rebrand_Call) RunAndReturn(run func(context.Context, string, string, string) error) *MockCatalogRepository_Rebrand_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveProduct provides a mock function with given fields: ctx, productID
func (_m *MockCatalogRepository) RemoveProduct(ctx context.Context, productID string) error {
	ret := _m.Called(ctx, productID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, productID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCatalogRepository_RemoveProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveProduct'
type MockCatalogRepository_RemoveProduct_Call struct {
	*mock.Call
}

// RemoveProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
func (_e *MockCatalogRepository_Expecter) RemoveProduct(ctx interface{}, productID interface{}) *MockCatalogRepository_RemoveProduct_Call {
	return &MockCatalogRepository_RemoveProduct_Call{Call: _e.mock.On("RemoveProduct", ctx, productID)}
}

func (_c *MockCatalogRepository_RemoveProduct_Call) Run(run func(ctx context.Context, productID string)) *MockCatalogRepository_RemoveProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCatalogRepository_RemoveProduct_Call) Return(_a0 error) *MockCatalogRepository_RemoveProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCatalogRepository_RemoveProduct_Call) RunAndReturn(run func(context.Context, string) error) *MockCatalogRepository_RemoveProduct_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePrice provides a mock function with given fields: ctx, productID, delta
func (_m *MockCatalogRepository) UpdatePrice(ctx context.Context, productID string, delta float64) error {
	ret := _m.Called(ctx, productID, delta)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePrice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, float64) error); ok {
		r0 = rf(ctx, productID, delta)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCatalogRepository_UpdatePrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePrice'
type MockCatalogRepository_UpdatePrice_Call struct {
	*mock.Call
}

// UpdatePrice is a helper method to define mock.On call
//   - ctx context.Context
//   - productID string
//   - delta float64
func (_e *MockCatalogRepository_Expecter) UpdatePrice(ctx interface{}, productID interface{}, delta interface{}) *MockCatalogRepository_UpdatePrice_Call {
	return &MockCatalogRepository_UpdatePrice_Call{Call: _e.mock.On("UpdatePrice", ctx, productID, delta)}
}

func (_c *MockCatalogRepository_UpdatePrice_Call) Run(run func(ctx context.Context, productID string, delta float64)) *MockCatalogRepository_UpdatePrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(float64))
	})
	return _c
}

func (_c *MockCatalogRepository_UpdatePrice_Call) Return(_a0 error) *MockCatalogRepository_UpdatePrice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCatalogRepository_UpdatePrice_Call) RunAndReturn(run func(context.Context, string, float64) error) *MockCatalogRepository_UpdatePrice_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCatalogRepository creates a new instance of MockCatalogRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCatalogRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCatalogRepository {
	mock := &MockCatalogRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
