// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.ts"
// @generated from file searchpb/api.proto (package searchpb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { GetOrderRequest, GetOrderResponse, SearchOrdersRequest, SearchOrdersResponse } from "./api_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service searchpb.SearchService
 */
export const SearchService = {
  typeName: "searchpb.SearchService",
  methods: {
    /**
     * @generated from rpc searchpb.SearchService.SearchOrders
     */
    searchOrders: {
      name: "SearchOrders",
      I: SearchOrdersRequest,
      O: SearchOrdersResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc searchpb.SearchService.GetOrder
     */
    getOrder: {
      name: "GetOrder",
      I: GetOrderRequest,
      O: GetOrderResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

