// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=.ts"
// @generated from file searchpb/api.proto (package searchpb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file searchpb/api.proto.
 */
export const file_searchpb_api: GenFile = /*@__PURE__*/
  fileDesc("ChJzZWFyY2hwYi9hcGkucHJvdG8SCHNlYXJjaHBiIoICCgVPcmRlchIQCghvcmRlcl9pZBgBIAEoCRITCgtjdXN0b21lcl9pZBgCIAEoCRIVCg1jdXN0b21lcl9uYW1lGAMgASgJEiMKBWl0ZW1zGAQgAygLMhQuc2VhcmNocGIuT3JkZXIuSXRlbRINCgV0b3RhbBgFIAEoARIOCgZzdGF0dXMYBiABKAkadwoESXRlbRISCgpwcm9kdWN0X2lkGAEgASgJEhAKCHN0b3JlX2lkGAIgASgJEhQKDHByb2R1Y3RfbmFtZRgDIAEoCRISCgpzdG9yZV9uYW1lGAQgASgJEg0KBXByaWNlGAUgASgBEhAKCHF1YW50aXR5GAYgASgDIsACChNTZWFyY2hPcmRlcnNSZXF1ZXN0EjYKB2ZpbHRlcnMYASABKAsyJS5zZWFyY2hwYi5TZWFyY2hPcmRlcnNSZXF1ZXN0LkZpbHRlcnMSDAoEbmV4dBgCIAEoCRINCgVsaW1pdBgDIAEoBRrTAQoHRmlsdGVycxITCgtjdXN0b21lcl9pZBgBIAEoCRIpCgVhZnRlchgCIAEoCzIaLmdvb2dsZS5wcm90b2J1Zi5UaW1lc3RhbXASKgoGYmVmb3JlGAMgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIRCglzdG9yZV9pZHMYBCADKAkSEwoLcHJvZHVjdF9pZHMYBSADKAkSEQoJbWluX3RvdGFsGAYgASgBEhEKCW1heF90b3RhbBgHIAEoARIOCgZzdGF0dXMYCCABKAkiRQoUU2VhcmNoT3JkZXJzUmVzcG9uc2USHwoGb3JkZXJzGAEgAygLMg8uc2VhcmNocGIuT3JkZXISDAoEbmV4dBgCIAEoCSIdCg9HZXRPcmRlclJlcXVlc3QSCgoCaWQYASABKAkiMgoQR2V0T3JkZXJSZXNwb25zZRIeCgVvcmRlchgBIAEoCzIPLnNlYXJjaHBiLk9yZGVyMqUBCg1TZWFyY2hTZXJ2aWNlEk8KDFNlYXJjaE9yZGVycxIdLnNlYXJjaHBiLlNlYXJjaE9yZGVyc1JlcXVlc3QaHi5zZWFyY2hwYi5TZWFyY2hPcmRlcnNSZXNwb25zZSIAEkMKCEdldE9yZGVyEhkuc2VhcmNocGIuR2V0T3JkZXJSZXF1ZXN0Ghouc2VhcmNocGIuR2V0T3JkZXJSZXNwb25zZSIAQpEBCgxjb20uc2VhcmNocGJCCEFwaVByb3RvUAFaN2dpdGh1Yi5jb20vb3dlenp5L3Nva28tYm9yYS1tbmd0LXN5c3RlbS9zZWFyY2gvc2VhcmNocGKiAgNTWFiqAghTZWFyY2hwYsoCCFNlYXJjaHBi4gIUU2VhcmNocGJcR1BCTWV0YWRhdGHqAghTZWFyY2hwYmIGcHJvdG8z", [file_google_protobuf_timestamp]);

/**
 * @generated from message searchpb.Order
 */
export type Order = Message<"searchpb.Order"> & {
  /**
   * @generated from field: string order_id = 1;
   */
  orderId: string;

  /**
   * @generated from field: string customer_id = 2;
   */
  customerId: string;

  /**
   * @generated from field: string customer_name = 3;
   */
  customerName: string;

  /**
   * @generated from field: repeated searchpb.Order.Item items = 4;
   */
  items: Order_Item[];

  /**
   * @generated from field: double total = 5;
   */
  total: number;

  /**
   * @generated from field: string status = 6;
   */
  status: string;
};

/**
 * Describes the message searchpb.Order.
 * Use `create(OrderSchema)` to create a new message.
 */
export const OrderSchema: GenMessage<Order> = /*@__PURE__*/
  messageDesc(file_searchpb_api, 0);

/**
 * @generated from message searchpb.Order.Item
 */
export type Order_Item = Message<"searchpb.Order.Item"> & {
  /**
   * @generated from field: string product_id = 1;
   */
  productId: string;

  /**
   * @generated from field: string store_id = 2;
   */
  storeId: string;

  /**
   * @generated from field: string product_name = 3;
   */
  productName: string;

  /**
   * @generated from field: string store_name = 4;
   */
  storeName: string;

  /**
   * @generated from field: double price = 5;
   */
  price: number;

  /**
   * @generated from field: int64 quantity = 6;
   */
  quantity: bigint;
};

/**
 * Describes the message searchpb.Order.Item.
 * Use `create(Order_ItemSchema)` to create a new message.
 */
export const Order_ItemSchema: GenMessage<Order_Item> = /*@__PURE__*/
  messageDesc(file_searchpb_api, 0, 0);

/**
 * @generated from message searchpb.SearchOrdersRequest
 */
export type SearchOrdersRequest = Message<"searchpb.SearchOrdersRequest"> & {
  /**
   * @generated from field: searchpb.SearchOrdersRequest.Filters filters = 1;
   */
  filters?: SearchOrdersRequest_Filters;

  /**
   * @generated from field: string next = 2;
   */
  next: string;

  /**
   * @generated from field: int32 limit = 3;
   */
  limit: number;
};

/**
 * Describes the message searchpb.SearchOrdersRequest.
 * Use `create(SearchOrdersRequestSchema)` to create a new message.
 */
export const SearchOrdersRequestSchema: GenMessage<SearchOrdersRequest> = /*@__PURE__*/
  messageDesc(file_searchpb_api, 1);

/**
 * @generated from message searchpb.SearchOrdersRequest.Filters
 */
export type SearchOrdersRequest_Filters = Message<"searchpb.SearchOrdersRequest.Filters"> & {
  /**
   * @generated from field: string customer_id = 1;
   */
  customerId: string;

  /**
   * @generated from field: google.protobuf.Timestamp after = 2;
   */
  after?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp before = 3;
   */
  before?: Timestamp;

  /**
   * @generated from field: repeated string store_ids = 4;
   */
  storeIds: string[];

  /**
   * @generated from field: repeated string product_ids = 5;
   */
  productIds: string[];

  /**
   * @generated from field: double min_total = 6;
   */
  minTotal: number;

  /**
   * @generated from field: double max_total = 7;
   */
  maxTotal: number;

  /**
   * @generated from field: string status = 8;
   */
  status: string;
};

/**
 * Describes the message searchpb.SearchOrdersRequest.Filters.
 * Use `create(SearchOrdersRequest_FiltersSchema)` to create a new message.
 */
export const SearchOrdersRequest_FiltersSchema: GenMessage<SearchOrdersRequest_Filters> = /*@__PURE__*/
  messageDesc(file_searchpb_api, 1, 0);

/**
 * @generated from message searchpb.SearchOrdersResponse
 */
export type SearchOrdersResponse = Message<"searchpb.SearchOrdersResponse"> & {
  /**
   * @generated from field: repeated searchpb.Order orders = 1;
   */
  orders: Order[];

  /**
   * @generated from field: string next = 2;
   */
  next: string;
};

/**
 * Describes the message searchpb.SearchOrdersResponse.
 * Use `create(SearchOrdersResponseSchema)` to create a new message.
 */
export const SearchOrdersResponseSchema: GenMessage<SearchOrdersResponse> = /*@__PURE__*/
  messageDesc(file_searchpb_api, 2);

/**
 * @generated from message searchpb.GetOrderRequest
 */
export type GetOrderRequest = Message<"searchpb.GetOrderRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message searchpb.GetOrderRequest.
 * Use `create(GetOrderRequestSchema)` to create a new message.
 */
export const GetOrderRequestSchema: GenMessage<GetOrderRequest> = /*@__PURE__*/
  messageDesc(file_searchpb_api, 3);

/**
 * @generated from message searchpb.GetOrderResponse
 */
export type GetOrderResponse = Message<"searchpb.GetOrderResponse"> & {
  /**
   * @generated from field: searchpb.Order order = 1;
   */
  order?: Order;
};

/**
 * Describes the message searchpb.GetOrderResponse.
 * Use `create(GetOrderResponseSchema)` to create a new message.
 */
export const GetOrderResponseSchema: GenMessage<GetOrderResponse> = /*@__PURE__*/
  messageDesc(file_searchpb_api, 4);

/**
 * @generated from service searchpb.SearchService
 */
export const SearchService: GenService<{
  /**
   * @generated from rpc searchpb.SearchService.SearchOrders
   */
  searchOrders: {
    methodKind: "unary";
    input: typeof SearchOrdersRequestSchema;
    output: typeof SearchOrdersResponseSchema;
  },
  /**
   * @generated from rpc searchpb.SearchService.GetOrder
   */
  getOrder: {
    methodKind: "unary";
    input: typeof GetOrderRequestSchema;
    output: typeof GetOrderResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_searchpb_api, 0);

