// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"

	models "github.com/owezzy/soko-bora-mngt-system/payments/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// MockInvoiceRepository is an autogenerated mock type for the InvoiceRepository type
type MockInvoiceRepository struct {
	mock.Mock
}

type MockInvoiceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInvoiceRepository) EXPECT() *MockInvoiceRepository_Expecter {
	return &MockInvoiceRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function with given fields: ctx, invoiceID
func (_m *MockInvoiceRepository) Find(ctx context.Context, invoiceID string) (*models.Invoice, error) {
	ret := _m.Called(ctx, invoiceID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *models.Invoice
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*models.Invoice, error)); ok {
		return rf(ctx, invoiceID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *models.Invoice); ok {
		r0 = rf(ctx, invoiceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.Invoice)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, invoiceID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockInvoiceRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockInvoiceRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - invoiceID string
func (_e *MockInvoiceRepository_Expecter) Find(ctx interface{}, invoiceID interface{}) *MockInvoiceRepository_Find_Call {
	return &MockInvoiceRepository_Find_Call{Call: _e.mock.On("Find", ctx, invoiceID)}
}

func (_c *MockInvoiceRepository_Find_Call) Run(run func(ctx context.Context, invoiceID string)) *MockInvoiceRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockInvoiceRepository_Find_Call) Return(_a0 *models.Invoice, _a1 error) *MockInvoiceRepository_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockInvoiceRepository_Find_Call) RunAndReturn(run func(context.Context, string) (*models.Invoice, error)) *MockInvoiceRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, invoice
func (_m *MockInvoiceRepository) Save(ctx context.Context, invoice *models.Invoice) error {
	ret := _m.Called(ctx, invoice)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Invoice) error); ok {
		r0 = rf(ctx, invoice)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInvoiceRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockInvoiceRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - invoice *models.Invoice
func (_e *MockInvoiceRepository_Expecter) Save(ctx interface{}, invoice interface{}) *MockInvoiceRepository_Save_Call {
	return &MockInvoiceRepository_Save_Call{Call: _e.mock.On("Save", ctx, invoice)}
}

func (_c *MockInvoiceRepository_Save_Call) Run(run func(ctx context.Context, invoice *models.Invoice)) *MockInvoiceRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Invoice))
	})
	return _c
}

func (_c *MockInvoiceRepository_Save_Call) Return(_a0 error) *MockInvoiceRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInvoiceRepository_Save_Call) RunAndReturn(run func(context.Context, *models.Invoice) error) *MockInvoiceRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, invoice
func (_m *MockInvoiceRepository) Update(ctx context.Context, invoice *models.Invoice) error {
	ret := _m.Called(ctx, invoice)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *models.Invoice) error); ok {
		r0 = rf(ctx, invoice)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockInvoiceRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockInvoiceRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - invoice *models.Invoice
func (_e *MockInvoiceRepository_Expecter) Update(ctx interface{}, invoice interface{}) *MockInvoiceRepository_Update_Call {
	return &MockInvoiceRepository_Update_Call{Call: _e.mock.On("Update", ctx, invoice)}
}

func (_c *MockInvoiceRepository_Update_Call) Run(run func(ctx context.Context, invoice *models.Invoice)) *MockInvoiceRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*models.Invoice))
	})
	return _c
}

func (_c *MockInvoiceRepository_Update_Call) Return(_a0 error) *MockInvoiceRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockInvoiceRepository_Update_Call) RunAndReturn(run func(context.Context, *models.Invoice) error) *MockInvoiceRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockInvoiceRepository creates a new instance of MockInvoiceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInvoiceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInvoiceRepository {
	mock := &MockInvoiceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
