// Code generated by mockery. DO NOT EDIT.

package orderingpb

import mock "github.com/stretchr/testify/mock"

// MockUnsafeOrderingServiceServer is an autogenerated mock type for the UnsafeOrderingServiceServer type
type MockUnsafeOrderingServiceServer struct {
	mock.Mock
}

type MockUnsafeOrderingServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnsafeOrderingServiceServer) EXPECT() *MockUnsafeOrderingServiceServer_Expecter {
	return &MockUnsafeOrderingServiceServer_Expecter{mock: &_m.Mock}
}

// mustEmbedUnimplementedOrderingServiceServer provides a mock function with no fields
func (_m *MockUnsafeOrderingServiceServer) mustEmbedUnimplementedOrderingServiceServer() {
	_m.Called()
}

// MockUnsafeOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedOrderingServiceServer'
type MockUnsafeOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedOrderingServiceServer is a helper method to define mock.On call
func (_e *MockUnsafeOrderingServiceServer_Expecter) mustEmbedUnimplementedOrderingServiceServer() *MockUnsafeOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call {
	return &MockUnsafeOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedOrderingServiceServer")}
}

func (_c *MockUnsafeOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call) Run(run func()) *MockUnsafeOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnsafeOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call) Return() *MockUnsafeOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUnsafeOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call) RunAndReturn(run func()) *MockUnsafeOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockUnsafeOrderingServiceServer creates a new instance of MockUnsafeOrderingServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnsafeOrderingServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnsafeOrderingServiceServer {
	mock := &MockUnsafeOrderingServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
