// Code generated by mockery. DO NOT EDIT.

package orderingpb

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderingServiceServer is an autogenerated mock type for the OrderingServiceServer type
type MockOrderingServiceServer struct {
	mock.Mock
}

type MockOrderingServiceServer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderingServiceServer) EXPECT() *MockOrderingServiceServer_Expecter {
	return &MockOrderingServiceServer_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: _a0, _a1
func (_m *MockOrderingServiceServer) CancelOrder(_a0 context.Context, _a1 *CancelOrderRequest) (*CancelOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 *CancelOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *CancelOrderRequest) *CancelOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CancelOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *CancelOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderingServiceServer_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type MockOrderingServiceServer_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *CancelOrderRequest
func (_e *MockOrderingServiceServer_Expecter) CancelOrder(_a0 interface{}, _a1 interface{}) *MockOrderingServiceServer_CancelOrder_Call {
	return &MockOrderingServiceServer_CancelOrder_Call{Call: _e.mock.On("CancelOrder", _a0, _a1)}
}

func (_c *MockOrderingServiceServer_CancelOrder_Call) Run(run func(_a0 context.Context, _a1 *CancelOrderRequest)) *MockOrderingServiceServer_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*CancelOrderRequest))
	})
	return _c
}

func (_c *MockOrderingServiceServer_CancelOrder_Call) Return(_a0 *CancelOrderResponse, _a1 error) *MockOrderingServiceServer_CancelOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderingServiceServer_CancelOrder_Call) RunAndReturn(run func(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)) *MockOrderingServiceServer_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteOrder provides a mock function with given fields: _a0, _a1
func (_m *MockOrderingServiceServer) CompleteOrder(_a0 context.Context, _a1 *CompleteOrderRequest) (*CompleteOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CompleteOrder")
	}

	var r0 *CompleteOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *CompleteOrderRequest) (*CompleteOrderResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *CompleteOrderRequest) *CompleteOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CompleteOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *CompleteOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderingServiceServer_CompleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteOrder'
type MockOrderingServiceServer_CompleteOrder_Call struct {
	*mock.Call
}

// CompleteOrder is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *CompleteOrderRequest
func (_e *MockOrderingServiceServer_Expecter) CompleteOrder(_a0 interface{}, _a1 interface{}) *MockOrderingServiceServer_CompleteOrder_Call {
	return &MockOrderingServiceServer_CompleteOrder_Call{Call: _e.mock.On("CompleteOrder", _a0, _a1)}
}

func (_c *MockOrderingServiceServer_CompleteOrder_Call) Run(run func(_a0 context.Context, _a1 *CompleteOrderRequest)) *MockOrderingServiceServer_CompleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*CompleteOrderRequest))
	})
	return _c
}

func (_c *MockOrderingServiceServer_CompleteOrder_Call) Return(_a0 *CompleteOrderResponse, _a1 error) *MockOrderingServiceServer_CompleteOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderingServiceServer_CompleteOrder_Call) RunAndReturn(run func(context.Context, *CompleteOrderRequest) (*CompleteOrderResponse, error)) *MockOrderingServiceServer_CompleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: _a0, _a1
func (_m *MockOrderingServiceServer) CreateOrder(_a0 context.Context, _a1 *CreateOrderRequest) (*CreateOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *CreateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *CreateOrderRequest) *CreateOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CreateOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *CreateOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderingServiceServer_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderingServiceServer_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *CreateOrderRequest
func (_e *MockOrderingServiceServer_Expecter) CreateOrder(_a0 interface{}, _a1 interface{}) *MockOrderingServiceServer_CreateOrder_Call {
	return &MockOrderingServiceServer_CreateOrder_Call{Call: _e.mock.On("CreateOrder", _a0, _a1)}
}

func (_c *MockOrderingServiceServer_CreateOrder_Call) Run(run func(_a0 context.Context, _a1 *CreateOrderRequest)) *MockOrderingServiceServer_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*CreateOrderRequest))
	})
	return _c
}

func (_c *MockOrderingServiceServer_CreateOrder_Call) Return(_a0 *CreateOrderResponse, _a1 error) *MockOrderingServiceServer_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderingServiceServer_CreateOrder_Call) RunAndReturn(run func(context.Context, *CreateOrderRequest) (*CreateOrderResponse, error)) *MockOrderingServiceServer_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: _a0, _a1
func (_m *MockOrderingServiceServer) GetOrder(_a0 context.Context, _a1 *GetOrderRequest) (*GetOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *GetOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetOrderRequest) (*GetOrderResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetOrderRequest) *GetOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderingServiceServer_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderingServiceServer_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *GetOrderRequest
func (_e *MockOrderingServiceServer_Expecter) GetOrder(_a0 interface{}, _a1 interface{}) *MockOrderingServiceServer_GetOrder_Call {
	return &MockOrderingServiceServer_GetOrder_Call{Call: _e.mock.On("GetOrder", _a0, _a1)}
}

func (_c *MockOrderingServiceServer_GetOrder_Call) Run(run func(_a0 context.Context, _a1 *GetOrderRequest)) *MockOrderingServiceServer_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*GetOrderRequest))
	})
	return _c
}

func (_c *MockOrderingServiceServer_GetOrder_Call) Return(_a0 *GetOrderResponse, _a1 error) *MockOrderingServiceServer_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderingServiceServer_GetOrder_Call) RunAndReturn(run func(context.Context, *GetOrderRequest) (*GetOrderResponse, error)) *MockOrderingServiceServer_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// ReadyOrder provides a mock function with given fields: _a0, _a1
func (_m *MockOrderingServiceServer) ReadyOrder(_a0 context.Context, _a1 *ReadyOrderRequest) (*ReadyOrderResponse, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for ReadyOrder")
	}

	var r0 *ReadyOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ReadyOrderRequest) (*ReadyOrderResponse, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ReadyOrderRequest) *ReadyOrderResponse); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ReadyOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ReadyOrderRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderingServiceServer_ReadyOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadyOrder'
type MockOrderingServiceServer_ReadyOrder_Call struct {
	*mock.Call
}

// ReadyOrder is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 *ReadyOrderRequest
func (_e *MockOrderingServiceServer_Expecter) ReadyOrder(_a0 interface{}, _a1 interface{}) *MockOrderingServiceServer_ReadyOrder_Call {
	return &MockOrderingServiceServer_ReadyOrder_Call{Call: _e.mock.On("ReadyOrder", _a0, _a1)}
}

func (_c *MockOrderingServiceServer_ReadyOrder_Call) Run(run func(_a0 context.Context, _a1 *ReadyOrderRequest)) *MockOrderingServiceServer_ReadyOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*ReadyOrderRequest))
	})
	return _c
}

func (_c *MockOrderingServiceServer_ReadyOrder_Call) Return(_a0 *ReadyOrderResponse, _a1 error) *MockOrderingServiceServer_ReadyOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderingServiceServer_ReadyOrder_Call) RunAndReturn(run func(context.Context, *ReadyOrderRequest) (*ReadyOrderResponse, error)) *MockOrderingServiceServer_ReadyOrder_Call {
	_c.Call.Return(run)
	return _c
}

// mustEmbedUnimplementedOrderingServiceServer provides a mock function with no fields
func (_m *MockOrderingServiceServer) mustEmbedUnimplementedOrderingServiceServer() {
	_m.Called()
}

// MockOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'mustEmbedUnimplementedOrderingServiceServer'
type MockOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call struct {
	*mock.Call
}

// mustEmbedUnimplementedOrderingServiceServer is a helper method to define mock.On call
func (_e *MockOrderingServiceServer_Expecter) mustEmbedUnimplementedOrderingServiceServer() *MockOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call {
	return &MockOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call{Call: _e.mock.On("mustEmbedUnimplementedOrderingServiceServer")}
}

func (_c *MockOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call) Run(run func()) *MockOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call) Return() *MockOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call) RunAndReturn(run func()) *MockOrderingServiceServer_mustEmbedUnimplementedOrderingServiceServer_Call {
	_c.Run(run)
	return _c
}

// NewMockOrderingServiceServer creates a new instance of MockOrderingServiceServer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderingServiceServer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderingServiceServer {
	mock := &MockOrderingServiceServer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
