// Code generated by mockery. DO NOT EDIT.

package orderingpb

import (
	context "context"

	grpc "google.golang.org/grpc"

	mock "github.com/stretchr/testify/mock"
)

// MockOrderingServiceClient is an autogenerated mock type for the OrderingServiceClient type
type MockOrderingServiceClient struct {
	mock.Mock
}

type MockOrderingServiceClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrderingServiceClient) EXPECT() *MockOrderingServiceClient_Expecter {
	return &MockOrderingServiceClient_Expecter{mock: &_m.Mock}
}

// CancelOrder provides a mock function with given fields: ctx, in, opts
func (_m *MockOrderingServiceClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CancelOrder")
	}

	var r0 *CancelOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *CancelOrderRequest, ...grpc.CallOption) (*CancelOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *CancelOrderRequest, ...grpc.CallOption) *CancelOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CancelOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *CancelOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderingServiceClient_CancelOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CancelOrder'
type MockOrderingServiceClient_CancelOrder_Call struct {
	*mock.Call
}

// CancelOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *CancelOrderRequest
//   - opts ...grpc.CallOption
func (_e *MockOrderingServiceClient_Expecter) CancelOrder(ctx interface{}, in interface{}, opts ...interface{}) *MockOrderingServiceClient_CancelOrder_Call {
	return &MockOrderingServiceClient_CancelOrder_Call{Call: _e.mock.On("CancelOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockOrderingServiceClient_CancelOrder_Call) Run(run func(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption)) *MockOrderingServiceClient_CancelOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*CancelOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockOrderingServiceClient_CancelOrder_Call) Return(_a0 *CancelOrderResponse, _a1 error) *MockOrderingServiceClient_CancelOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderingServiceClient_CancelOrder_Call) RunAndReturn(run func(context.Context, *CancelOrderRequest, ...grpc.CallOption) (*CancelOrderResponse, error)) *MockOrderingServiceClient_CancelOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteOrder provides a mock function with given fields: ctx, in, opts
func (_m *MockOrderingServiceClient) CompleteOrder(ctx context.Context, in *CompleteOrderRequest, opts ...grpc.CallOption) (*CompleteOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CompleteOrder")
	}

	var r0 *CompleteOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *CompleteOrderRequest, ...grpc.CallOption) (*CompleteOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *CompleteOrderRequest, ...grpc.CallOption) *CompleteOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CompleteOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *CompleteOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderingServiceClient_CompleteOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteOrder'
type MockOrderingServiceClient_CompleteOrder_Call struct {
	*mock.Call
}

// CompleteOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *CompleteOrderRequest
//   - opts ...grpc.CallOption
func (_e *MockOrderingServiceClient_Expecter) CompleteOrder(ctx interface{}, in interface{}, opts ...interface{}) *MockOrderingServiceClient_CompleteOrder_Call {
	return &MockOrderingServiceClient_CompleteOrder_Call{Call: _e.mock.On("CompleteOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockOrderingServiceClient_CompleteOrder_Call) Run(run func(ctx context.Context, in *CompleteOrderRequest, opts ...grpc.CallOption)) *MockOrderingServiceClient_CompleteOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*CompleteOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockOrderingServiceClient_CompleteOrder_Call) Return(_a0 *CompleteOrderResponse, _a1 error) *MockOrderingServiceClient_CompleteOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderingServiceClient_CompleteOrder_Call) RunAndReturn(run func(context.Context, *CompleteOrderRequest, ...grpc.CallOption) (*CompleteOrderResponse, error)) *MockOrderingServiceClient_CompleteOrder_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrder provides a mock function with given fields: ctx, in, opts
func (_m *MockOrderingServiceClient) CreateOrder(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption) (*CreateOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrder")
	}

	var r0 *CreateOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *CreateOrderRequest, ...grpc.CallOption) (*CreateOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *CreateOrderRequest, ...grpc.CallOption) *CreateOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*CreateOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *CreateOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderingServiceClient_CreateOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrder'
type MockOrderingServiceClient_CreateOrder_Call struct {
	*mock.Call
}

// CreateOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *CreateOrderRequest
//   - opts ...grpc.CallOption
func (_e *MockOrderingServiceClient_Expecter) CreateOrder(ctx interface{}, in interface{}, opts ...interface{}) *MockOrderingServiceClient_CreateOrder_Call {
	return &MockOrderingServiceClient_CreateOrder_Call{Call: _e.mock.On("CreateOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockOrderingServiceClient_CreateOrder_Call) Run(run func(ctx context.Context, in *CreateOrderRequest, opts ...grpc.CallOption)) *MockOrderingServiceClient_CreateOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*CreateOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockOrderingServiceClient_CreateOrder_Call) Return(_a0 *CreateOrderResponse, _a1 error) *MockOrderingServiceClient_CreateOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderingServiceClient_CreateOrder_Call) RunAndReturn(run func(context.Context, *CreateOrderRequest, ...grpc.CallOption) (*CreateOrderResponse, error)) *MockOrderingServiceClient_CreateOrder_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrder provides a mock function with given fields: ctx, in, opts
func (_m *MockOrderingServiceClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *GetOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *GetOrderRequest, ...grpc.CallOption) (*GetOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *GetOrderRequest, ...grpc.CallOption) *GetOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GetOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *GetOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderingServiceClient_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockOrderingServiceClient_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *GetOrderRequest
//   - opts ...grpc.CallOption
func (_e *MockOrderingServiceClient_Expecter) GetOrder(ctx interface{}, in interface{}, opts ...interface{}) *MockOrderingServiceClient_GetOrder_Call {
	return &MockOrderingServiceClient_GetOrder_Call{Call: _e.mock.On("GetOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockOrderingServiceClient_GetOrder_Call) Run(run func(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption)) *MockOrderingServiceClient_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*GetOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockOrderingServiceClient_GetOrder_Call) Return(_a0 *GetOrderResponse, _a1 error) *MockOrderingServiceClient_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderingServiceClient_GetOrder_Call) RunAndReturn(run func(context.Context, *GetOrderRequest, ...grpc.CallOption) (*GetOrderResponse, error)) *MockOrderingServiceClient_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// ReadyOrder provides a mock function with given fields: ctx, in, opts
func (_m *MockOrderingServiceClient) ReadyOrder(ctx context.Context, in *ReadyOrderRequest, opts ...grpc.CallOption) (*ReadyOrderResponse, error) {
	_va := make([]interface{}, len(opts))
	for _i := range opts {
		_va[_i] = opts[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, in)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for ReadyOrder")
	}

	var r0 *ReadyOrderResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *ReadyOrderRequest, ...grpc.CallOption) (*ReadyOrderResponse, error)); ok {
		return rf(ctx, in, opts...)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *ReadyOrderRequest, ...grpc.CallOption) *ReadyOrderResponse); ok {
		r0 = rf(ctx, in, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ReadyOrderResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *ReadyOrderRequest, ...grpc.CallOption) error); ok {
		r1 = rf(ctx, in, opts...)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOrderingServiceClient_ReadyOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadyOrder'
type MockOrderingServiceClient_ReadyOrder_Call struct {
	*mock.Call
}

// ReadyOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - in *ReadyOrderRequest
//   - opts ...grpc.CallOption
func (_e *MockOrderingServiceClient_Expecter) ReadyOrder(ctx interface{}, in interface{}, opts ...interface{}) *MockOrderingServiceClient_ReadyOrder_Call {
	return &MockOrderingServiceClient_ReadyOrder_Call{Call: _e.mock.On("ReadyOrder",
		append([]interface{}{ctx, in}, opts...)...)}
}

func (_c *MockOrderingServiceClient_ReadyOrder_Call) Run(run func(ctx context.Context, in *ReadyOrderRequest, opts ...grpc.CallOption)) *MockOrderingServiceClient_ReadyOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]grpc.CallOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(grpc.CallOption)
			}
		}
		run(args[0].(context.Context), args[1].(*ReadyOrderRequest), variadicArgs...)
	})
	return _c
}

func (_c *MockOrderingServiceClient_ReadyOrder_Call) Return(_a0 *ReadyOrderResponse, _a1 error) *MockOrderingServiceClient_ReadyOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOrderingServiceClient_ReadyOrder_Call) RunAndReturn(run func(context.Context, *ReadyOrderRequest, ...grpc.CallOption) (*ReadyOrderResponse, error)) *MockOrderingServiceClient_ReadyOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOrderingServiceClient creates a new instance of MockOrderingServiceClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrderingServiceClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrderingServiceClient {
	mock := &MockOrderingServiceClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
