// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/owezzy/soko-bora-mngt-system/ordering/internal/domain"
	mock "github.com/stretchr/testify/mock"

	queries "github.com/owezzy/soko-bora-mngt-system/ordering/internal/application/queries"
)

// MockQueries is an autogenerated mock type for the Queries type
type MockQueries struct {
	mock.Mock
}

type MockQueries_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueries) EXPECT() *MockQueries_Expecter {
	return &MockQueries_Expecter{mock: &_m.Mock}
}

// GetOrder provides a mock function with given fields: ctx, query
func (_m *MockQueries) GetOrder(ctx context.Context, query queries.GetOrder) (*domain.Order, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetOrder")
	}

	var r0 *domain.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetOrder) (*domain.Order, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetOrder) *domain.Order); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetOrder) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueries_GetOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrder'
type MockQueries_GetOrder_Call struct {
	*mock.Call
}

// GetOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - query queries.GetOrder
func (_e *MockQueries_Expecter) GetOrder(ctx interface{}, query interface{}) *MockQueries_GetOrder_Call {
	return &MockQueries_GetOrder_Call{Call: _e.mock.On("GetOrder", ctx, query)}
}

func (_c *MockQueries_GetOrder_Call) Run(run func(ctx context.Context, query queries.GetOrder)) *MockQueries_GetOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queries.GetOrder))
	})
	return _c
}

func (_c *MockQueries_GetOrder_Call) Return(_a0 *domain.Order, _a1 error) *MockQueries_GetOrder_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueries_GetOrder_Call) RunAndReturn(run func(context.Context, queries.GetOrder) (*domain.Order, error)) *MockQueries_GetOrder_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueries creates a new instance of MockQueries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueries(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueries {
	mock := &MockQueries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
