// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"

	commands "github.com/owezzy/soko-bora-mngt-system/stores/internal/application/commands"

	mock "github.com/stretchr/testify/mock"
)

// MockCommands is an autogenerated mock type for the Commands type
type MockCommands struct {
	mock.Mock
}

type MockCommands_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommands) EXPECT() *MockCommands_Expecter {
	return &MockCommands_Expecter{mock: &_m.Mock}
}

// AddProduct provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) AddProduct(ctx context.Context, cmd commands.AddProduct) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddProduct) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommands_AddProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProduct'
type MockCommands_AddProduct_Call struct {
	*mock.Call
}

// AddProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.AddProduct
func (_e *MockCommands_Expecter) AddProduct(ctx interface{}, cmd interface{}) *MockCommands_AddProduct_Call {
	return &MockCommands_AddProduct_Call{Call: _e.mock.On("AddProduct", ctx, cmd)}
}

func (_c *MockCommands_AddProduct_Call) Run(run func(ctx context.Context, cmd commands.AddProduct)) *MockCommands_AddProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.AddProduct))
	})
	return _c
}

func (_c *MockCommands_AddProduct_Call) Return(_a0 error) *MockCommands_AddProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommands_AddProduct_Call) RunAndReturn(run func(context.Context, commands.AddProduct) error) *MockCommands_AddProduct_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStore provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) CreateStore(ctx context.Context, cmd commands.CreateStore) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateStore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateStore) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommands_CreateStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStore'
type MockCommands_CreateStore_Call struct {
	*mock.Call
}

// CreateStore is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.CreateStore
func (_e *MockCommands_Expecter) CreateStore(ctx interface{}, cmd interface{}) *MockCommands_CreateStore_Call {
	return &MockCommands_CreateStore_Call{Call: _e.mock.On("CreateStore", ctx, cmd)}
}

func (_c *MockCommands_CreateStore_Call) Run(run func(ctx context.Context, cmd commands.CreateStore)) *MockCommands_CreateStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.CreateStore))
	})
	return _c
}

func (_c *MockCommands_CreateStore_Call) Return(_a0 error) *MockCommands_CreateStore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommands_CreateStore_Call) RunAndReturn(run func(context.Context, commands.CreateStore) error) *MockCommands_CreateStore_Call {
	_c.Call.Return(run)
	return _c
}

// DecreaseProductPrice provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) DecreaseProductPrice(ctx context.Context, cmd commands.DecreaseProductPrice) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for DecreaseProductPrice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.DecreaseProductPrice) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommands_DecreaseProductPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecreaseProductPrice'
type MockCommands_DecreaseProductPrice_Call struct {
	*mock.Call
}

// DecreaseProductPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.DecreaseProductPrice
func (_e *MockCommands_Expecter) DecreaseProductPrice(ctx interface{}, cmd interface{}) *MockCommands_DecreaseProductPrice_Call {
	return &MockCommands_DecreaseProductPrice_Call{Call: _e.mock.On("DecreaseProductPrice", ctx, cmd)}
}

func (_c *MockCommands_DecreaseProductPrice_Call) Run(run func(ctx context.Context, cmd commands.DecreaseProductPrice)) *MockCommands_DecreaseProductPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.DecreaseProductPrice))
	})
	return _c
}

func (_c *MockCommands_DecreaseProductPrice_Call) Return(_a0 error) *MockCommands_DecreaseProductPrice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommands_DecreaseProductPrice_Call) RunAndReturn(run func(context.Context, commands.DecreaseProductPrice) error) *MockCommands_DecreaseProductPrice_Call {
	_c.Call.Return(run)
	return _c
}

// DisableParticipation provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) DisableParticipation(ctx context.Context, cmd commands.DisableParticipation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for DisableParticipation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.DisableParticipation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommands_DisableParticipation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableParticipation'
type MockCommands_DisableParticipation_Call struct {
	*mock.Call
}

// DisableParticipation is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.DisableParticipation
func (_e *MockCommands_Expecter) DisableParticipation(ctx interface{}, cmd interface{}) *MockCommands_DisableParticipation_Call {
	return &MockCommands_DisableParticipation_Call{Call: _e.mock.On("DisableParticipation", ctx, cmd)}
}

func (_c *MockCommands_DisableParticipation_Call) Run(run func(ctx context.Context, cmd commands.DisableParticipation)) *MockCommands_DisableParticipation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.DisableParticipation))
	})
	return _c
}

func (_c *MockCommands_DisableParticipation_Call) Return(_a0 error) *MockCommands_DisableParticipation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommands_DisableParticipation_Call) RunAndReturn(run func(context.Context, commands.DisableParticipation) error) *MockCommands_DisableParticipation_Call {
	_c.Call.Return(run)
	return _c
}

// EnableParticipation provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) EnableParticipation(ctx context.Context, cmd commands.EnableParticipation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for EnableParticipation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.EnableParticipation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommands_EnableParticipation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableParticipation'
type MockCommands_EnableParticipation_Call struct {
	*mock.Call
}

// EnableParticipation is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.EnableParticipation
func (_e *MockCommands_Expecter) EnableParticipation(ctx interface{}, cmd interface{}) *MockCommands_EnableParticipation_Call {
	return &MockCommands_EnableParticipation_Call{Call: _e.mock.On("EnableParticipation", ctx, cmd)}
}

func (_c *MockCommands_EnableParticipation_Call) Run(run func(ctx context.Context, cmd commands.EnableParticipation)) *MockCommands_EnableParticipation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.EnableParticipation))
	})
	return _c
}

func (_c *MockCommands_EnableParticipation_Call) Return(_a0 error) *MockCommands_EnableParticipation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommands_EnableParticipation_Call) RunAndReturn(run func(context.Context, commands.EnableParticipation) error) *MockCommands_EnableParticipation_Call {
	_c.Call.Return(run)
	return _c
}

// IncreaseProductPrice provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) IncreaseProductPrice(ctx context.Context, cmd commands.IncreaseProductPrice) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for IncreaseProductPrice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.IncreaseProductPrice) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommands_IncreaseProductPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncreaseProductPrice'
type MockCommands_IncreaseProductPrice_Call struct {
	*mock.Call
}

// IncreaseProductPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.IncreaseProductPrice
func (_e *MockCommands_Expecter) IncreaseProductPrice(ctx interface{}, cmd interface{}) *MockCommands_IncreaseProductPrice_Call {
	return &MockCommands_IncreaseProductPrice_Call{Call: _e.mock.On("IncreaseProductPrice", ctx, cmd)}
}

func (_c *MockCommands_IncreaseProductPrice_Call) Run(run func(ctx context.Context, cmd commands.IncreaseProductPrice)) *MockCommands_IncreaseProductPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.IncreaseProductPrice))
	})
	return _c
}

func (_c *MockCommands_IncreaseProductPrice_Call) Return(_a0 error) *MockCommands_IncreaseProductPrice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommands_IncreaseProductPrice_Call) RunAndReturn(run func(context.Context, commands.IncreaseProductPrice) error) *MockCommands_IncreaseProductPrice_Call {
	_c.Call.Return(run)
	return _c
}

// RebrandProduct provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) RebrandProduct(ctx context.Context, cmd commands.RebrandProduct) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RebrandProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.RebrandProduct) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommands_RebrandProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RebrandProduct'
type MockCommands_RebrandProduct_Call struct {
	*mock.Call
}

// RebrandProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.RebrandProduct
func (_e *MockCommands_Expecter) RebrandProduct(ctx interface{}, cmd interface{}) *MockCommands_RebrandProduct_Call {
	return &MockCommands_RebrandProduct_Call{Call: _e.mock.On("RebrandProduct", ctx, cmd)}
}

func (_c *MockCommands_RebrandProduct_Call) Run(run func(ctx context.Context, cmd commands.RebrandProduct)) *MockCommands_RebrandProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.RebrandProduct))
	})
	return _c
}

func (_c *MockCommands_RebrandProduct_Call) Return(_a0 error) *MockCommands_RebrandProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommands_RebrandProduct_Call) RunAndReturn(run func(context.Context, commands.RebrandProduct) error) *MockCommands_RebrandProduct_Call {
	_c.Call.Return(run)
	return _c
}

// RebrandStore provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) RebrandStore(ctx context.Context, cmd commands.RebrandStore) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RebrandStore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.RebrandStore) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommands_RebrandStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RebrandStore'
type MockCommands_RebrandStore_Call struct {
	*mock.Call
}

// RebrandStore is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.RebrandStore
func (_e *MockCommands_Expecter) RebrandStore(ctx interface{}, cmd interface{}) *MockCommands_RebrandStore_Call {
	return &MockCommands_RebrandStore_Call{Call: _e.mock.On("RebrandStore", ctx, cmd)}
}

func (_c *MockCommands_RebrandStore_Call) Run(run func(ctx context.Context, cmd commands.RebrandStore)) *MockCommands_RebrandStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.RebrandStore))
	})
	return _c
}

func (_c *MockCommands_RebrandStore_Call) Return(_a0 error) *MockCommands_RebrandStore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommands_RebrandStore_Call) RunAndReturn(run func(context.Context, commands.RebrandStore) error) *MockCommands_RebrandStore_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveProduct provides a mock function with given fields: ctx, cmd
func (_m *MockCommands) RemoveProduct(ctx context.Context, cmd commands.RemoveProduct) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.RemoveProduct) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCommands_RemoveProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveProduct'
type MockCommands_RemoveProduct_Call struct {
	*mock.Call
}

// RemoveProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.RemoveProduct
func (_e *MockCommands_Expecter) RemoveProduct(ctx interface{}, cmd interface{}) *MockCommands_RemoveProduct_Call {
	return &MockCommands_RemoveProduct_Call{Call: _e.mock.On("RemoveProduct", ctx, cmd)}
}

func (_c *MockCommands_RemoveProduct_Call) Run(run func(ctx context.Context, cmd commands.RemoveProduct)) *MockCommands_RemoveProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.RemoveProduct))
	})
	return _c
}

func (_c *MockCommands_RemoveProduct_Call) Return(_a0 error) *MockCommands_RemoveProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCommands_RemoveProduct_Call) RunAndReturn(run func(context.Context, commands.RemoveProduct) error) *MockCommands_RemoveProduct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCommands creates a new instance of MockCommands. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommands(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommands {
	mock := &MockCommands{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
