// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"

	domain "github.com/owezzy/soko-bora-mngt-system/stores/internal/domain"
	mock "github.com/stretchr/testify/mock"

	queries "github.com/owezzy/soko-bora-mngt-system/stores/internal/application/queries"
)

// MockQueries is an autogenerated mock type for the Queries type
type MockQueries struct {
	mock.Mock
}

type MockQueries_Expecter struct {
	mock *mock.Mock
}

func (_m *MockQueries) EXPECT() *MockQueries_Expecter {
	return &MockQueries_Expecter{mock: &_m.Mock}
}

// GetCatalog provides a mock function with given fields: ctx, query
func (_m *MockQueries) GetCatalog(ctx context.Context, query queries.GetCatalog) ([]*domain.CatalogProduct, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetCatalog")
	}

	var r0 []*domain.CatalogProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetCatalog) ([]*domain.CatalogProduct, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetCatalog) []*domain.CatalogProduct); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CatalogProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetCatalog) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueries_GetCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCatalog'
type MockQueries_GetCatalog_Call struct {
	*mock.Call
}

// GetCatalog is a helper method to define mock.On call
//   - ctx context.Context
//   - query queries.GetCatalog
func (_e *MockQueries_Expecter) GetCatalog(ctx interface{}, query interface{}) *MockQueries_GetCatalog_Call {
	return &MockQueries_GetCatalog_Call{Call: _e.mock.On("GetCatalog", ctx, query)}
}

func (_c *MockQueries_GetCatalog_Call) Run(run func(ctx context.Context, query queries.GetCatalog)) *MockQueries_GetCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queries.GetCatalog))
	})
	return _c
}

func (_c *MockQueries_GetCatalog_Call) Return(_a0 []*domain.CatalogProduct, _a1 error) *MockQueries_GetCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueries_GetCatalog_Call) RunAndReturn(run func(context.Context, queries.GetCatalog) ([]*domain.CatalogProduct, error)) *MockQueries_GetCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipatingStores provides a mock function with given fields: ctx, query
func (_m *MockQueries) GetParticipatingStores(ctx context.Context, query queries.GetParticipatingStores) ([]*domain.MallStore, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipatingStores")
	}

	var r0 []*domain.MallStore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetParticipatingStores) ([]*domain.MallStore, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetParticipatingStores) []*domain.MallStore); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.MallStore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetParticipatingStores) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueries_GetParticipatingStores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipatingStores'
type MockQueries_GetParticipatingStores_Call struct {
	*mock.Call
}

// GetParticipatingStores is a helper method to define mock.On call
//   - ctx context.Context
//   - query queries.GetParticipatingStores
func (_e *MockQueries_Expecter) GetParticipatingStores(ctx interface{}, query interface{}) *MockQueries_GetParticipatingStores_Call {
	return &MockQueries_GetParticipatingStores_Call{Call: _e.mock.On("GetParticipatingStores", ctx, query)}
}

func (_c *MockQueries_GetParticipatingStores_Call) Run(run func(ctx context.Context, query queries.GetParticipatingStores)) *MockQueries_GetParticipatingStores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queries.GetParticipatingStores))
	})
	return _c
}

func (_c *MockQueries_GetParticipatingStores_Call) Return(_a0 []*domain.MallStore, _a1 error) *MockQueries_GetParticipatingStores_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueries_GetParticipatingStores_Call) RunAndReturn(run func(context.Context, queries.GetParticipatingStores) ([]*domain.MallStore, error)) *MockQueries_GetParticipatingStores_Call {
	_c.Call.Return(run)
	return _c
}

// GetProduct provides a mock function with given fields: ctx, query
func (_m *MockQueries) GetProduct(ctx context.Context, query queries.GetProduct) (*domain.CatalogProduct, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *domain.CatalogProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetProduct) (*domain.CatalogProduct, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetProduct) *domain.CatalogProduct); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CatalogProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetProduct) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueries_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type MockQueries_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - query queries.GetProduct
func (_e *MockQueries_Expecter) GetProduct(ctx interface{}, query interface{}) *MockQueries_GetProduct_Call {
	return &MockQueries_GetProduct_Call{Call: _e.mock.On("GetProduct", ctx, query)}
}

func (_c *MockQueries_GetProduct_Call) Run(run func(ctx context.Context, query queries.GetProduct)) *MockQueries_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queries.GetProduct))
	})
	return _c
}

func (_c *MockQueries_GetProduct_Call) Return(_a0 *domain.CatalogProduct, _a1 error) *MockQueries_GetProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueries_GetProduct_Call) RunAndReturn(run func(context.Context, queries.GetProduct) (*domain.CatalogProduct, error)) *MockQueries_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetStore provides a mock function with given fields: ctx, query
func (_m *MockQueries) GetStore(ctx context.Context, query queries.GetStore) (*domain.MallStore, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetStore")
	}

	var r0 *domain.MallStore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetStore) (*domain.MallStore, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetStore) *domain.MallStore); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MallStore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetStore) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueries_GetStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStore'
type MockQueries_GetStore_Call struct {
	*mock.Call
}

// GetStore is a helper method to define mock.On call
//   - ctx context.Context
//   - query queries.GetStore
func (_e *MockQueries_Expecter) GetStore(ctx interface{}, query interface{}) *MockQueries_GetStore_Call {
	return &MockQueries_GetStore_Call{Call: _e.mock.On("GetStore", ctx, query)}
}

func (_c *MockQueries_GetStore_Call) Run(run func(ctx context.Context, query queries.GetStore)) *MockQueries_GetStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queries.GetStore))
	})
	return _c
}

func (_c *MockQueries_GetStore_Call) Return(_a0 *domain.MallStore, _a1 error) *MockQueries_GetStore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueries_GetStore_Call) RunAndReturn(run func(context.Context, queries.GetStore) (*domain.MallStore, error)) *MockQueries_GetStore_Call {
	_c.Call.Return(run)
	return _c
}

// GetStores provides a mock function with given fields: ctx, query
func (_m *MockQueries) GetStores(ctx context.Context, query queries.GetStores) ([]*domain.MallStore, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetStores")
	}

	var r0 []*domain.MallStore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetStores) ([]*domain.MallStore, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetStores) []*domain.MallStore); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.MallStore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetStores) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockQueries_GetStores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStores'
type MockQueries_GetStores_Call struct {
	*mock.Call
}

// GetStores is a helper method to define mock.On call
//   - ctx context.Context
//   - query queries.GetStores
func (_e *MockQueries_Expecter) GetStores(ctx interface{}, query interface{}) *MockQueries_GetStores_Call {
	return &MockQueries_GetStores_Call{Call: _e.mock.On("GetStores", ctx, query)}
}

func (_c *MockQueries_GetStores_Call) Run(run func(ctx context.Context, query queries.GetStores)) *MockQueries_GetStores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queries.GetStores))
	})
	return _c
}

func (_c *MockQueries_GetStores_Call) Return(_a0 []*domain.MallStore, _a1 error) *MockQueries_GetStores_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockQueries_GetStores_Call) RunAndReturn(run func(context.Context, queries.GetStores) ([]*domain.MallStore, error)) *MockQueries_GetStores_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockQueries creates a new instance of MockQueries. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockQueries(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockQueries {
	mock := &MockQueries{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
