// Code generated by mockery. DO NOT EDIT.

package application

import (
	context "context"

	commands "github.com/owezzy/soko-bora-mngt-system/stores/internal/application/commands"

	domain "github.com/owezzy/soko-bora-mngt-system/stores/internal/domain"

	mock "github.com/stretchr/testify/mock"

	queries "github.com/owezzy/soko-bora-mngt-system/stores/internal/application/queries"
)

// MockApp is an autogenerated mock type for the App type
type MockApp struct {
	mock.Mock
}

type MockApp_Expecter struct {
	mock *mock.Mock
}

func (_m *MockApp) EXPECT() *MockApp_Expecter {
	return &MockApp_Expecter{mock: &_m.Mock}
}

// AddProduct provides a mock function with given fields: ctx, cmd
func (_m *MockApp) AddProduct(ctx context.Context, cmd commands.AddProduct) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for AddProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.AddProduct) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_AddProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddProduct'
type MockApp_AddProduct_Call struct {
	*mock.Call
}

// AddProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.AddProduct
func (_e *MockApp_Expecter) AddProduct(ctx interface{}, cmd interface{}) *MockApp_AddProduct_Call {
	return &MockApp_AddProduct_Call{Call: _e.mock.On("AddProduct", ctx, cmd)}
}

func (_c *MockApp_AddProduct_Call) Run(run func(ctx context.Context, cmd commands.AddProduct)) *MockApp_AddProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.AddProduct))
	})
	return _c
}

func (_c *MockApp_AddProduct_Call) Return(_a0 error) *MockApp_AddProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_AddProduct_Call) RunAndReturn(run func(context.Context, commands.AddProduct) error) *MockApp_AddProduct_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStore provides a mock function with given fields: ctx, cmd
func (_m *MockApp) CreateStore(ctx context.Context, cmd commands.CreateStore) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for CreateStore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.CreateStore) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_CreateStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStore'
type MockApp_CreateStore_Call struct {
	*mock.Call
}

// CreateStore is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.CreateStore
func (_e *MockApp_Expecter) CreateStore(ctx interface{}, cmd interface{}) *MockApp_CreateStore_Call {
	return &MockApp_CreateStore_Call{Call: _e.mock.On("CreateStore", ctx, cmd)}
}

func (_c *MockApp_CreateStore_Call) Run(run func(ctx context.Context, cmd commands.CreateStore)) *MockApp_CreateStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.CreateStore))
	})
	return _c
}

func (_c *MockApp_CreateStore_Call) Return(_a0 error) *MockApp_CreateStore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_CreateStore_Call) RunAndReturn(run func(context.Context, commands.CreateStore) error) *MockApp_CreateStore_Call {
	_c.Call.Return(run)
	return _c
}

// DecreaseProductPrice provides a mock function with given fields: ctx, cmd
func (_m *MockApp) DecreaseProductPrice(ctx context.Context, cmd commands.DecreaseProductPrice) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for DecreaseProductPrice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.DecreaseProductPrice) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_DecreaseProductPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DecreaseProductPrice'
type MockApp_DecreaseProductPrice_Call struct {
	*mock.Call
}

// DecreaseProductPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.DecreaseProductPrice
func (_e *MockApp_Expecter) DecreaseProductPrice(ctx interface{}, cmd interface{}) *MockApp_DecreaseProductPrice_Call {
	return &MockApp_DecreaseProductPrice_Call{Call: _e.mock.On("DecreaseProductPrice", ctx, cmd)}
}

func (_c *MockApp_DecreaseProductPrice_Call) Run(run func(ctx context.Context, cmd commands.DecreaseProductPrice)) *MockApp_DecreaseProductPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.DecreaseProductPrice))
	})
	return _c
}

func (_c *MockApp_DecreaseProductPrice_Call) Return(_a0 error) *MockApp_DecreaseProductPrice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_DecreaseProductPrice_Call) RunAndReturn(run func(context.Context, commands.DecreaseProductPrice) error) *MockApp_DecreaseProductPrice_Call {
	_c.Call.Return(run)
	return _c
}

// DisableParticipation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) DisableParticipation(ctx context.Context, cmd commands.DisableParticipation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for DisableParticipation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.DisableParticipation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_DisableParticipation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableParticipation'
type MockApp_DisableParticipation_Call struct {
	*mock.Call
}

// DisableParticipation is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.DisableParticipation
func (_e *MockApp_Expecter) DisableParticipation(ctx interface{}, cmd interface{}) *MockApp_DisableParticipation_Call {
	return &MockApp_DisableParticipation_Call{Call: _e.mock.On("DisableParticipation", ctx, cmd)}
}

func (_c *MockApp_DisableParticipation_Call) Run(run func(ctx context.Context, cmd commands.DisableParticipation)) *MockApp_DisableParticipation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.DisableParticipation))
	})
	return _c
}

func (_c *MockApp_DisableParticipation_Call) Return(_a0 error) *MockApp_DisableParticipation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_DisableParticipation_Call) RunAndReturn(run func(context.Context, commands.DisableParticipation) error) *MockApp_DisableParticipation_Call {
	_c.Call.Return(run)
	return _c
}

// EnableParticipation provides a mock function with given fields: ctx, cmd
func (_m *MockApp) EnableParticipation(ctx context.Context, cmd commands.EnableParticipation) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for EnableParticipation")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.EnableParticipation) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_EnableParticipation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableParticipation'
type MockApp_EnableParticipation_Call struct {
	*mock.Call
}

// EnableParticipation is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.EnableParticipation
func (_e *MockApp_Expecter) EnableParticipation(ctx interface{}, cmd interface{}) *MockApp_EnableParticipation_Call {
	return &MockApp_EnableParticipation_Call{Call: _e.mock.On("EnableParticipation", ctx, cmd)}
}

func (_c *MockApp_EnableParticipation_Call) Run(run func(ctx context.Context, cmd commands.EnableParticipation)) *MockApp_EnableParticipation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.EnableParticipation))
	})
	return _c
}

func (_c *MockApp_EnableParticipation_Call) Return(_a0 error) *MockApp_EnableParticipation_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_EnableParticipation_Call) RunAndReturn(run func(context.Context, commands.EnableParticipation) error) *MockApp_EnableParticipation_Call {
	_c.Call.Return(run)
	return _c
}

// GetCatalog provides a mock function with given fields: ctx, query
func (_m *MockApp) GetCatalog(ctx context.Context, query queries.GetCatalog) ([]*domain.CatalogProduct, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetCatalog")
	}

	var r0 []*domain.CatalogProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetCatalog) ([]*domain.CatalogProduct, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetCatalog) []*domain.CatalogProduct); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.CatalogProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetCatalog) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_GetCatalog_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCatalog'
type MockApp_GetCatalog_Call struct {
	*mock.Call
}

// GetCatalog is a helper method to define mock.On call
//   - ctx context.Context
//   - query queries.GetCatalog
func (_e *MockApp_Expecter) GetCatalog(ctx interface{}, query interface{}) *MockApp_GetCatalog_Call {
	return &MockApp_GetCatalog_Call{Call: _e.mock.On("GetCatalog", ctx, query)}
}

func (_c *MockApp_GetCatalog_Call) Run(run func(ctx context.Context, query queries.GetCatalog)) *MockApp_GetCatalog_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queries.GetCatalog))
	})
	return _c
}

func (_c *MockApp_GetCatalog_Call) Return(_a0 []*domain.CatalogProduct, _a1 error) *MockApp_GetCatalog_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_GetCatalog_Call) RunAndReturn(run func(context.Context, queries.GetCatalog) ([]*domain.CatalogProduct, error)) *MockApp_GetCatalog_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipatingStores provides a mock function with given fields: ctx, query
func (_m *MockApp) GetParticipatingStores(ctx context.Context, query queries.GetParticipatingStores) ([]*domain.MallStore, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetParticipatingStores")
	}

	var r0 []*domain.MallStore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetParticipatingStores) ([]*domain.MallStore, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetParticipatingStores) []*domain.MallStore); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.MallStore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetParticipatingStores) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_GetParticipatingStores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipatingStores'
type MockApp_GetParticipatingStores_Call struct {
	*mock.Call
}

// GetParticipatingStores is a helper method to define mock.On call
//   - ctx context.Context
//   - query queries.GetParticipatingStores
func (_e *MockApp_Expecter) GetParticipatingStores(ctx interface{}, query interface{}) *MockApp_GetParticipatingStores_Call {
	return &MockApp_GetParticipatingStores_Call{Call: _e.mock.On("GetParticipatingStores", ctx, query)}
}

func (_c *MockApp_GetParticipatingStores_Call) Run(run func(ctx context.Context, query queries.GetParticipatingStores)) *MockApp_GetParticipatingStores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queries.GetParticipatingStores))
	})
	return _c
}

func (_c *MockApp_GetParticipatingStores_Call) Return(_a0 []*domain.MallStore, _a1 error) *MockApp_GetParticipatingStores_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_GetParticipatingStores_Call) RunAndReturn(run func(context.Context, queries.GetParticipatingStores) ([]*domain.MallStore, error)) *MockApp_GetParticipatingStores_Call {
	_c.Call.Return(run)
	return _c
}

// GetProduct provides a mock function with given fields: ctx, query
func (_m *MockApp) GetProduct(ctx context.Context, query queries.GetProduct) (*domain.CatalogProduct, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetProduct")
	}

	var r0 *domain.CatalogProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetProduct) (*domain.CatalogProduct, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetProduct) *domain.CatalogProduct); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.CatalogProduct)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetProduct) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_GetProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProduct'
type MockApp_GetProduct_Call struct {
	*mock.Call
}

// GetProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - query queries.GetProduct
func (_e *MockApp_Expecter) GetProduct(ctx interface{}, query interface{}) *MockApp_GetProduct_Call {
	return &MockApp_GetProduct_Call{Call: _e.mock.On("GetProduct", ctx, query)}
}

func (_c *MockApp_GetProduct_Call) Run(run func(ctx context.Context, query queries.GetProduct)) *MockApp_GetProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queries.GetProduct))
	})
	return _c
}

func (_c *MockApp_GetProduct_Call) Return(_a0 *domain.CatalogProduct, _a1 error) *MockApp_GetProduct_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_GetProduct_Call) RunAndReturn(run func(context.Context, queries.GetProduct) (*domain.CatalogProduct, error)) *MockApp_GetProduct_Call {
	_c.Call.Return(run)
	return _c
}

// GetStore provides a mock function with given fields: ctx, query
func (_m *MockApp) GetStore(ctx context.Context, query queries.GetStore) (*domain.MallStore, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetStore")
	}

	var r0 *domain.MallStore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetStore) (*domain.MallStore, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetStore) *domain.MallStore); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.MallStore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetStore) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_GetStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStore'
type MockApp_GetStore_Call struct {
	*mock.Call
}

// GetStore is a helper method to define mock.On call
//   - ctx context.Context
//   - query queries.GetStore
func (_e *MockApp_Expecter) GetStore(ctx interface{}, query interface{}) *MockApp_GetStore_Call {
	return &MockApp_GetStore_Call{Call: _e.mock.On("GetStore", ctx, query)}
}

func (_c *MockApp_GetStore_Call) Run(run func(ctx context.Context, query queries.GetStore)) *MockApp_GetStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queries.GetStore))
	})
	return _c
}

func (_c *MockApp_GetStore_Call) Return(_a0 *domain.MallStore, _a1 error) *MockApp_GetStore_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_GetStore_Call) RunAndReturn(run func(context.Context, queries.GetStore) (*domain.MallStore, error)) *MockApp_GetStore_Call {
	_c.Call.Return(run)
	return _c
}

// GetStores provides a mock function with given fields: ctx, query
func (_m *MockApp) GetStores(ctx context.Context, query queries.GetStores) ([]*domain.MallStore, error) {
	ret := _m.Called(ctx, query)

	if len(ret) == 0 {
		panic("no return value specified for GetStores")
	}

	var r0 []*domain.MallStore
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetStores) ([]*domain.MallStore, error)); ok {
		return rf(ctx, query)
	}
	if rf, ok := ret.Get(0).(func(context.Context, queries.GetStores) []*domain.MallStore); ok {
		r0 = rf(ctx, query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.MallStore)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, queries.GetStores) error); ok {
		r1 = rf(ctx, query)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockApp_GetStores_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStores'
type MockApp_GetStores_Call struct {
	*mock.Call
}

// GetStores is a helper method to define mock.On call
//   - ctx context.Context
//   - query queries.GetStores
func (_e *MockApp_Expecter) GetStores(ctx interface{}, query interface{}) *MockApp_GetStores_Call {
	return &MockApp_GetStores_Call{Call: _e.mock.On("GetStores", ctx, query)}
}

func (_c *MockApp_GetStores_Call) Run(run func(ctx context.Context, query queries.GetStores)) *MockApp_GetStores_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(queries.GetStores))
	})
	return _c
}

func (_c *MockApp_GetStores_Call) Return(_a0 []*domain.MallStore, _a1 error) *MockApp_GetStores_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockApp_GetStores_Call) RunAndReturn(run func(context.Context, queries.GetStores) ([]*domain.MallStore, error)) *MockApp_GetStores_Call {
	_c.Call.Return(run)
	return _c
}

// IncreaseProductPrice provides a mock function with given fields: ctx, cmd
func (_m *MockApp) IncreaseProductPrice(ctx context.Context, cmd commands.IncreaseProductPrice) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for IncreaseProductPrice")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.IncreaseProductPrice) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_IncreaseProductPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IncreaseProductPrice'
type MockApp_IncreaseProductPrice_Call struct {
	*mock.Call
}

// IncreaseProductPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.IncreaseProductPrice
func (_e *MockApp_Expecter) IncreaseProductPrice(ctx interface{}, cmd interface{}) *MockApp_IncreaseProductPrice_Call {
	return &MockApp_IncreaseProductPrice_Call{Call: _e.mock.On("IncreaseProductPrice", ctx, cmd)}
}

func (_c *MockApp_IncreaseProductPrice_Call) Run(run func(ctx context.Context, cmd commands.IncreaseProductPrice)) *MockApp_IncreaseProductPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.IncreaseProductPrice))
	})
	return _c
}

func (_c *MockApp_IncreaseProductPrice_Call) Return(_a0 error) *MockApp_IncreaseProductPrice_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_IncreaseProductPrice_Call) RunAndReturn(run func(context.Context, commands.IncreaseProductPrice) error) *MockApp_IncreaseProductPrice_Call {
	_c.Call.Return(run)
	return _c
}

// RebrandProduct provides a mock function with given fields: ctx, cmd
func (_m *MockApp) RebrandProduct(ctx context.Context, cmd commands.RebrandProduct) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RebrandProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.RebrandProduct) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_RebrandProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RebrandProduct'
type MockApp_RebrandProduct_Call struct {
	*mock.Call
}

// RebrandProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.RebrandProduct
func (_e *MockApp_Expecter) RebrandProduct(ctx interface{}, cmd interface{}) *MockApp_RebrandProduct_Call {
	return &MockApp_RebrandProduct_Call{Call: _e.mock.On("RebrandProduct", ctx, cmd)}
}

func (_c *MockApp_RebrandProduct_Call) Run(run func(ctx context.Context, cmd commands.RebrandProduct)) *MockApp_RebrandProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.RebrandProduct))
	})
	return _c
}

func (_c *MockApp_RebrandProduct_Call) Return(_a0 error) *MockApp_RebrandProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_RebrandProduct_Call) RunAndReturn(run func(context.Context, commands.RebrandProduct) error) *MockApp_RebrandProduct_Call {
	_c.Call.Return(run)
	return _c
}

// RebrandStore provides a mock function with given fields: ctx, cmd
func (_m *MockApp) RebrandStore(ctx context.Context, cmd commands.RebrandStore) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RebrandStore")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.RebrandStore) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_RebrandStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RebrandStore'
type MockApp_RebrandStore_Call struct {
	*mock.Call
}

// RebrandStore is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.RebrandStore
func (_e *MockApp_Expecter) RebrandStore(ctx interface{}, cmd interface{}) *MockApp_RebrandStore_Call {
	return &MockApp_RebrandStore_Call{Call: _e.mock.On("RebrandStore", ctx, cmd)}
}

func (_c *MockApp_RebrandStore_Call) Run(run func(ctx context.Context, cmd commands.RebrandStore)) *MockApp_RebrandStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.RebrandStore))
	})
	return _c
}

func (_c *MockApp_RebrandStore_Call) Return(_a0 error) *MockApp_RebrandStore_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_RebrandStore_Call) RunAndReturn(run func(context.Context, commands.RebrandStore) error) *MockApp_RebrandStore_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveProduct provides a mock function with given fields: ctx, cmd
func (_m *MockApp) RemoveProduct(ctx context.Context, cmd commands.RemoveProduct) error {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for RemoveProduct")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, commands.RemoveProduct) error); ok {
		r0 = rf(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockApp_RemoveProduct_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveProduct'
type MockApp_RemoveProduct_Call struct {
	*mock.Call
}

// RemoveProduct is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd commands.RemoveProduct
func (_e *MockApp_Expecter) RemoveProduct(ctx interface{}, cmd interface{}) *MockApp_RemoveProduct_Call {
	return &MockApp_RemoveProduct_Call{Call: _e.mock.On("RemoveProduct", ctx, cmd)}
}

func (_c *MockApp_RemoveProduct_Call) Run(run func(ctx context.Context, cmd commands.RemoveProduct)) *MockApp_RemoveProduct_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(commands.RemoveProduct))
	})
	return _c
}

func (_c *MockApp_RemoveProduct_Call) Return(_a0 error) *MockApp_RemoveProduct_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockApp_RemoveProduct_Call) RunAndReturn(run func(context.Context, commands.RemoveProduct) error) *MockApp_RemoveProduct_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockApp creates a new instance of MockApp. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockApp(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockApp {
	mock := &MockApp{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
