// Code generated by mockery. DO NOT EDIT.

package es

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAggregateStore is an autogenerated mock type for the AggregateStore type
type MockAggregateStore struct {
	mock.Mock
}

type MockAggregateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAggregateStore) EXPECT() *MockAggregateStore_Expecter {
	return &MockAggregateStore_Expecter{mock: &_m.Mock}
}

// Load provides a mock function with given fields: ctx, aggregate
func (_m *MockAggregateStore) Load(ctx context.Context, aggregate EventSourcedAggregate) error {
	ret := _m.Called(ctx, aggregate)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, EventSourcedAggregate) error); ok {
		r0 = rf(ctx, aggregate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAggregateStore_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockAggregateStore_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregate EventSourcedAggregate
func (_e *MockAggregateStore_Expecter) Load(ctx interface{}, aggregate interface{}) *MockAggregateStore_Load_Call {
	return &MockAggregateStore_Load_Call{Call: _e.mock.On("Load", ctx, aggregate)}
}

func (_c *MockAggregateStore_Load_Call) Run(run func(ctx context.Context, aggregate EventSourcedAggregate)) *MockAggregateStore_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(EventSourcedAggregate))
	})
	return _c
}

func (_c *MockAggregateStore_Load_Call) Return(_a0 error) *MockAggregateStore_Load_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAggregateStore_Load_Call) RunAndReturn(run func(context.Context, EventSourcedAggregate) error) *MockAggregateStore_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, aggregate
func (_m *MockAggregateStore) Save(ctx context.Context, aggregate EventSourcedAggregate) error {
	ret := _m.Called(ctx, aggregate)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, EventSourcedAggregate) error); ok {
		r0 = rf(ctx, aggregate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAggregateStore_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAggregateStore_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregate EventSourcedAggregate
func (_e *MockAggregateStore_Expecter) Save(ctx interface{}, aggregate interface{}) *MockAggregateStore_Save_Call {
	return &MockAggregateStore_Save_Call{Call: _e.mock.On("Save", ctx, aggregate)}
}

func (_c *MockAggregateStore_Save_Call) Run(run func(ctx context.Context, aggregate EventSourcedAggregate)) *MockAggregateStore_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(EventSourcedAggregate))
	})
	return _c
}

func (_c *MockAggregateStore_Save_Call) Return(_a0 error) *MockAggregateStore_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAggregateStore_Save_Call) RunAndReturn(run func(context.Context, EventSourcedAggregate) error) *MockAggregateStore_Save_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAggregateStore creates a new instance of MockAggregateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAggregateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAggregateStore {
	mock := &MockAggregateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
