// Code generated by mockery. DO NOT EDIT.

package es

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockAggregateRepository is an autogenerated mock type for the AggregateRepository type
type MockAggregateRepository[T EventSourcedAggregate] struct {
	mock.Mock
}

type MockAggregateRepository_Expecter[T EventSourcedAggregate] struct {
	mock *mock.Mock
}

func (_m *MockAggregateRepository[T]) EXPECT() *MockAggregateRepository_Expecter[T] {
	return &MockAggregateRepository_Expecter[T]{mock: &_m.Mock}
}

// Load provides a mock function with given fields: ctx, aggregateID
func (_m *MockAggregateRepository[T]) Load(ctx context.Context, aggregateID string) (T, error) {
	ret := _m.Called(ctx, aggregateID)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 T
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (T, error)); ok {
		return rf(ctx, aggregateID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) T); ok {
		r0 = rf(ctx, aggregateID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(T)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, aggregateID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAggregateRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockAggregateRepository_Load_Call[T EventSourcedAggregate] struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregateID string
func (_e *MockAggregateRepository_Expecter[T]) Load(ctx interface{}, aggregateID interface{}) *MockAggregateRepository_Load_Call[T] {
	return &MockAggregateRepository_Load_Call[T]{Call: _e.mock.On("Load", ctx, aggregateID)}
}

func (_c *MockAggregateRepository_Load_Call[T]) Run(run func(ctx context.Context, aggregateID string)) *MockAggregateRepository_Load_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAggregateRepository_Load_Call[T]) Return(agg T, err error) *MockAggregateRepository_Load_Call[T] {
	_c.Call.Return(agg, err)
	return _c
}

func (_c *MockAggregateRepository_Load_Call[T]) RunAndReturn(run func(context.Context, string) (T, error)) *MockAggregateRepository_Load_Call[T] {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, aggregate
func (_m *MockAggregateRepository[T]) Save(ctx context.Context, aggregate T) error {
	ret := _m.Called(ctx, aggregate)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = rf(ctx, aggregate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAggregateRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockAggregateRepository_Save_Call[T EventSourcedAggregate] struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - aggregate T
func (_e *MockAggregateRepository_Expecter[T]) Save(ctx interface{}, aggregate interface{}) *MockAggregateRepository_Save_Call[T] {
	return &MockAggregateRepository_Save_Call[T]{Call: _e.mock.On("Save", ctx, aggregate)}
}

func (_c *MockAggregateRepository_Save_Call[T]) Run(run func(ctx context.Context, aggregate T)) *MockAggregateRepository_Save_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *MockAggregateRepository_Save_Call[T]) Return(_a0 error) *MockAggregateRepository_Save_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAggregateRepository_Save_Call[T]) RunAndReturn(run func(context.Context, T) error) *MockAggregateRepository_Save_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockAggregateRepository creates a new instance of MockAggregateRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAggregateRepository[T EventSourcedAggregate](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAggregateRepository[T] {
	mock := &MockAggregateRepository[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
