// Code generated by mockery. DO NOT EDIT.

package es

import (
	ddd "github.com/owezzy/soko-bora-mngt-system/internal/ddd"
	mock "github.com/stretchr/testify/mock"
)

// MockAggregate is an autogenerated mock type for the Aggregate type
type MockAggregate struct {
	mock.Mock
}

type MockAggregate_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAggregate) EXPECT() *MockAggregate_Expecter {
	return &MockAggregate_Expecter{mock: &_m.Mock}
}

// AddEvent provides a mock function with given fields: _a0, _a1, _a2
func (_m *MockAggregate) AddEvent(_a0 string, _a1 ddd.EventPayload, _a2 ...ddd.EventOption) {
	_va := make([]interface{}, len(_a2))
	for _i := range _a2 {
		_va[_i] = _a2[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, _a0, _a1)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockAggregate_AddEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddEvent'
type MockAggregate_AddEvent_Call struct {
	*mock.Call
}

// AddEvent is a helper method to define mock.On call
//   - _a0 string
//   - _a1 ddd.EventPayload
//   - _a2 ...ddd.EventOption
func (_e *MockAggregate_Expecter) AddEvent(_a0 interface{}, _a1 interface{}, _a2 ...interface{}) *MockAggregate_AddEvent_Call {
	return &MockAggregate_AddEvent_Call{Call: _e.mock.On("AddEvent",
		append([]interface{}{_a0, _a1}, _a2...)...)}
}

func (_c *MockAggregate_AddEvent_Call) Run(run func(_a0 string, _a1 ddd.EventPayload, _a2 ...ddd.EventOption)) *MockAggregate_AddEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]ddd.EventOption, len(args)-2)
		for i, a := range args[2:] {
			if a != nil {
				variadicArgs[i] = a.(ddd.EventOption)
			}
		}
		run(args[0].(string), args[1].(ddd.EventPayload), variadicArgs...)
	})
	return _c
}

func (_c *MockAggregate_AddEvent_Call) Return() *MockAggregate_AddEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAggregate_AddEvent_Call) RunAndReturn(run func(string, ddd.EventPayload, ...ddd.EventOption)) *MockAggregate_AddEvent_Call {
	_c.Run(run)
	return _c
}

// AggregateName provides a mock function with no fields
func (_m *MockAggregate) AggregateName() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for AggregateName")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockAggregate_AggregateName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AggregateName'
type MockAggregate_AggregateName_Call struct {
	*mock.Call
}

// AggregateName is a helper method to define mock.On call
func (_e *MockAggregate_Expecter) AggregateName() *MockAggregate_AggregateName_Call {
	return &MockAggregate_AggregateName_Call{Call: _e.mock.On("AggregateName")}
}

func (_c *MockAggregate_AggregateName_Call) Run(run func()) *MockAggregate_AggregateName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregate_AggregateName_Call) Return(_a0 string) *MockAggregate_AggregateName_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAggregate_AggregateName_Call) RunAndReturn(run func() string) *MockAggregate_AggregateName_Call {
	_c.Call.Return(run)
	return _c
}

// ClearEvents provides a mock function with no fields
func (_m *MockAggregate) ClearEvents() {
	_m.Called()
}

// MockAggregate_ClearEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearEvents'
type MockAggregate_ClearEvents_Call struct {
	*mock.Call
}

// ClearEvents is a helper method to define mock.On call
func (_e *MockAggregate_Expecter) ClearEvents() *MockAggregate_ClearEvents_Call {
	return &MockAggregate_ClearEvents_Call{Call: _e.mock.On("ClearEvents")}
}

func (_c *MockAggregate_ClearEvents_Call) Run(run func()) *MockAggregate_ClearEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregate_ClearEvents_Call) Return() *MockAggregate_ClearEvents_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAggregate_ClearEvents_Call) RunAndReturn(run func()) *MockAggregate_ClearEvents_Call {
	_c.Run(run)
	return _c
}

// CommitEvents provides a mock function with no fields
func (_m *MockAggregate) CommitEvents() {
	_m.Called()
}

// MockAggregate_CommitEvents_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CommitEvents'
type MockAggregate_CommitEvents_Call struct {
	*mock.Call
}

// CommitEvents is a helper method to define mock.On call
func (_e *MockAggregate_Expecter) CommitEvents() *MockAggregate_CommitEvents_Call {
	return &MockAggregate_CommitEvents_Call{Call: _e.mock.On("CommitEvents")}
}

func (_c *MockAggregate_CommitEvents_Call) Run(run func()) *MockAggregate_CommitEvents_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregate_CommitEvents_Call) Return() *MockAggregate_CommitEvents_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAggregate_CommitEvents_Call) RunAndReturn(run func()) *MockAggregate_CommitEvents_Call {
	_c.Run(run)
	return _c
}

// Events provides a mock function with no fields
func (_m *MockAggregate) Events() []ddd.AggregateEvent {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Events")
	}

	var r0 []ddd.AggregateEvent
	if rf, ok := ret.Get(0).(func() []ddd.AggregateEvent); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]ddd.AggregateEvent)
		}
	}

	return r0
}

// MockAggregate_Events_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Events'
type MockAggregate_Events_Call struct {
	*mock.Call
}

// Events is a helper method to define mock.On call
func (_e *MockAggregate_Expecter) Events() *MockAggregate_Events_Call {
	return &MockAggregate_Events_Call{Call: _e.mock.On("Events")}
}

func (_c *MockAggregate_Events_Call) Run(run func()) *MockAggregate_Events_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregate_Events_Call) Return(_a0 []ddd.AggregateEvent) *MockAggregate_Events_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAggregate_Events_Call) RunAndReturn(run func() []ddd.AggregateEvent) *MockAggregate_Events_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function with no fields
func (_m *MockAggregate) ID() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockAggregate_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockAggregate_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockAggregate_Expecter) ID() *MockAggregate_ID_Call {
	return &MockAggregate_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockAggregate_ID_Call) Run(run func()) *MockAggregate_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregate_ID_Call) Return(_a0 string) *MockAggregate_ID_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAggregate_ID_Call) RunAndReturn(run func() string) *MockAggregate_ID_Call {
	_c.Call.Return(run)
	return _c
}

// PendingVersion provides a mock function with no fields
func (_m *MockAggregate) PendingVersion() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PendingVersion")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockAggregate_PendingVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PendingVersion'
type MockAggregate_PendingVersion_Call struct {
	*mock.Call
}

// PendingVersion is a helper method to define mock.On call
func (_e *MockAggregate_Expecter) PendingVersion() *MockAggregate_PendingVersion_Call {
	return &MockAggregate_PendingVersion_Call{Call: _e.mock.On("PendingVersion")}
}

func (_c *MockAggregate_PendingVersion_Call) Run(run func()) *MockAggregate_PendingVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregate_PendingVersion_Call) Return(_a0 int) *MockAggregate_PendingVersion_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAggregate_PendingVersion_Call) RunAndReturn(run func() int) *MockAggregate_PendingVersion_Call {
	_c.Call.Return(run)
	return _c
}

// SetID provides a mock function with given fields: _a0
func (_m *MockAggregate) SetID(_a0 string) {
	_m.Called(_a0)
}

// MockAggregate_SetID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetID'
type MockAggregate_SetID_Call struct {
	*mock.Call
}

// SetID is a helper method to define mock.On call
//   - _a0 string
func (_e *MockAggregate_Expecter) SetID(_a0 interface{}) *MockAggregate_SetID_Call {
	return &MockAggregate_SetID_Call{Call: _e.mock.On("SetID", _a0)}
}

func (_c *MockAggregate_SetID_Call) Run(run func(_a0 string)) *MockAggregate_SetID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAggregate_SetID_Call) Return() *MockAggregate_SetID_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAggregate_SetID_Call) RunAndReturn(run func(string)) *MockAggregate_SetID_Call {
	_c.Run(run)
	return _c
}

// SetName provides a mock function with given fields: _a0
func (_m *MockAggregate) SetName(_a0 string) {
	_m.Called(_a0)
}

// MockAggregate_SetName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetName'
type MockAggregate_SetName_Call struct {
	*mock.Call
}

// SetName is a helper method to define mock.On call
//   - _a0 string
func (_e *MockAggregate_Expecter) SetName(_a0 interface{}) *MockAggregate_SetName_Call {
	return &MockAggregate_SetName_Call{Call: _e.mock.On("SetName", _a0)}
}

func (_c *MockAggregate_SetName_Call) Run(run func(_a0 string)) *MockAggregate_SetName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAggregate_SetName_Call) Return() *MockAggregate_SetName_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAggregate_SetName_Call) RunAndReturn(run func(string)) *MockAggregate_SetName_Call {
	_c.Run(run)
	return _c
}

// SetVersion provides a mock function with given fields: _a0
func (_m *MockAggregate) SetVersion(_a0 int) {
	_m.Called(_a0)
}

// MockAggregate_SetVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVersion'
type MockAggregate_SetVersion_Call struct {
	*mock.Call
}

// SetVersion is a helper method to define mock.On call
//   - _a0 int
func (_e *MockAggregate_Expecter) SetVersion(_a0 interface{}) *MockAggregate_SetVersion_Call {
	return &MockAggregate_SetVersion_Call{Call: _e.mock.On("SetVersion", _a0)}
}

func (_c *MockAggregate_SetVersion_Call) Run(run func(_a0 int)) *MockAggregate_SetVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockAggregate_SetVersion_Call) Return() *MockAggregate_SetVersion_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAggregate_SetVersion_Call) RunAndReturn(run func(int)) *MockAggregate_SetVersion_Call {
	_c.Run(run)
	return _c
}

// Version provides a mock function with no fields
func (_m *MockAggregate) Version() int {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Version")
	}

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}

// MockAggregate_Version_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Version'
type MockAggregate_Version_Call struct {
	*mock.Call
}

// Version is a helper method to define mock.On call
func (_e *MockAggregate_Expecter) Version() *MockAggregate_Version_Call {
	return &MockAggregate_Version_Call{Call: _e.mock.On("Version")}
}

func (_c *MockAggregate_Version_Call) Run(run func()) *MockAggregate_Version_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAggregate_Version_Call) Return(_a0 int) *MockAggregate_Version_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAggregate_Version_Call) RunAndReturn(run func() int) *MockAggregate_Version_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAggregate creates a new instance of MockAggregate. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAggregate(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAggregate {
	mock := &MockAggregate{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
