// Code generated by mockery. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCustomerRepository is an autogenerated mock type for the CustomerRepository type
type MockCustomerRepository struct {
	mock.Mock
}

type MockCustomerRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCustomerRepository) EXPECT() *MockCustomerRepository_Expecter {
	return &MockCustomerRepository_Expecter{mock: &_m.Mock}
}

// Find provides a mock function with given fields: ctx, customerID
func (_m *MockCustomerRepository) Find(ctx context.Context, customerID string) (*Customer, error) {
	ret := _m.Called(ctx, customerID)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *Customer
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*Customer, error)); ok {
		return rf(ctx, customerID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *Customer); ok {
		r0 = rf(ctx, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Customer)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, customerID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCustomerRepository_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type MockCustomerRepository_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - customerID string
func (_e *MockCustomerRepository_Expecter) Find(ctx interface{}, customerID interface{}) *MockCustomerRepository_Find_Call {
	return &MockCustomerRepository_Find_Call{Call: _e.mock.On("Find", ctx, customerID)}
}

func (_c *MockCustomerRepository_Find_Call) Run(run func(ctx context.Context, customerID string)) *MockCustomerRepository_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockCustomerRepository_Find_Call) Return(_a0 *Customer, _a1 error) *MockCustomerRepository_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCustomerRepository_Find_Call) RunAndReturn(run func(context.Context, string) (*Customer, error)) *MockCustomerRepository_Find_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function with given fields: ctx, customer
func (_m *MockCustomerRepository) Save(ctx context.Context, customer *Customer) error {
	ret := _m.Called(ctx, customer)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Customer) error); ok {
		r0 = rf(ctx, customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCustomerRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockCustomerRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - customer *Customer
func (_e *MockCustomerRepository_Expecter) Save(ctx interface{}, customer interface{}) *MockCustomerRepository_Save_Call {
	return &MockCustomerRepository_Save_Call{Call: _e.mock.On("Save", ctx, customer)}
}

func (_c *MockCustomerRepository_Save_Call) Run(run func(ctx context.Context, customer *Customer)) *MockCustomerRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Customer))
	})
	return _c
}

func (_c *MockCustomerRepository_Save_Call) Return(_a0 error) *MockCustomerRepository_Save_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCustomerRepository_Save_Call) RunAndReturn(run func(context.Context, *Customer) error) *MockCustomerRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, customer
func (_m *MockCustomerRepository) Update(ctx context.Context, customer *Customer) error {
	ret := _m.Called(ctx, customer)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *Customer) error); ok {
		r0 = rf(ctx, customer)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCustomerRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockCustomerRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - customer *Customer
func (_e *MockCustomerRepository_Expecter) Update(ctx interface{}, customer interface{}) *MockCustomerRepository_Update_Call {
	return &MockCustomerRepository_Update_Call{Call: _e.mock.On("Update", ctx, customer)}
}

func (_c *MockCustomerRepository_Update_Call) Run(run func(ctx context.Context, customer *Customer)) *MockCustomerRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*Customer))
	})
	return _c
}

func (_c *MockCustomerRepository_Update_Call) Return(_a0 error) *MockCustomerRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCustomerRepository_Update_Call) RunAndReturn(run func(context.Context, *Customer) error) *MockCustomerRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCustomerRepository creates a new instance of MockCustomerRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCustomerRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCustomerRepository {
	mock := &MockCustomerRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
