// Code generated by mockery. DO NOT EDIT.

package ddd

import mock "github.com/stretchr/testify/mock"

// MockEventSubscriber is an autogenerated mock type for the EventSubscriber type
type MockEventSubscriber[T Event] struct {
	mock.Mock
}

type MockEventSubscriber_Expecter[T Event] struct {
	mock *mock.Mock
}

func (_m *MockEventSubscriber[T]) EXPECT() *MockEventSubscriber_Expecter[T] {
	return &MockEventSubscriber_Expecter[T]{mock: &_m.Mock}
}

// Subscribe provides a mock function with given fields: handler, events
func (_m *MockEventSubscriber[T]) Subscribe(handler EventHandler[T], events ...string) {
	_va := make([]interface{}, len(events))
	for _i := range events {
		_va[_i] = events[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, handler)
	_ca = append(_ca, _va...)
	_m.Called(_ca...)
}

// MockEventSubscriber_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockEventSubscriber_Subscribe_Call[T Event] struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - handler EventHandler[T]
//   - events ...string
func (_e *MockEventSubscriber_Expecter[T]) Subscribe(handler interface{}, events ...interface{}) *MockEventSubscriber_Subscribe_Call[T] {
	return &MockEventSubscriber_Subscribe_Call[T]{Call: _e.mock.On("Subscribe",
		append([]interface{}{handler}, events...)...)}
}

func (_c *MockEventSubscriber_Subscribe_Call[T]) Run(run func(handler EventHandler[T], events ...string)) *MockEventSubscriber_Subscribe_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]string, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(string)
			}
		}
		run(args[0].(EventHandler[T]), variadicArgs...)
	})
	return _c
}

func (_c *MockEventSubscriber_Subscribe_Call[T]) Return() *MockEventSubscriber_Subscribe_Call[T] {
	_c.Call.Return()
	return _c
}

func (_c *MockEventSubscriber_Subscribe_Call[T]) RunAndReturn(run func(EventHandler[T], ...string)) *MockEventSubscriber_Subscribe_Call[T] {
	_c.Run(run)
	return _c
}

// NewMockEventSubscriber creates a new instance of MockEventSubscriber. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventSubscriber[T Event](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventSubscriber[T] {
	mock := &MockEventSubscriber[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
