// Code generated by mockery. DO NOT EDIT.

package ddd

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockReplyHandler is an autogenerated mock type for the ReplyHandler type
type MockReplyHandler[T Reply] struct {
	mock.Mock
}

type MockReplyHandler_Expecter[T Reply] struct {
	mock *mock.Mock
}

func (_m *MockReplyHandler[T]) EXPECT() *MockReplyHandler_Expecter[T] {
	return &MockReplyHandler_Expecter[T]{mock: &_m.Mock}
}

// HandleReply provides a mock function with given fields: ctx, reply
func (_m *MockReplyHandler[T]) HandleReply(ctx context.Context, reply T) error {
	ret := _m.Called(ctx, reply)

	if len(ret) == 0 {
		panic("no return value specified for HandleReply")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, T) error); ok {
		r0 = rf(ctx, reply)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockReplyHandler_HandleReply_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleReply'
type MockReplyHandler_HandleReply_Call[T Reply] struct {
	*mock.Call
}

// HandleReply is a helper method to define mock.On call
//   - ctx context.Context
//   - reply T
func (_e *MockReplyHandler_Expecter[T]) HandleReply(ctx interface{}, reply interface{}) *MockReplyHandler_HandleReply_Call[T] {
	return &MockReplyHandler_HandleReply_Call[T]{Call: _e.mock.On("HandleReply", ctx, reply)}
}

func (_c *MockReplyHandler_HandleReply_Call[T]) Run(run func(ctx context.Context, reply T)) *MockReplyHandler_HandleReply_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *MockReplyHandler_HandleReply_Call[T]) Return(_a0 error) *MockReplyHandler_HandleReply_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockReplyHandler_HandleReply_Call[T]) RunAndReturn(run func(context.Context, T) error) *MockReplyHandler_HandleReply_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockReplyHandler creates a new instance of MockReplyHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReplyHandler[T Reply](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReplyHandler[T] {
	mock := &MockReplyHandler[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
