// Code generated by mockery. DO NOT EDIT.

package ddd

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher[T Event] struct {
	mock.Mock
}

type MockEventPublisher_Expecter[T Event] struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher[T]) EXPECT() *MockEventPublisher_Expecter[T] {
	return &MockEventPublisher_Expecter[T]{mock: &_m.Mock}
}

// Publish provides a mock function with given fields: ctx, events
func (_m *MockEventPublisher[T]) Publish(ctx context.Context, events ...T) error {
	_va := make([]interface{}, len(events))
	for _i := range events {
		_va[_i] = events[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx)
	_ca = append(_ca, _va...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, ...T) error); ok {
		r0 = rf(ctx, events...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEventPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventPublisher_Publish_Call[T Event] struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - events ...T
func (_e *MockEventPublisher_Expecter[T]) Publish(ctx interface{}, events ...interface{}) *MockEventPublisher_Publish_Call[T] {
	return &MockEventPublisher_Publish_Call[T]{Call: _e.mock.On("Publish",
		append([]interface{}{ctx}, events...)...)}
}

func (_c *MockEventPublisher_Publish_Call[T]) Run(run func(ctx context.Context, events ...T)) *MockEventPublisher_Publish_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := make([]T, len(args)-1)
		for i, a := range args[1:] {
			if a != nil {
				variadicArgs[i] = a.(T)
			}
		}
		run(args[0].(context.Context), variadicArgs...)
	})
	return _c
}

func (_c *MockEventPublisher_Publish_Call[T]) Return(_a0 error) *MockEventPublisher_Publish_Call[T] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEventPublisher_Publish_Call[T]) RunAndReturn(run func(context.Context, ...T) error) *MockEventPublisher_Publish_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher[T Event](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher[T] {
	mock := &MockEventPublisher[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
