// Code generated by mockery. DO NOT EDIT.

package ddd

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockCommandHandler is an autogenerated mock type for the CommandHandler type
type MockCommandHandler[T Command] struct {
	mock.Mock
}

type MockCommandHandler_Expecter[T Command] struct {
	mock *mock.Mock
}

func (_m *MockCommandHandler[T]) EXPECT() *MockCommandHandler_Expecter[T] {
	return &MockCommandHandler_Expecter[T]{mock: &_m.Mock}
}

// HandleCommand provides a mock function with given fields: ctx, cmd
func (_m *MockCommandHandler[T]) HandleCommand(ctx context.Context, cmd T) (Reply, error) {
	ret := _m.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for HandleCommand")
	}

	var r0 Reply
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, T) (Reply, error)); ok {
		return rf(ctx, cmd)
	}
	if rf, ok := ret.Get(0).(func(context.Context, T) Reply); ok {
		r0 = rf(ctx, cmd)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(Reply)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, T) error); ok {
		r1 = rf(ctx, cmd)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockCommandHandler_HandleCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleCommand'
type MockCommandHandler_HandleCommand_Call[T Command] struct {
	*mock.Call
}

// HandleCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd T
func (_e *MockCommandHandler_Expecter[T]) HandleCommand(ctx interface{}, cmd interface{}) *MockCommandHandler_HandleCommand_Call[T] {
	return &MockCommandHandler_HandleCommand_Call[T]{Call: _e.mock.On("HandleCommand", ctx, cmd)}
}

func (_c *MockCommandHandler_HandleCommand_Call[T]) Run(run func(ctx context.Context, cmd T)) *MockCommandHandler_HandleCommand_Call[T] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(T))
	})
	return _c
}

func (_c *MockCommandHandler_HandleCommand_Call[T]) Return(_a0 Reply, _a1 error) *MockCommandHandler_HandleCommand_Call[T] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockCommandHandler_HandleCommand_Call[T]) RunAndReturn(run func(context.Context, T) (Reply, error)) *MockCommandHandler_HandleCommand_Call[T] {
	_c.Call.Return(run)
	return _c
}

// NewMockCommandHandler creates a new instance of MockCommandHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandHandler[T Command](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandHandler[T] {
	mock := &MockCommandHandler[T]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
