// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts,import_extension=.ts"
// @generated from file customerspb/api.proto (package customerspb, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { AuthorizeCustomerRequest, AuthorizeCustomerResponse, ChangeSmsNumberRequest, ChangeSmsNumberResponse, DisableCustomerRequest, DisableCustomerResponse, EnableCustomerRequest, EnableCustomerResponse, GetCustomerRequest, GetCustomerResponse, RegisterCustomerRequest, RegisterCustomerResponse } from "./api_pb.ts";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service customerspb.CustomersService
 */
export const CustomersService = {
  typeName: "customerspb.CustomersService",
  methods: {
    /**
     * @generated from rpc customerspb.CustomersService.RegisterCustomer
     */
    registerCustomer: {
      name: "RegisterCustomer",
      I: RegisterCustomerRequest,
      O: RegisterCustomerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc customerspb.CustomersService.EnableCustomer
     */
    enableCustomer: {
      name: "EnableCustomer",
      I: EnableCustomerRequest,
      O: EnableCustomerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc customerspb.CustomersService.DisableCustomer
     */
    disableCustomer: {
      name: "DisableCustomer",
      I: DisableCustomerRequest,
      O: DisableCustomerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc customerspb.CustomersService.ChangeSmsNumber
     */
    changeSmsNumber: {
      name: "ChangeSmsNumber",
      I: ChangeSmsNumberRequest,
      O: ChangeSmsNumberResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc customerspb.CustomersService.AuthorizeCustomer
     */
    authorizeCustomer: {
      name: "AuthorizeCustomer",
      I: AuthorizeCustomerRequest,
      O: AuthorizeCustomerResponse,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc customerspb.CustomersService.GetCustomer
     */
    getCustomer: {
      name: "GetCustomer",
      I: GetCustomerRequest,
      O: GetCustomerResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

