// @generated by protoc-gen-es v2.5.2 with parameter "target=ts,import_extension=.ts"
// @generated from file customerspb/api.proto (package customerspb, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file customerspb/api.proto.
 */
export const file_customerspb_api: GenFile = /*@__PURE__*/
  fileDesc("ChVjdXN0b21lcnNwYi9hcGkucHJvdG8SC2N1c3RvbWVyc3BiIkkKCEN1c3RvbWVyEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSEgoKc21zX251bWJlchgDIAEoCRIPCgdlbmFibGVkGAQgASgIIjsKF1JlZ2lzdGVyQ3VzdG9tZXJSZXF1ZXN0EgwKBG5hbWUYASABKAkSEgoKc21zX251bWJlchgCIAEoCSImChhSZWdpc3RlckN1c3RvbWVyUmVzcG9uc2USCgoCaWQYASABKAkiIwoVRW5hYmxlQ3VzdG9tZXJSZXF1ZXN0EgoKAmlkGAEgASgJIhgKFkVuYWJsZUN1c3RvbWVyUmVzcG9uc2UiJAoWRGlzYWJsZUN1c3RvbWVyUmVxdWVzdBIKCgJpZBgBIAEoCSIZChdEaXNhYmxlQ3VzdG9tZXJSZXNwb25zZSI4ChZDaGFuZ2VTbXNOdW1iZXJSZXF1ZXN0EgoKAmlkGAEgASgJEhIKCnNtc19udW1iZXIYAiABKAkiGQoXQ2hhbmdlU21zTnVtYmVyUmVzcG9uc2UiJgoYQXV0aG9yaXplQ3VzdG9tZXJSZXF1ZXN0EgoKAmlkGAEgASgJIhsKGUF1dGhvcml6ZUN1c3RvbWVyUmVzcG9uc2UiIAoSR2V0Q3VzdG9tZXJSZXF1ZXN0EgoKAmlkGAEgASgJIj4KE0dldEN1c3RvbWVyUmVzcG9uc2USJwoIY3VzdG9tZXIYASABKAsyFS5jdXN0b21lcnNwYi5DdXN0b21lcjLMBAoQQ3VzdG9tZXJzU2VydmljZRJhChBSZWdpc3RlckN1c3RvbWVyEiQuY3VzdG9tZXJzcGIuUmVnaXN0ZXJDdXN0b21lclJlcXVlc3QaJS5jdXN0b21lcnNwYi5SZWdpc3RlckN1c3RvbWVyUmVzcG9uc2UiABJbCg5FbmFibGVDdXN0b21lchIiLmN1c3RvbWVyc3BiLkVuYWJsZUN1c3RvbWVyUmVxdWVzdBojLmN1c3RvbWVyc3BiLkVuYWJsZUN1c3RvbWVyUmVzcG9uc2UiABJeCg9EaXNhYmxlQ3VzdG9tZXISIy5jdXN0b21lcnNwYi5EaXNhYmxlQ3VzdG9tZXJSZXF1ZXN0GiQuY3VzdG9tZXJzcGIuRGlzYWJsZUN1c3RvbWVyUmVzcG9uc2UiABJeCg9DaGFuZ2VTbXNOdW1iZXISIy5jdXN0b21lcnNwYi5DaGFuZ2VTbXNOdW1iZXJSZXF1ZXN0GiQuY3VzdG9tZXJzcGIuQ2hhbmdlU21zTnVtYmVyUmVzcG9uc2UiABJkChFBdXRob3JpemVDdXN0b21lchIlLmN1c3RvbWVyc3BiLkF1dGhvcml6ZUN1c3RvbWVyUmVxdWVzdBomLmN1c3RvbWVyc3BiLkF1dGhvcml6ZUN1c3RvbWVyUmVzcG9uc2UiABJSCgtHZXRDdXN0b21lchIfLmN1c3RvbWVyc3BiLkdldEN1c3RvbWVyUmVxdWVzdBogLmN1c3RvbWVyc3BiLkdldEN1c3RvbWVyUmVzcG9uc2UiAEKmAQoPY29tLmN1c3RvbWVyc3BiQghBcGlQcm90b1ABWj1naXRodWIuY29tL293ZXp6eS9zb2tvLWJvcmEtbW5ndC1zeXN0ZW0vY3VzdG9tZXJzL2N1c3RvbWVyc3BiogIDQ1hYqgILQ3VzdG9tZXJzcGLKAgtDdXN0b21lcnNwYuICF0N1c3RvbWVyc3BiXEdQQk1ldGFkYXRh6gILQ3VzdG9tZXJzcGJiBnByb3RvMw");

/**
 * @generated from message customerspb.Customer
 */
export type Customer = Message<"customerspb.Customer"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string sms_number = 3;
   */
  smsNumber: string;

  /**
   * @generated from field: bool enabled = 4;
   */
  enabled: boolean;
};

/**
 * Describes the message customerspb.Customer.
 * Use `create(CustomerSchema)` to create a new message.
 */
export const CustomerSchema: GenMessage<Customer> = /*@__PURE__*/
  messageDesc(file_customerspb_api, 0);

/**
 * @generated from message customerspb.RegisterCustomerRequest
 */
export type RegisterCustomerRequest = Message<"customerspb.RegisterCustomerRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string sms_number = 2;
   */
  smsNumber: string;
};

/**
 * Describes the message customerspb.RegisterCustomerRequest.
 * Use `create(RegisterCustomerRequestSchema)` to create a new message.
 */
export const RegisterCustomerRequestSchema: GenMessage<RegisterCustomerRequest> = /*@__PURE__*/
  messageDesc(file_customerspb_api, 1);

/**
 * @generated from message customerspb.RegisterCustomerResponse
 */
export type RegisterCustomerResponse = Message<"customerspb.RegisterCustomerResponse"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message customerspb.RegisterCustomerResponse.
 * Use `create(RegisterCustomerResponseSchema)` to create a new message.
 */
export const RegisterCustomerResponseSchema: GenMessage<RegisterCustomerResponse> = /*@__PURE__*/
  messageDesc(file_customerspb_api, 2);

/**
 * @generated from message customerspb.EnableCustomerRequest
 */
export type EnableCustomerRequest = Message<"customerspb.EnableCustomerRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message customerspb.EnableCustomerRequest.
 * Use `create(EnableCustomerRequestSchema)` to create a new message.
 */
export const EnableCustomerRequestSchema: GenMessage<EnableCustomerRequest> = /*@__PURE__*/
  messageDesc(file_customerspb_api, 3);

/**
 * @generated from message customerspb.EnableCustomerResponse
 */
export type EnableCustomerResponse = Message<"customerspb.EnableCustomerResponse"> & {
};

/**
 * Describes the message customerspb.EnableCustomerResponse.
 * Use `create(EnableCustomerResponseSchema)` to create a new message.
 */
export const EnableCustomerResponseSchema: GenMessage<EnableCustomerResponse> = /*@__PURE__*/
  messageDesc(file_customerspb_api, 4);

/**
 * @generated from message customerspb.DisableCustomerRequest
 */
export type DisableCustomerRequest = Message<"customerspb.DisableCustomerRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message customerspb.DisableCustomerRequest.
 * Use `create(DisableCustomerRequestSchema)` to create a new message.
 */
export const DisableCustomerRequestSchema: GenMessage<DisableCustomerRequest> = /*@__PURE__*/
  messageDesc(file_customerspb_api, 5);

/**
 * @generated from message customerspb.DisableCustomerResponse
 */
export type DisableCustomerResponse = Message<"customerspb.DisableCustomerResponse"> & {
};

/**
 * Describes the message customerspb.DisableCustomerResponse.
 * Use `create(DisableCustomerResponseSchema)` to create a new message.
 */
export const DisableCustomerResponseSchema: GenMessage<DisableCustomerResponse> = /*@__PURE__*/
  messageDesc(file_customerspb_api, 6);

/**
 * @generated from message customerspb.ChangeSmsNumberRequest
 */
export type ChangeSmsNumberRequest = Message<"customerspb.ChangeSmsNumberRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string sms_number = 2;
   */
  smsNumber: string;
};

/**
 * Describes the message customerspb.ChangeSmsNumberRequest.
 * Use `create(ChangeSmsNumberRequestSchema)` to create a new message.
 */
export const ChangeSmsNumberRequestSchema: GenMessage<ChangeSmsNumberRequest> = /*@__PURE__*/
  messageDesc(file_customerspb_api, 7);

/**
 * @generated from message customerspb.ChangeSmsNumberResponse
 */
export type ChangeSmsNumberResponse = Message<"customerspb.ChangeSmsNumberResponse"> & {
};

/**
 * Describes the message customerspb.ChangeSmsNumberResponse.
 * Use `create(ChangeSmsNumberResponseSchema)` to create a new message.
 */
export const ChangeSmsNumberResponseSchema: GenMessage<ChangeSmsNumberResponse> = /*@__PURE__*/
  messageDesc(file_customerspb_api, 8);

/**
 * @generated from message customerspb.AuthorizeCustomerRequest
 */
export type AuthorizeCustomerRequest = Message<"customerspb.AuthorizeCustomerRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message customerspb.AuthorizeCustomerRequest.
 * Use `create(AuthorizeCustomerRequestSchema)` to create a new message.
 */
export const AuthorizeCustomerRequestSchema: GenMessage<AuthorizeCustomerRequest> = /*@__PURE__*/
  messageDesc(file_customerspb_api, 9);

/**
 * @generated from message customerspb.AuthorizeCustomerResponse
 */
export type AuthorizeCustomerResponse = Message<"customerspb.AuthorizeCustomerResponse"> & {
};

/**
 * Describes the message customerspb.AuthorizeCustomerResponse.
 * Use `create(AuthorizeCustomerResponseSchema)` to create a new message.
 */
export const AuthorizeCustomerResponseSchema: GenMessage<AuthorizeCustomerResponse> = /*@__PURE__*/
  messageDesc(file_customerspb_api, 10);

/**
 * @generated from message customerspb.GetCustomerRequest
 */
export type GetCustomerRequest = Message<"customerspb.GetCustomerRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message customerspb.GetCustomerRequest.
 * Use `create(GetCustomerRequestSchema)` to create a new message.
 */
export const GetCustomerRequestSchema: GenMessage<GetCustomerRequest> = /*@__PURE__*/
  messageDesc(file_customerspb_api, 11);

/**
 * @generated from message customerspb.GetCustomerResponse
 */
export type GetCustomerResponse = Message<"customerspb.GetCustomerResponse"> & {
  /**
   * @generated from field: customerspb.Customer customer = 1;
   */
  customer?: Customer;
};

/**
 * Describes the message customerspb.GetCustomerResponse.
 * Use `create(GetCustomerResponseSchema)` to create a new message.
 */
export const GetCustomerResponseSchema: GenMessage<GetCustomerResponse> = /*@__PURE__*/
  messageDesc(file_customerspb_api, 12);

/**
 * @generated from service customerspb.CustomersService
 */
export const CustomersService: GenService<{
  /**
   * @generated from rpc customerspb.CustomersService.RegisterCustomer
   */
  registerCustomer: {
    methodKind: "unary";
    input: typeof RegisterCustomerRequestSchema;
    output: typeof RegisterCustomerResponseSchema;
  },
  /**
   * @generated from rpc customerspb.CustomersService.EnableCustomer
   */
  enableCustomer: {
    methodKind: "unary";
    input: typeof EnableCustomerRequestSchema;
    output: typeof EnableCustomerResponseSchema;
  },
  /**
   * @generated from rpc customerspb.CustomersService.DisableCustomer
   */
  disableCustomer: {
    methodKind: "unary";
    input: typeof DisableCustomerRequestSchema;
    output: typeof DisableCustomerResponseSchema;
  },
  /**
   * @generated from rpc customerspb.CustomersService.ChangeSmsNumber
   */
  changeSmsNumber: {
    methodKind: "unary";
    input: typeof ChangeSmsNumberRequestSchema;
    output: typeof ChangeSmsNumberResponseSchema;
  },
  /**
   * @generated from rpc customerspb.CustomersService.AuthorizeCustomer
   */
  authorizeCustomer: {
    methodKind: "unary";
    input: typeof AuthorizeCustomerRequestSchema;
    output: typeof AuthorizeCustomerResponseSchema;
  },
  /**
   * @generated from rpc customerspb.CustomersService.GetCustomer
   */
  getCustomer: {
    methodKind: "unary";
    input: typeof GetCustomerRequestSchema;
    output: typeof GetCustomerResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_customerspb_api, 0);

